// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.cipher.Encryption;
import java.util.function.UnaryOperator;

/** AddReceiverResponse */
public class AddReceiverResponse {
  /** 서브 가맹점 번호 설명: 요청 파라미터 참조 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 수신자 유형 설명: 요청 파라미터 참조 */
  @SerializedName("type")
  private ReceiverType type;

  /** 수신자 계정 설명: 요청 파라미터 참조 */
  @SerializedName("account")
  private String account;

  /** 수익 분배 수신자 전체 이름 설명: 요청 파라미터 참조. APIv3 민감 정보 암호화 방식 사용 */
  @Encryption
  @SerializedName("name")
  private String name;

  /** 수익 분배 방과의 관계 유형 설명: 요청 파라미터 참조 */
  @SerializedName("relation_type")
  private ReceiverRelationType relationType;

  /** 사용자 정의 수익 분배 관계 설명: 요청 파라미터 참조 */
  @SerializedName("custom_relation")
  private String customRelation;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public ReceiverType getType() {
    return type;
  }

  public void setType(ReceiverType type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ReceiverRelationType getRelationType() {
    return relationType;
  }

  public void setRelationType(ReceiverRelationType relationType) {
    this.relationType = relationType;
  }

  public String getCustomRelation() {
    return customRelation;
  }

  public void setCustomRelation(String customRelation) {
    this.customRelation = customRelation;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddReceiverResponse {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("    customRelation: ").append(toIndentedString(customRelation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  public AddReceiverResponse cloneWithCipher(UnaryOperator<String> s) {
    AddReceiverResponse copy = new AddReceiverResponse();
    copy.subMchid = subMchid;
    copy.type = type;
    copy.account = account;
    if (name != null && !name.isEmpty()) {
      copy.name = s.apply(name);
    }
    copy.relationType = relationType;
    copy.customRelation = customRelation;
    return copy;
  }
}
