// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.cipher.Encryption;
import java.util.function.UnaryOperator;

/** AddReceiverRequest */
public class AddReceiverRequest {
  /** 서브 가맹점 번호 설명: 위챗페이가 할당한 서브 가맹점 번호, 즉 수익 분배의 출자 가맹점 번호. (직접 연결 가맹점은 불필요, 서비스 제공자는 필요) */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 공개 계정 ID 설명: 위챗페이가 할당한 공개 계정 ID */
  @SerializedName("appid")
  private String appid;

  /** 서브 가맹점 공개 계정 ID 설명: 서브 가맹점의 공개 계정 ID, 수익 분배 수신자 유형에 PERSONAL_SUB_OPENID가 포함된 경우 필수. (직접 연결 가맹점은 불필요, 서비스 제공자는 필요) */
  @SerializedName("sub_appid")
  private String subAppid;

  /**
   * 수신자 유형 설명: 열거형 값: MERCHANT_ID: 가맹점 ID PERSONAL_OPENID: 개인 openid (부모 가맹점 APPID에서 변환)
   * PERSONAL_SUB_OPENID: 개인 sub_openid (서브 가맹점 APPID에서 변환)
   */
  @SerializedName("type")
  private ReceiverType type;

  /**
   * 수신자 계정 설명: 유형이 MERCHANT_ID인 경우, 가맹점 번호 유형이 PERSONAL_OPENID인 경우, 개인 openid
   * 유형이 PERSONAL_SUB_OPENID인 경우, 개인 sub_openid
   */
  @SerializedName("account")
  private String account;

  /**
   * 수익 분배 수신자 전체 이름 설명: 수익 분배 수신자 유형이 MERCHANT_ID인 경우, 가맹점 전체 이름 (필수 전달), 가맹점이 소규모 가맹점 또는 개인 사업자일 때, 계좌 개설자 이름
   * 수익 분배 수신자 유형이 PERSONAL_OPENID인 경우, 개인 이름 (선택 전달, 전달 시 검증) 수익 분배 수신자 유형이 PERSONAL_SUB_OPENID인 경우, 개인 이름 (선택 전달, 전달 시 검증)
   * 1. 이 필드는 암호화가 필요하며, 암호화 방법은 민감 정보 암호화 설명 참조 2. 위챗페이 플랫폼 인증서의 공개 키 사용 3. RSAES-OAEP 알고리즘으로 암호화
   * 4. 요청의 HTTP 헤더 Wechatpay-Serial을 인증서 일련 번호로 설정
   */
  @Encryption
  @SerializedName("name")
  private String name;

  /**
   * 수익 분배 방과의 관계 유형 설명: 서브 가맹점과 수신자의 관계. 이 필드 값은 열거형: SERVICE_PROVIDER: 서비스 제공자 STORE: 매장 STAFF: 직원 STORE_OWNER: 점주
   * PARTNER: 파트너 HEADQUARTER: 본부 BRAND: 브랜드 측 DISTRIBUTOR: 유통업자 USER: 사용자 SUPPLIER: 공급업체 CUSTOM: 사용자 정의
   */
  @SerializedName("relation_type")
  private ReceiverRelationType relationType;

  /**
   * 사용자 정의 수익 분배 관계 설명: 서브 가맹점과 수신자의 구체적인 관계, 이 필드는 최대 10자. relation_type 필드 값이 CUSTOM일 때, 이 필드는 필수
   * relation_type 필드 값이 CUSTOM이 아닐 때, 이 필드는 작성할 필요 없음
   */
  @SerializedName("custom_relation")
  private String customRelation;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getSubAppid() {
    return subAppid;
  }

  public void setSubAppid(String subAppid) {
    this.subAppid = subAppid;
  }

  public ReceiverType getType() {
    return type;
  }

  public void setType(ReceiverType type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ReceiverRelationType getRelationType() {
    return relationType;
  }

  public void setRelationType(ReceiverRelationType relationType) {
    this.relationType = relationType;
  }

  public String getCustomRelation() {
    return customRelation;
  }

  public void setCustomRelation(String customRelation) {
    this.customRelation = customRelation;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddReceiverRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    subAppid: ").append(toIndentedString(subAppid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("    customRelation: ").append(toIndentedString(customRelation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  public AddReceiverRequest cloneWithCipher(UnaryOperator<String> s) {
    AddReceiverRequest copy = new AddReceiverRequest();
    copy.subMchid = subMchid;
    copy.appid = appid;
    copy.subAppid = subAppid;
    copy.type = type;
    copy.account = account;
    if (name != null && !name.isEmpty()) {
      copy.name = s.apply(name);
    }
    copy.relationType = relationType;
    copy.customRelation = customRelation;
    return copy;
  }
}
