// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** DeleteReceiverRequest */
public class DeleteReceiverRequest {
  /** 서브 가맹점 번호 설명: 위챗페이가 할당한 서브 가맹점 번호, 즉 수익 분배의 출자 가맹점 번호. (직접 연결 가맹점은 불필요, 서비스 제공자는 필요) */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 공개 계정 ID 설명: 위챗페이가 할당한 공개 계정 ID */
  @SerializedName("appid")
  private String appid;

  /** 서브 가맹점 공개 계정 ID 설명: 위챗페이가 할당한 서브 가맹점 공개 계정 ID, 수익 분배 수신자 유형에 PERSONAL_SUB_OPENID가 포함된 경우 필수. (직접 연결 가맹점은 불필요, 서비스 제공자는 필요) */
  @SerializedName("sub_appid")
  private String subAppid;

  /**
   * 수신자 유형 설명: 열거형 값: MERCHANT_ID: 가맹점 ID PERSONAL_OPENID: 개인 openid (부모 가맹점 APPID에서 변환)
   * PERSONAL_SUB_OPENID: 개인 sub_openid (서브 가맹점 APPID에서 변환)
   */
  @SerializedName("type")
  private ReceiverType type;

  /**
   * 수신자 계정 설명: 유형이 MERCHANT\\_ID인 경우, 가맹점 번호 유형이 PERSONAL\\_OPENID인 경우, 개인 openid
   * [openid 획득 방법](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/open/pay/chapter3_3_1.shtml#part-13)
   */
  @SerializedName("account")
  private String account;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getSubAppid() {
    return subAppid;
  }

  public void setSubAppid(String subAppid) {
    this.subAppid = subAppid;
  }

  public ReceiverType getType() {
    return type;
  }

  public void setType(ReceiverType type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteReceiverRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    subAppid: ").append(toIndentedString(subAppid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
