// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** DeleteReceiverResponse */
public class DeleteReceiverResponse {
  /** 서브 가맹점 번호 설명: 요청 파라미터 참조 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 수신자 유형 설명: 요청 파라미터 참조 */
  @SerializedName("type")
  private ReceiverType type;

  /** 수신자 계정 설명: 요청 파라미터 참조 */
  @SerializedName("account")
  private String account;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public ReceiverType getType() {
    return type;
  }

  public void setType(ReceiverType type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteReceiverResponse {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
