// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** QueryMerchantRatioResponse */
public class QueryMerchantRatioResponse {
  /** 서브 가맹점 번호 설명: 요청 파라미터 참조 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 최대 수익 분배 비율 설명: 서브 가맹점이 부모 가맹점의 수익 분배를 허용하는 최대 비율, 단위는 만분율, 예: 2000은 20%를 의미 */
  @SerializedName("max_ratio")
  private Long maxRatio;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public Long getMaxRatio() {
    return maxRatio;
  }

  public void setMaxRatio(Long maxRatio) {
    this.maxRatio = maxRatio;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryMerchantRatioResponse {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    maxRatio: ").append(toIndentedString(maxRatio)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
