// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import com.google.gson.annotations.SerializedName;

/** ReceiverType */
public enum ReceiverType {
  @SerializedName("MERCHANT_ID")
  MERCHANT_ID,

  @SerializedName("PERSONAL_OPENID")
  PERSONAL_OPENID,

  @SerializedName("PERSONAL_SUB_OPENID")
  PERSONAL_SUB_OPENID
}
