// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import com.google.gson.annotations.SerializedName;

/** ReceiverRelationType */
public enum ReceiverRelationType {
  @SerializedName("SERVICE_PROVIDER")
  SERVICE_PROVIDER,

  @SerializedName("STORE")
  STORE,

  @SerializedName("STAFF")
  STAFF,

  @SerializedName("STORE_OWNER")
  STORE_OWNER,

  @SerializedName("PARTNER")
  PARTNER,

  @SerializedName("HEADQUARTER")
  HEADQUARTER,

  @SerializedName("BRAND")
  BRAND,

  @SerializedName("DISTRIBUTOR")
  DISTRIBUTOR,

  @SerializedName("USER")
  USER,

  @SerializedName("SUPPLIER")
  SUPPLIER,

  @SerializedName("CUSTOM")
  CUSTOM
}
