// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import com.google.gson.annotations.SerializedName;

/** ReturnOrderFailReason */
public enum ReturnOrderFailReason {
  @SerializedName("ACCOUNT_ABNORMAL")
  ACCOUNT_ABNORMAL,

  @SerializedName("BALANCE_NOT_ENOUGH")
  BALANCE_NOT_ENOUGH,

  @SerializedName("TIME_OUT_CLOSED")
  TIME_OUT_CLOSED,

  @SerializedName("PAYER_ACCOUNT_ABNORMAL")
  PAYER_ACCOUNT_ABNORMAL,

  @SerializedName("INVALID_REQUEST")
  INVALID_REQUEST
}
