// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** SplitBillRequest */
public class SplitBillRequest {
  /** 서브 가맹점 번호 설명: 가맹점이 직접 연결 가맹점인 경우: - 이 필드를 작성할 필요 없음 가맹점이 서비스 제공자인 경우: - 작성하지 않으면 기본적으로 서비스 제공자 하위의 모든 수익 분배 청구서 반환. - 특정 서브 가맹점 하위의 수익 분배 청구서를 다운로드하려면 지정된 서브 가맹점 번호를 입력. */
  @SerializedName("sub_mchid")
  @Expose(serialize = false)
  private String subMchid;

  /** 청구서 날짜 설명: 형식 YYYY-MM-DD. 3개월 이내의 청구서 다운로드 신청만 지원. */
  @SerializedName("bill_date")
  @Expose(serialize = false)
  private String billDate;

  /** 압축 유형 설명: 작성하지 않으면 압축하지 않은 방식으로 데이터 스트림 반환 */
  @SerializedName("tar_type")
  @Expose(serialize = false)
  private SplitBillTarType tarType;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getBillDate() {
    return billDate;
  }

  public void setBillDate(String billDate) {
    this.billDate = billDate;
  }

  public SplitBillTarType getTarType() {
    return tarType;
  }

  public void setTarType(SplitBillTarType tarType) {
    this.tarType = tarType;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SplitBillRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    billDate: ").append(toIndentedString(billDate)).append("\n");
    sb.append("    tarType: ").append(toIndentedString(tarType)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
