// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 수익 분배 API
//
// 위챗페이 수익 분배 API
//
// API version: 0.0.9

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.profitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** UnfreezeOrderRequest */
public class UnfreezeOrderRequest {
  /** 서브 가맹점 번호 설명: 위챗페이가 할당한 서브 가맹점 번호, 즉 수익 분배의 출자 가맹점 번호. (직접 연결 가맹점은 불필요, 서비스 제공자는 필요) */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 위챗페이 주문 번호 설명: 위챗페이 주문 번호 */
  @SerializedName("transaction_id")
  private String transactionId;

  /** 가맹점 수익 분배 단 번호 설명: 가맹점 시스템 내부의 수익 분배 단 번호, 가맹점 시스템 내부에서 고유, 동일한 수익 분배 단 번호로 여러 번 요청해도 한 번과 동일. 숫자, 대소문자 _-|*@만 가능 */
  @SerializedName("out_order_no")
  private String outOrderNo;

  /** 수익 분배 설명 설명: 수익 분배 사유 설명, 수익 분배 청구서에 표시되어야 함 */
  @SerializedName("description")
  private String description;

  /** 수익 분배 결과 콜백 url 설명: 위챗페이 수익 분배 결과 알림을 비동기로 수신하는 콜백 주소, 알림 url은 외부에서 접근 가능한 url이어야 하며 매개변수를 포함할 수 없음 */
  @SerializedName("notify_url")
  private String notifyUrl;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnfreezeOrderRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    outOrderNo: ").append(toIndentedString(outOrderNo)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
