// Copyright 2021 Tencent Inc. All rights reserved.
//
// Native 결제
//
// Native 결제 API
//
// API version: 1.2.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payments.nativepay.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** Amount */
public class Amount {
  /** 총액 설명: 주문 총액, 단위는 분 */
  @SerializedName("total")
  private Integer total;

  /** 통화 유형 설명: CNY: 위안화, 국내 가맹점 번호는 위안화만 지원 */
  @SerializedName("currency")
  private String currency;

  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Amount {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
