// Copyright 2021 Tencent Inc. All rights reserved.
//
// 체인 가맹 공급망 분할 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 1.0.12

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.brandprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** AddReceiverRequest */
public class AddReceiverRequest {
  /** 브랜드 주 가맹점 번호 설명: 브랜드 주 가맹점 번호는 특정 브랜드에 바인딩된 가맹점 번호이며, 위챗페이가 할당한 가맹점 번호를 입력 */
  @SerializedName("brand_mchid")
  private String brandMchid;

  /** 공개 계정 ID 설명: 위챗이 할당한 공개 계정 ID */
  @SerializedName("appid")
  private String appid;

  /** 하위 가맹점 공개 계정 ID 설명: 브랜드 주인의 공개 계정 ID, 분할 수취인 유형에 PERSONAL_SUB_OPENID가 포함된 경우 필수 */
  @SerializedName("sub_appid")
  private String subAppid;

  /**
   * 수취인 유형 설명: 분할 수취인 유형, 열거형 값: 1. MERCHANT_ID: 가맹점 번호(mch_id 또는 sub_mch_id) 2. PERSONAL_OPENID: 개인 OpenID(서비스 제공업체의 AppID에서 변환됨) 3. PERSONAL_SUB_OPENID: 개인 OpenID(브랜드 주인의 AppID에서 변환됨)
   */
  @SerializedName("type")
  private String type;

  /**
   * 수취인 계정 설명: 분할 수취인 계정 1. 분할 수취인 유형이 MERCHANT_ID일 때, 분할 수취인 계정은 가맹점 번호(mch_id 또는 sub_mch_id) 2. 분할 수취인 유형이 PERSONAL_OPENID일 때, 분할 수취인 계정은 개인 OpenID(서비스 제공업체의 AppID에서 변환됨) 3. 분할 수취인 유형이 PERSONAL_SUB_OPENID일 때, 분할 수취인 계정은 개인 OpenID(브랜드 주인의 AppID에서 변환됨)
   */
  @SerializedName("account")
  private String account;

  /**
   * 수취인 이름 설명: 분할 수취인의 이름. 1. type이 MERCHANT_ID일 때, 수취인 이름은 필수이며, 가맹점 전체 이름임. 2. type이 PERSONAL_OPENID일 때, 수취인 이름은 선택이며, 개인 이름임.(이 필드를 전달할 때 검증이 필요함.) 3. type이 PERSONAL_SUB_OPENID일 때, 수취인 이름은 선택이며, 개인 이름임.(이 필드를 전달할 때 검증이 필요함.)
   */
  @SerializedName("name")
  private String name;

  /**
   * 브랜드 주인과의 관계 유형 설명: 열거형 값: - SUPPLIER: 공급업체 - DISTRIBUTOR: 유통업체 - SERVICE_PROVIDER: 서비스 제공업체 - PLATFORM: 플랫폼 - STAFF: 직원 - OTHERS: 기타
   */
  @SerializedName("relation_type")
  private String relationType;

  public String getBrandMchid() {
    return brandMchid;
  }

  public void setBrandMchid(String brandMchid) {
    this.brandMchid = brandMchid;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getSubAppid() {
    return subAppid;
  }

  public void setSubAppid(String subAppid) {
    this.subAppid = subAppid;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getRelationType() {
    return relationType;
  }

  public void setRelationType(String relationType) {
    this.relationType = relationType;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddReceiverRequest {\n");
    sb.append("    brandMchid: ").append(toIndentedString(brandMchid)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    subAppid: ").append(toIndentedString(subAppid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
