// Copyright 2021 Tencent Inc. All rights reserved.
//
// 체인 가맹 공급망 분할 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 1.0.12

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.brandprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** QueryOrderRequest */
public class QueryOrderRequest {
  /** 하위 가맹점 번호 설명: 주문 수취 가맹점 번호, 위챗페이가 할당한 가맹점 번호 입력 */
  @SerializedName("sub_mchid")
  @Expose(serialize = false)
  private String subMchid;

  /** 위챗 주문 번호 설명: 위챗페이 주문 번호 */
  @SerializedName("transaction_id")
  @Expose(serialize = false)
  private String transactionId;

  /** 가맹점 분할 내역 번호 설명: 가맹점 시스템 내부의 분할 내역 번호, 가맹점 시스템 내부에서 고유함(분할, 완료 분할은 서로 다른 가맹점 분할 내역 번호를 사용해야 함), 동일 분할 내역 번호에 대한 여러 요청은 한 번과 동일함 */
  @SerializedName("out_order_no")
  @Expose(serialize = false)
  private String outOrderNo;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryOrderRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    outOrderNo: ").append(toIndentedString(outOrderNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
