// Copyright 2021 Tencent Inc. All rights reserved.
//
// 체인 가맹 공급망 분할 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 1.0.12

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.brandprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** ReceiverResultEntity */
public class ReceiverResultEntity {
  /**
   * 수취인 유형 설명: 열거형 값: 1. MERCHANT_ID: 가맹점 ID 2. PERSONAL_OPENID: 개인 OpenID(상위 가맹점 AppID에서 변환됨) 3. PERSONAL_SUB_OPENID: 개인 OpenID(브랜드 주인의 AppID에서 변환됨)
   */
  @SerializedName("type")
  private String type;

  /**
   * 수취인 계정 설명: 1. 분할 수취인 유형이 MERCHANT_ID일 때, 분할 수취인 계정은 가맹점 번호(mch_id 또는 sub_mch_id) 2. 분할 수취인 유형이 PERSONAL_OPENID일 때, 분할 수취인 계정은 개인 OpenID(서비스 제공업체의 AppID에서 변환됨) 3. 분할 수취인 유형이 PERSONAL_SUB_OPENID일 때, 분할 수취인 계정은 개인 OpenID(브랜드 주인의 AppID에서 변환됨)
   */
  @SerializedName("account")
  private String account;

  /** 분할 금액 설명: 분할 금액, 단위는 분, 정수만 가능 */
  @SerializedName("amount")
  private Long amount;

  /** 분할 설명 설명: 분할 사유 설명, 분할 청구서에 표시되어야 함 */
  @SerializedName("description")
  private String description;

  /** 분할 결과 설명: 열거형 값: - PENDING: 분할 대기 - SUCCESS: 분할 성공 - CLOSED: 닫힘 */
  @SerializedName("result")
  private String result;

  /**
   * 분할 완료 시간 설명: 분할 완료 시간, RFC3339 표준 형식을 따르며, 형식은 yyyy-MM-DDTHH:mm:ss.sss+TIMEZONE이며, yyyy-MM-DD는 년월일을 나타내고, T는 문자열에 나타나며 time 요소의 시작을 나타내고, HH:mm:ss.sss는 시분초 밀리초를 나타내며, TIMEZONE은 시간대를 나타냅니다(+08:00는 동부 8구 시간, UTC보다 8시간 앞서며, 즉 베이징 시간). 예: 2015-05-20T13:29:35:120+08:00는 베이징 시간 2015년 05월 20일 13시 29분 35초를 나타냅니다.
   */
  @SerializedName("finish_time")
  private String finishTime;

  /**
   * 분할 실패 사유 설명: 분할 실패 사유. 다음 열거형 값을 포함: 1. ACCOUNT_ABNORMAL: 분할 수취 계정 이상 2. NO_RELATION: 분할 관계 해제됨 3. RECEIVER_HIGH_RISK: 고위험 수취인 4. RECEIVER_REAL_NAME_NOT_VERIFIED: 수취인 미실명 5. NO_AUTH: 분할 권한 해제됨 6. RECEIVER_RECEIPT_LIMIT: 사용자 월 수취 한도 초과 7. PAYER_ACCOUNT_ABNORMAL: 분할 측 계정 이상 8. INVALID_REQUEST: 설명 매개변수 설정 실패
   */
  @SerializedName("fail_reason")
  private String failReason;

  /** 분할 상세 내역 번호 설명: 위챗 분할 상세 내역 번호, 각 분할 업무 실행의 상세 내역 번호, 자금 청구서와 대조에 사용 가능 */
  @SerializedName("detail_id")
  private String detailId;

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public String getFinishTime() {
    return finishTime;
  }

  public void setFinishTime(String finishTime) {
    this.finishTime = finishTime;
  }

  public String getFailReason() {
    return failReason;
  }

  public void setFailReason(String failReason) {
    this.failReason = failReason;
  }

  public String getDetailId() {
    return detailId;
  }

  public void setDetailId(String detailId) {
    this.detailId = detailId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiverResultEntity {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    finishTime: ").append(toIndentedString(finishTime)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("    detailId: ").append(toIndentedString(detailId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
