// Copyright 2021 Tencent Inc. All rights reserved.

// API version: 1.2.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payments.model;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.util.GsonUtil;
import java.util.List;

/** PromotionDetail */
public class PromotionDetail {
  /** 쿠폰 ID 설명: 쿠폰 ID */
  @SerializedName("coupon_id")
  private String couponId;

  /** 혜택 이름 설명: 혜택 이름 */
  @SerializedName("name")
  private String name;

  /** GLOBAL: 전체 상품권; SINGLE: 단품 혜택 */
  public enum ScopeEnum {
    @SerializedName("GLOBAL")
    GLOBAL,

    @SerializedName("SINGLE")
    SINGLE
  }

  @SerializedName("scope")
  private ScopeEnum scope;

  /** CASH: 충전; NOCASH: 사전 충전 */
  public enum TypeEnum {
    @SerializedName("CASH")
    CASH,

    @SerializedName("NOCASH")
    NOCASH
  }

  @SerializedName("type")
  private TypeEnum type;

  /** 쿠폰 액면가 설명: 쿠폰 액면가 */
  @SerializedName("amount")
  private Integer amount;

  /** 활동 ID 설명: 활동 ID, 배치 ID */
  @SerializedName("stock_id")
  private String stockId;

  /** 위챗페이 출자 설명: 단위는 분 */
  @SerializedName("wechatpay_contribute")
  private Integer wechatpayContribute;

  /** 가맹점 출자 설명: 단위는 분 */
  @SerializedName("merchant_contribute")
  private Integer merchantContribute;

  /** 기타 출자 설명: 단위는 분 */
  @SerializedName("other_contribute")
  private Integer otherContribute;

  /** 혜택 통화 설명: CNY: 위안화, 국내 가맹점 번호는 위안화만 지원 */
  @SerializedName("currency")
  private String currency;

  /** 단품 목록 */
  @SerializedName("goods_detail")
  private List<PromotionGoodsDetail> goodsDetail;

  public String getCouponId() {
    return couponId;
  }

  public void setCouponId(String couponId) {
    this.couponId = couponId;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ScopeEnum getScope() {
    return scope;
  }

  public void setScope(ScopeEnum scope) {
    this.scope = scope;
  }

  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public Integer getWechatpayContribute() {
    return wechatpayContribute;
  }

  public void setWechatpayContribute(Integer wechatpayContribute) {
    this.wechatpayContribute = wechatpayContribute;
  }

  public Integer getMerchantContribute() {
    return merchantContribute;
  }

  public void setMerchantContribute(Integer merchantContribute) {
    this.merchantContribute = merchantContribute;
  }

  public Integer getOtherContribute() {
    return otherContribute;
  }

  public void setOtherContribute(Integer otherContribute) {
    this.otherContribute = otherContribute;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public List<PromotionGoodsDetail> getGoodsDetail() {
    return goodsDetail;
  }

  public void setGoodsDetail(List<PromotionGoodsDetail> goodsDetail) {
    this.goodsDetail = goodsDetail;
  }

  @Override
  public String toString() {
    return GsonUtil.getGson().toJson(this);
  }
}
