// Copyright 2021 Tencent Inc. All rights reserved.
//
// 청단 파일 다운로드 주소 조회 대외 API
//
// 가맹점이 빠르게 조회하고 계정 정보를 확인할 수 있도록, 이 인터페이스를 통해 오프라인 청단의 다운로드 주소를 조회할 수 있음.
//
// API version: 2.1.4

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.billdownload.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.cipher.Encryption;
import java.util.function.UnaryOperator;

/** EncryptBillEntity */
public class EncryptBillEntity {
  /** 청단 파일 순서 번호 설명: 청단 파일 순서 번호, 가맹점이 여러 파일을 청단 파일 순서 번호 순서로 병합하여 완전한 자금 청단 파일로 만듦, 시작 값은 1 */
  @SerializedName("bill_sequence")
  private Long billSequence;

  /** 해시 유형 설명: 해시 유형 */
  @SerializedName("hash_type")
  private HashType hashType;

  /** 해시 값 설명: 원본 청단(gzip은 압축 해제 필요)의 요약 값, 파일 무결성 검증에 사용. GCM 알고리즘으로 암호화된 청단 복호화 성공은 무결성 검증 통과를 의미함. */
  @SerializedName("hash_value")
  private String hashValue;

  /** 다운로드 주소 설명: 다음 단계 청단 파일 요청을 위한 다운로드 주소, 이 주소는 5분 내 유효 */
  @SerializedName("download_url")
  private String downloadUrl;

  /** 암호화 키 설명: 암호화 청단 파일에 사용하는 암호화 키. 키는 가맹점 인증서의 공개 키로 암호화한 후 Base64 인코딩 */
  @Encryption
  @SerializedName("encrypt_key")
  private String encryptKey;

  /** 랜덤 문자열 설명: 암호화 청단 파일에 사용하는 랜덤 문자열 */
  @SerializedName("nonce")
  private String nonce;

  public Long getBillSequence() {
    return billSequence;
  }

  public void setBillSequence(Long billSequence) {
    this.billSequence = billSequence;
  }

  public HashType getHashType() {
    return hashType;
  }

  public void setHashType(HashType hashType) {
    this.hashType = hashType;
  }

  public String getHashValue() {
    return hashValue;
  }

  public void setHashValue(String hashValue) {
    this.hashValue = hashValue;
  }

  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  public String getEncryptKey() {
    return encryptKey;
  }

  public void setEncryptKey(String encryptKey) {
    this.encryptKey = encryptKey;
  }

  public String getNonce() {
    return nonce;
  }

  public void setNonce(String nonce) {
    this.nonce = nonce;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EncryptBillEntity {\n");
    sb.append("    billSequence: ").append(toIndentedString(billSequence)).append("\n");
    sb.append("    hashType: ").append(toIndentedString(hashType)).append("\n");
    sb.append("    hashValue: ").append(toIndentedString(hashValue)).append("\n");
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    encryptKey: ").append(toIndentedString(encryptKey)).append("\n");
    sb.append("    nonce: ").append(toIndentedString(nonce)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  public EncryptBillEntity cloneWithCipher(UnaryOperator<String> s) {
    EncryptBillEntity copy = new EncryptBillEntity();
    copy.billSequence = billSequence;
    copy.hashType = hashType;
    copy.hashValue = hashValue;
    copy.downloadUrl = downloadUrl;
    if (encryptKey != null && !encryptKey.isEmpty()) {
      copy.encryptKey = s.apply(encryptKey);
    }
    copy.nonce = nonce;
    return copy;
  }
}
