// Copyright 2021 Tencent Inc. All rights reserved.
//
// 청단 파일 다운로드 주소 조회 대외 API
//
// 가맹점이 빠르게 조회하고 계정 정보를 확인할 수 있도록, 이 인터페이스를 통해 오프라인 청단의 다운로드 주소를 조회할 수 있음.
//
// API version: 2.1.4

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.billdownload.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** GetTradeBillRequest */
public class GetTradeBillRequest {
  /** 청단 날짜 설명: 청단 날짜, 형식 yyyy-MM-DD, 3개월 이내의 청단 다운로드 신청만 지원 */
  @SerializedName("bill_date")
  @Expose(serialize = false)
  private String billDate;

  /** 하위 가맹점 번호 설명: 가맹점이 직접 연결 가맹점인 경우: * 이 필드는 입력할 필요 없음 가맹점이 서비스 제공자인 경우: * 미입력 시 기본적으로 서비스 제공자 하위의 거래 또는 환불 데이터 반환 * 특정 하위 가맹점 하위의 거래 또는 환불 데이터를 다운로드하려면 이 필드는 필수 */
  @SerializedName("sub_mchid")
  @Expose(serialize = false)
  private String subMchid;

  /** 청단 유형 설명: 청단 유형, 미입력 시 기본값은 ALL */
  @SerializedName("bill_type")
  @Expose(serialize = false)
  private BillType billType;

  /** 압축 유형 설명: 압축 유형, 미입력 시 압축하지 않은 방식으로 데이터 스트림 반환 */
  @SerializedName("tar_type")
  @Expose(serialize = false)
  private TarType tarType;

  public String getBillDate() {
    return billDate;
  }

  public void setBillDate(String billDate) {
    this.billDate = billDate;
  }

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public BillType getBillType() {
    return billType;
  }

  public void setBillType(BillType billType) {
    this.billType = billType;
  }

  public TarType getTarType() {
    return tarType;
  }

  public void setTarType(TarType tarType) {
    this.tarType = tarType;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTradeBillRequest {\n");
    sb.append("    billDate: ").append(toIndentedString(billDate)).append("\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    billType: ").append(toIndentedString(billType)).append("\n");
    sb.append("    tarType: ").append(toIndentedString(tarType)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
