// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon;

import static com.wechat.pay.java.core.http.UrlEncoder.urlEncode;
import static com.wechat.pay.java.core.util.GsonUtil.toJson;
import static java.util.Objects.requireNonNull;

import com.wechat.pay.java.core.Config;
import com.wechat.pay.java.core.exception.HttpException;
import com.wechat.pay.java.core.exception.MalformedMessageException;
import com.wechat.pay.java.core.exception.ServiceException;
import com.wechat.pay.java.core.exception.ValidationException;
import com.wechat.pay.java.core.http.Constant;
import com.wechat.pay.java.core.http.DefaultHttpClientBuilder;
import com.wechat.pay.java.core.http.HostName;
import com.wechat.pay.java.core.http.HttpClient;
import com.wechat.pay.java.core.http.HttpHeaders;
import com.wechat.pay.java.core.http.HttpMethod;
import com.wechat.pay.java.core.http.HttpRequest;
import com.wechat.pay.java.core.http.HttpResponse;
import com.wechat.pay.java.core.http.JsonRequestBody;
import com.wechat.pay.java.core.http.MediaType;
import com.wechat.pay.java.core.http.QueryParameter;
import com.wechat.pay.java.core.http.RequestBody;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.AssociateTradeInfoRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.AssociateTradeInfoResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CouponCodeInfoRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CouponCodeInfoResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CouponCodeListResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CouponEntity;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CouponListResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CouponSendGovCardResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CreateBusiFavorStockRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.CreateBusiFavorStockResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.DeactivateCouponRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.DeactivateCouponResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.DeleteCouponCodeRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.DeleteCouponCodeResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.DisassociateTradeInfoRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.DisassociateTradeInfoResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.GetCouponNotifyRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.GetCouponNotifyResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.ListCouponsByFilterRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.ModifyBudgetRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.ModifyBudgetResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.ModifyStockInfoRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.PayReceiptInfoRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.PayReceiptListRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.QueryCouponCodeListRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.QueryCouponRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.QueryStockRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.ReturnCouponRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.ReturnCouponResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.ReturnReceiptInfoRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SendCouponRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SendCouponResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SendGovCardRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SetCouponNotifyRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SetCouponNotifyResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.StockGetResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SubsidyPayReceipt;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SubsidyPayReceiptListResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SubsidyPayRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SubsidyReturnReceipt;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.SubsidyReturnRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.UploadCouponCodeRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.UploadCouponCodeResponse;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.UseCouponRequest;
import com.wechat.pay.java.service.merchantexclusivecoupon.model.UseCouponResponse;

/** MerchantExclusiveCouponService 서비스 */
public class MerchantExclusiveCouponService {

  private final HttpClient httpClient;
  private final HostName hostName;

  private MerchantExclusiveCouponService(HttpClient httpClient, HostName hostName) {
    this.httpClient = requireNonNull(httpClient);
    this.hostName = hostName;
  }

  /** MerchantExclusiveCouponService 생성자 */
  public static class Builder {

    private HttpClient httpClient;
    private HostName hostName;

    public Builder config(Config config) {
      this.httpClient = new DefaultHttpClientBuilder().config(config).build();

      return this;
    }

    public Builder hostName(HostName hostName) {
      this.hostName = hostName;
      return this;
    }

    public Builder httpClient(HttpClient httpClient) {
      this.httpClient = httpClient;
      return this;
    }

    public MerchantExclusiveCouponService build() {
      return new MerchantExclusiveCouponService(httpClient, hostName);
    }
  }

  /**
   * 사전 저장 code 상세 조회
   *
   * @param request 요청 매개변수
   * @return CouponCodeInfoResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public CouponCodeInfoResponse couponCodeInfo(CouponCodeInfoRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks/{stock_id}/couponcodes/{coupon_code}";

    CouponCodeInfoRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "stock_id" + "}", urlEncode(realRequest.getStockId()));

    requestPath =
        requestPath.replace("{" + "coupon_code" + "}", urlEncode(realRequest.getCouponCode()));

    // query 매개변수 추가
    QueryParameter queryParameter = new QueryParameter();
    if (realRequest.getAppid() != null) {
      queryParameter.add("appid", urlEncode(realRequest.getAppid()));
    }
    requestPath += queryParameter.getQueryStr();
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<CouponCodeInfoResponse> httpResponse =
        httpClient.execute(httpRequest, CouponCodeInfoResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 생성
   *
   * @param request 요청 매개변수
   * @return CreateBusiFavorStockResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public CreateBusiFavorStockResponse createBusifavorStock(CreateBusiFavorStockRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks";
    CreateBusiFavorStockRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<CreateBusiFavorStockResponse> httpResponse =
        httpClient.execute(httpRequest, CreateBusiFavorStockResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 사전 저장 code 삭제
   *
   * @param request 요청 매개변수
   * @return DeleteCouponCodeResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public DeleteCouponCodeResponse deleteCouponCode(DeleteCouponCodeRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks/{stock_id}/couponcodes/{coupon_code}";

    DeleteCouponCodeRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "stock_id" + "}", urlEncode(realRequest.getStockId()));

    requestPath =
        requestPath.replace("{" + "coupon_code" + "}", urlEncode(realRequest.getCouponCode()));

    // query 매개변수 추가
    QueryParameter queryParameter = new QueryParameter();
    if (realRequest.getDeleteRequestNo() != null) {
      queryParameter.add("delete_request_no", urlEncode(realRequest.getDeleteRequestNo()));
    }
    requestPath += queryParameter.getQueryStr();
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.DELETE)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<DeleteCouponCodeResponse> httpResponse =
        httpClient.execute(httpRequest, DeleteCouponCodeResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 배치 예산 수정
   *
   * @param request 요청 매개변수
   * @return ModifyBudgetResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public ModifyBudgetResponse modifyBudget(ModifyBudgetRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks/{stock_id}/budget";

    ModifyBudgetRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "stock_id" + "}", urlEncode(realRequest.getStockId()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.PATCH)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<ModifyBudgetResponse> httpResponse =
        httpClient.execute(httpRequest, ModifyBudgetResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 기본 정보 수정
   *
   * @param request 요청 매개변수
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public void modifyStockInfo(ModifyStockInfoRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks/{stock_id}";

    ModifyStockInfoRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "stock_id" + "}", urlEncode(realRequest.getStockId()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.PATCH)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    httpClient.execute(httpRequest, null);
  }

  /**
   * 사전 저장 code 목록 조회
   *
   * @param request 요청 매개변수
   * @return CouponCodeListResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public CouponCodeListResponse queryCouponCodeList(QueryCouponCodeListRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks/{stock_id}/couponcodes";

    QueryCouponCodeListRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "stock_id" + "}", urlEncode(realRequest.getStockId()));

    // query 매개변수 추가
    QueryParameter queryParameter = new QueryParameter();
    if (realRequest.getLimit() != null) {
      queryParameter.add("limit", urlEncode(realRequest.getLimit().toString()));
    }
    if (realRequest.getOffset() != null) {
      queryParameter.add("offset", urlEncode(realRequest.getOffset().toString()));
    }
    if (realRequest.getAppid() != null) {
      queryParameter.add("appid", urlEncode(realRequest.getAppid()));
    }
    if (realRequest.getStatus() != null) {
      queryParameter.add("status", urlEncode(realRequest.getStatus().toString()));
    }
    requestPath += queryParameter.getQueryStr();
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<CouponCodeListResponse> httpResponse =
        httpClient.execute(httpRequest, CouponCodeListResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 배치 상세 조회
   *
   * @param request 요청 매개변수
   * @return StockGetResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public StockGetResponse queryStock(QueryStockRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks/{stock_id}";

    QueryStockRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "stock_id" + "}", urlEncode(realRequest.getStockId()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<StockGetResponse> httpResponse =
        httpClient.execute(httpRequest, StockGetResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 사전 저장 code 업로드
   *
   * @param request 요청 매개변수
   * @return UploadCouponCodeResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public UploadCouponCodeResponse uploadCouponCode(UploadCouponCodeRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/stocks/{stock_id}/couponcodes";

    UploadCouponCodeRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "stock_id" + "}", urlEncode(realRequest.getStockId()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<UploadCouponCodeResponse> httpResponse =
        httpClient.execute(httpRequest, UploadCouponCodeResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 이벤트 알림 주소 조회
   *
   * @param request 요청 매개변수
   * @return GetCouponNotifyResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public GetCouponNotifyResponse getCouponNotify(GetCouponNotifyRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/callbacks";

    GetCouponNotifyRequest realRequest = request;
    // query 매개변수 추가
    QueryParameter queryParameter = new QueryParameter();
    if (realRequest.getMchid() != null) {
      queryParameter.add("mchid", urlEncode(realRequest.getMchid()));
    }
    requestPath += queryParameter.getQueryStr();
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<GetCouponNotifyResponse> httpResponse =
        httpClient.execute(httpRequest, GetCouponNotifyResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 이벤트 알림 주소 설정
   *
   * @param request 요청 매개변수
   * @return SetCouponNotifyResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public SetCouponNotifyResponse setCouponNotify(SetCouponNotifyRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/callbacks";
    SetCouponNotifyRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<SetCouponNotifyResponse> httpResponse =
        httpClient.execute(httpRequest, SetCouponNotifyResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 주문 정보 연결
   *
   * @param request 요청 매개변수
   * @return AssociateTradeInfoResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public AssociateTradeInfoResponse associateTradeInfo(AssociateTradeInfoRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/coupons/associate";
    AssociateTradeInfoRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<AssociateTradeInfoResponse> httpResponse =
        httpClient.execute(httpRequest, AssociateTradeInfoResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 쿠폰 무효화
   *
   * @param request 요청 매개변수
   * @return DeactivateCouponResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public DeactivateCouponResponse deactivateCoupon(DeactivateCouponRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/coupons/deactivate";
    DeactivateCouponRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<DeactivateCouponResponse> httpResponse =
        httpClient.execute(httpRequest, DeactivateCouponResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 取消주문 정보 연결
   *
   * @param request 요청 매개변수
   * @return DisassociateTradeInfoResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public DisassociateTradeInfoResponse disassociateTradeInfo(DisassociateTradeInfoRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/coupons/disassociate";
    DisassociateTradeInfoRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<DisassociateTradeInfoResponse> httpResponse =
        httpClient.execute(httpRequest, DisassociateTradeInfoResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 필터 조건에 따라 사용자 쿠폰 조회
   *
   * @param request 요청 매개변수
   * @return CouponListResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public CouponListResponse listCouponsByFilter(ListCouponsByFilterRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/users/{openid}/coupons";

    ListCouponsByFilterRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "openid" + "}", urlEncode(realRequest.getOpenid()));

    // query 매개변수 추가
    QueryParameter queryParameter = new QueryParameter();
    if (realRequest.getAppid() != null) {
      queryParameter.add("appid", urlEncode(realRequest.getAppid()));
    }
    if (realRequest.getStockId() != null) {
      queryParameter.add("stock_id", urlEncode(realRequest.getStockId()));
    }
    if (realRequest.getCreatorMerchant() != null) {
      queryParameter.add("creator_merchant", urlEncode(realRequest.getCreatorMerchant()));
    }
    if (realRequest.getBelongMerchant() != null) {
      queryParameter.add("belong_merchant", urlEncode(realRequest.getBelongMerchant()));
    }
    if (realRequest.getSenderMerchant() != null) {
      queryParameter.add("sender_merchant", urlEncode(realRequest.getSenderMerchant()));
    }
    if (realRequest.getOffset() != null) {
      queryParameter.add("offset", urlEncode(realRequest.getOffset().toString()));
    }
    if (realRequest.getLimit() != null) {
      queryParameter.add("limit", urlEncode(realRequest.getLimit().toString()));
    }
    if (realRequest.getCouponState() != null) {
      queryParameter.add("coupon_state", urlEncode(realRequest.getCouponState().toString()));
    }
    requestPath += queryParameter.getQueryStr();
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<CouponListResponse> httpResponse =
        httpClient.execute(httpRequest, CouponListResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 사용자 쿠폰 상세 조회
   *
   * @param request 요청 매개변수
   * @return CouponEntity
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public CouponEntity queryCoupon(QueryCouponRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/users/{openid}/coupons/{coupon_code}/appids/{appid}";

    QueryCouponRequest realRequest = request;
    // path 매개변수 추가
    requestPath =
        requestPath.replace("{" + "coupon_code" + "}", urlEncode(realRequest.getCouponCode()));

    requestPath = requestPath.replace("{" + "appid" + "}", urlEncode(realRequest.getAppid()));

    requestPath = requestPath.replace("{" + "openid" + "}", urlEncode(realRequest.getOpenid()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<CouponEntity> httpResponse = httpClient.execute(httpRequest, CouponEntity.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 쿠폰 반환 신청
   *
   * @param request 요청 매개변수
   * @return ReturnCouponResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public ReturnCouponResponse returnCoupon(ReturnCouponRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/coupons/return";
    ReturnCouponRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<ReturnCouponResponse> httpResponse =
        httpClient.execute(httpRequest, ReturnCouponResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 사용자에게 쿠폰 발송
   *
   * @param request 요청 매개변수
   * @return SendCouponResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public SendCouponResponse sendCoupon(SendCouponRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/coupons/send";
    SendCouponRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<SendCouponResponse> httpResponse =
        httpClient.execute(httpRequest, SendCouponResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 정부 소비 카드 발급
   *
   * @param request 요청 매개변수
   * @return CouponSendGovCardResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public CouponSendGovCardResponse sendGovCard(SendGovCardRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/coupons/{card_id}/send";

    SendGovCardRequest realRequest = request;
    // path 매개변수 추가
    requestPath = requestPath.replace("{" + "card_id" + "}", urlEncode(realRequest.getCardId()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<CouponSendGovCardResponse> httpResponse =
        httpClient.execute(httpRequest, CouponSendGovCardResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 사용자 쿠폰 사용
   *
   * @param request 요청 매개변수
   * @return UseCouponResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public UseCouponResponse useCoupon(UseCouponRequest request) {
    String requestPath = "https://api.mch.weixin.qq.com/v3/marketing/busifavor/coupons/use";
    UseCouponRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<UseCouponResponse> httpResponse =
        httpClient.execute(httpRequest, UseCouponResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 마케팅 보조금 지급 내역 상세 조회
   *
   * @param request 요청 매개변수
   * @return SubsidyPayReceipt
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public SubsidyPayReceipt payReceiptInfo(PayReceiptInfoRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/subsidy/pay-receipts/{subsidy_receipt_id}";

    PayReceiptInfoRequest realRequest = request;
    // path 매개변수 추가
    requestPath =
        requestPath.replace(
            "{" + "subsidy_receipt_id" + "}", urlEncode(realRequest.getSubsidyReceiptId()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<SubsidyPayReceipt> httpResponse =
        httpClient.execute(httpRequest, SubsidyPayReceipt.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 마케팅 보조금 지급 내역 목록 조회
   *
   * @param request 요청 매개변수
   * @return SubsidyPayReceiptListResponse
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public SubsidyPayReceiptListResponse payReceiptList(PayReceiptListRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/subsidy/pay-receipts";

    PayReceiptListRequest realRequest = request;
    // query 매개변수 추가
    QueryParameter queryParameter = new QueryParameter();
    if (realRequest.getStockId() != null) {
      queryParameter.add("stock_id", urlEncode(realRequest.getStockId()));
    }
    if (realRequest.getCouponCode() != null) {
      queryParameter.add("coupon_code", urlEncode(realRequest.getCouponCode()));
    }
    if (realRequest.getOutSubsidyNo() != null) {
      queryParameter.add("out_subsidy_no", urlEncode(realRequest.getOutSubsidyNo()));
    }
    requestPath += queryParameter.getQueryStr();
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<SubsidyPayReceiptListResponse> httpResponse =
        httpClient.execute(httpRequest, SubsidyPayReceiptListResponse.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 마케팅 보조금 반환 내역 상세 조회
   *
   * @param request 요청 매개변수
   * @return SubsidyReturnReceipt
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public SubsidyReturnReceipt returnReceiptInfo(ReturnReceiptInfoRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/subsidy/return-receipts/{subsidy_return_receipt_id}";

    ReturnReceiptInfoRequest realRequest = request;
    // path 매개변수 추가
    requestPath =
        requestPath.replace(
            "{" + "subsidy_return_receipt_id" + "}",
            urlEncode(realRequest.getSubsidyReturnReceiptId()));

    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.GET)
            .url(requestPath)
            .headers(headers)
            .build();
    HttpResponse<SubsidyReturnReceipt> httpResponse =
        httpClient.execute(httpRequest, SubsidyReturnReceipt.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 마케팅 보조금 지급
   *
   * @param request 요청 매개변수
   * @return SubsidyPayReceipt
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public SubsidyPayReceipt subsidyPay(SubsidyPayRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/subsidy/pay-receipts";
    SubsidyPayRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<SubsidyPayReceipt> httpResponse =
        httpClient.execute(httpRequest, SubsidyPayReceipt.class);
    return httpResponse.getServiceResponse();
  }

  /**
   * 가맹점 쿠폰 마케팅 보조금 반환
   *
   * @param request 요청 매개변수
   * @return SubsidyReturnReceipt
   * @throws HttpException 发送HTTP请求失败。例如构建요청 매개변수失败、发送请求失败、I/O错误等。包含请求信息。
   * @throws ValidationException HTTP 요청 전송 성공, 위챗페이 반환 서명 검증 실패.
   * @throws ServiceException HTTP 요청 전송 성공, 서비스 반환 예외. 예: 반환 상태 코드가 200보다 작거나 300보다 크거나 같음.
   * @throws MalformedMessageException 서비스 반환 성공, content-type이 application/json이 아니거나 반환 본문 파싱 실패.
   */
  public SubsidyReturnReceipt subsidyReturn(SubsidyReturnRequest request) {
    String requestPath =
        "https://api.mch.weixin.qq.com/v3/marketing/busifavor/subsidy/return-receipts";
    SubsidyReturnRequest realRequest = request;
    if (this.hostName != null) {
      requestPath = requestPath.replaceFirst(HostName.API.getValue(), hostName.getValue());
    }
    HttpHeaders headers = new HttpHeaders();
    headers.addHeader(Constant.ACCEPT, MediaType.APPLICATION_JSON.getValue());
    headers.addHeader(Constant.CONTENT_TYPE, MediaType.APPLICATION_JSON.getValue());
    HttpRequest httpRequest =
        new HttpRequest.Builder()
            .httpMethod(HttpMethod.POST)
            .url(requestPath)
            .headers(headers)
            .body(createRequestBody(realRequest))
            .build();
    HttpResponse<SubsidyReturnReceipt> httpResponse =
        httpClient.execute(httpRequest, SubsidyReturnReceipt.class);
    return httpResponse.getServiceResponse();
  }

  private RequestBody createRequestBody(Object request) {
    return new JsonRequestBody.Builder().body(toJson(request)).build();
  }
}
