// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 스코어 주차 서비스
//
// 위챗페이 스코어 주차 서비스 결제 API
//
// API version: 1.2.1

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.wexinpayscoreparking.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CreateParkingRequest */
public class CreateParkingRequest {
  /** 서브 가맹점 번호 설명: 위챗페이가 할당한 서브 가맹점 번호, 서비스 제공자 모드에서 필수 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 가맹점 입장 id 설명: 가맹점 측 입장 식별 id, 동일한 가맹점 번호 하에서 고유 */
  @SerializedName("out_parking_no")
  private String outParkingNo;

  /** 차량 번호판 번호 설명: 차량 번호판 번호, 시/도 + 번호판만 포함, 특수 문자는 제외 */
  @SerializedName("plate_number")
  private String plateNumber;

  /** 차량 번호판 색상 설명: 차량 번호판 색상 */
  @SerializedName("plate_color")
  private PlateColor plateColor;

  /** 콜백 알림 url 설명: 입장 상태 변경 콜백 알림을 수신하는 url, 콜백 url은 https만 허용 */
  @SerializedName("notify_url")
  private String notifyUrl;

  /**
   * 입장 시간
   * 설명: 입장 시간, [rfc3339](https://datatracker.ietf.org/doc/html/rfc3339) 표준 형식을 따름, 형식은 yyyy-MM-DDTHH:mm:ss+TIMEZONE, yyyy-MM-DD는 년월일을 나타내고, T는 문자열에 나타나며 time 요소의 시작을 나타내고, HH:mm:ss는 시분초를 나타내고, TIMEZONE은 시간대를 나타냄 (+08:00은 동부 8구 시간대, UTC보다
   * 8시간 앞서며, 즉 베이징 시간). 예: 2015-05-20T13:29:35+08:00은 베이징 시간 2015년 5월 20일 13시 29분 35초를 나타냄.
   */
  @SerializedName("start_time")
  private String startTime;

  /** 주차장 이름 설명: 주차 공간이 있는 주차장의 이름 */
  @SerializedName("parking_name")
  private String parkingName;

  /** 무료 시간 설명: 주차장의 무료 주차 시간, 단위는 초 */
  @SerializedName("free_duration")
  private Integer freeDuration;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getOutParkingNo() {
    return outParkingNo;
  }

  public void setOutParkingNo(String outParkingNo) {
    this.outParkingNo = outParkingNo;
  }

  public String getPlateNumber() {
    return plateNumber;
  }

  public void setPlateNumber(String plateNumber) {
    this.plateNumber = plateNumber;
  }

  public PlateColor getPlateColor() {
    return plateColor;
  }

  public void setPlateColor(PlateColor plateColor) {
    this.plateColor = plateColor;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public String getParkingName() {
    return parkingName;
  }

  public void setParkingName(String parkingName) {
    this.parkingName = parkingName;
  }

  public Integer getFreeDuration() {
    return freeDuration;
  }

  public void setFreeDuration(Integer freeDuration) {
    this.freeDuration = freeDuration;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateParkingRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    outParkingNo: ").append(toIndentedString(outParkingNo)).append("\n");
    sb.append("    plateNumber: ").append(toIndentedString(plateNumber)).append("\n");
    sb.append("    plateColor: ").append(toIndentedString(plateColor)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    parkingName: ").append(toIndentedString(parkingName)).append("\n");
    sb.append("    freeDuration: ").append(toIndentedString(freeDuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
