// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 스코어 주차 서비스
//
// 위챗페이 스코어 주차 서비스 차감 API
//
// API version: 1.2.1

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.wexinpayscoreparking.model;

import com.google.gson.annotations.SerializedName;

/** PlateColor */
public enum PlateColor {
  @SerializedName("BLUE")
  BLUE,

  @SerializedName("GREEN")
  GREEN,

  @SerializedName("YELLOW")
  YELLOW,

  @SerializedName("BLACK")
  BLACK,

  @SerializedName("WHITE")
  WHITE,

  @SerializedName("LIMEGREEN")
  LIMEGREEN
}
