// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 스코어 주차 서비스
//
// 위챗페이 스코어 주차 서비스 결제 API
//
// API version: 1.2.1

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.wexinpayscoreparking.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** QueryOrderAmount */
public class QueryOrderAmount {
  /** 주문 금액 설명: 주문 총액, 단위는 분, 정수만 가능, 결제 금액 참조 */
  @SerializedName("total")
  private Long total;

  /** 통화 유형 설명: ISO 4217 표준 3자리 문자 코드, 현재는 위안화만 지원: CNY */
  @SerializedName("currency")
  private String currency;

  /** 사용자 실제 결제 금액 설명: 사용자 실제 결제 금액, 단위는 분, 정수만 가능, 결제 금액 참조 */
  @SerializedName("payer_total")
  private Long payerTotal;

  /** 할인 설명: 주문 할인 */
  @SerializedName("discount_total")
  private Long discountTotal;

  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Long getPayerTotal() {
    return payerTotal;
  }

  public void setPayerTotal(Long payerTotal) {
    this.payerTotal = payerTotal;
  }

  public Long getDiscountTotal() {
    return discountTotal;
  }

  public void setDiscountTotal(Long discountTotal) {
    this.discountTotal = discountTotal;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryOrderAmount {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    payerTotal: ").append(toIndentedString(payerTotal)).append("\n");
    sb.append("    discountTotal: ").append(toIndentedString(discountTotal)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
