// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 스코어 주차 서비스
//
// 위챗페이 스코어 주차 서비스 차감 API
//
// API version: 1.2.1

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.wexinpayscoreparking.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** QueryPlateServiceRequest */
public class QueryPlateServiceRequest {
  /** 공개 계정 ID 설명: appid는 가맹점이 위챗에서 공개 계정 또는 모바일 애플리케이션을 신청하여 성공한 후 할당받은 계정 ID이며, 로그인 플랫폼은 mp.weixin.qq.com 또는 open.weixin.qq.com */
  @SerializedName("appid")
  @Expose(serialize = false)
  private String appid;

  /** 하위 가맹점 번호 설명: 위챗페이가 할당한 하위 가맹점 번호, 서비스 제공자 모드에서 필수 전달 */
  @SerializedName("sub_mchid")
  @Expose(serialize = false)
  private String subMchid;

  /** 차량 번호판 설명: 차량 번호판, 지방+번호판만 포함하며, 특수 문자는 포함하지 않음. */
  @SerializedName("plate_number")
  @Expose(serialize = false)
  private String plateNumber;

  /** 사용자 식별자 설명: 가맹점에 해당하는 appid 하위의 사용자 고유 식별자 */
  @SerializedName("openid")
  @Expose(serialize = false)
  private String openid;

  /** 차량 번호판 색상 설명: 차량 번호판 색상 */
  @SerializedName("plate_color")
  @Expose(serialize = false)
  private PlateColor plateColor;

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getPlateNumber() {
    return plateNumber;
  }

  public void setPlateNumber(String plateNumber) {
    this.plateNumber = plateNumber;
  }

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public PlateColor getPlateColor() {
    return plateColor;
  }

  public void setPlateColor(PlateColor plateColor) {
    this.plateColor = plateColor;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryPlateServiceRequest {\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    plateNumber: ").append(toIndentedString(plateNumber)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    plateColor: ").append(toIndentedString(plateColor)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
