// Copyright 2021 Tencent Inc. All rights reserved.
//
// 판매자 계좌 이체 대외 API
//
// * 시나리오 및 비즈니스 프로세스: 가맹점은 이 제품을 통해 여러 사용자의 위챗페이 잔액으로 동시에 이체하는 작업을 수행할 수 있으며, 보너스 보조금 지급, 수수료 대금 정산, 직원 비용 처리 등의 시나리오에 사용할 수 있음.
// [https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0](https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0) * 접속 단계: * 가맹점은 위챗페이 가맹점 플랫폼에서 "일괄 이체" 제품 권한을 개통하고 "API 방식으로 이체 시작"을 선택함. * 일괄 이체 인터페이스를 호출하여 여러 사용자의 위챗페이 잔액으로 이체를 시작함. * 조회 배치 인터페이스를 호출하여 이체 배치 상세 정보 및 현재 상태를 얻을 수 있음. * 조회 상세 인터페이스를 호출하여 단일 이체 상세 정보 및 현재 상태를 얻을 수 있음.
//
// API version: 1.0.5

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.transferbatch.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** GetTransferBatchByOutNoRequest */
public class GetTransferBatchByOutNoRequest {
  /** 판매자 배치 단 번호 설명: 가맹점 시스템 내부의 판매자 배치 단 번호, 가맹점 시스템 내부에서 고유 */
  @SerializedName("out_batch_no")
  @Expose(serialize = false)
  private String outBatchNo;

  /**
   * 이체 상세 단 조회 여부 설명: true-예; false-아니오, 기본값은 아니오. 가맹점은 지정된 상태의 이체 상세 단을 조회할지 선택할 수 있으며, 이체 배치 단 상태가 "FINISHED" (완료됨)일 때만 조건을 만족하는 이체 상세 단을 반환함
   */
  @SerializedName("need_query_detail")
  @Expose(serialize = false)
  private Boolean needQueryDetail;

  /** 요청 리소스 시작 위치 설명: 이번 요청 리소스 (이체 상세 단)의 시작 위치, 0부터 시작, 기본값은 0 */
  @SerializedName("offset")
  @Expose(serialize = false)
  private Integer offset;

  /** 최대 리소스 건수 설명: 이번 요청에서 반환할 수 있는 최대 리소스 (이체 상세 단) 건수, 최소 20건, 최대 100건, 전달하지 않으면 기본값 20건. 20건 미만은 실제 건수로 반환 */
  @SerializedName("limit")
  @Expose(serialize = false)
  private Integer limit;

  /**
   * 상세 상태 설명: WAIT_PAY: 확인 대기. 가맹점 확인 대기, 무비밀번호 조건에 부합할 때, 시스템이 자동으로 이체 중으로 전환함 ALL: 전체. 이체 성공, 실패, 확인 대기 상태의 상세 단을 동시에 조회해야 함 SUCCESS: 이체 성공
   * FAIL: 이체 실패. 실패 사유를 확인한 후, 이 상세 단의 이체를 다시 시작할지 결정해야 함 (전체 이체 배치 단이 아님)
   */
  @SerializedName("detail_status")
  @Expose(serialize = false)
  private String detailStatus;

  public String getOutBatchNo() {
    return outBatchNo;
  }

  public void setOutBatchNo(String outBatchNo) {
    this.outBatchNo = outBatchNo;
  }

  public Boolean getNeedQueryDetail() {
    return needQueryDetail;
  }

  public void setNeedQueryDetail(Boolean needQueryDetail) {
    this.needQueryDetail = needQueryDetail;
  }

  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public String getDetailStatus() {
    return detailStatus;
  }

  public void setDetailStatus(String detailStatus) {
    this.detailStatus = detailStatus;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTransferBatchByOutNoRequest {\n");
    sb.append("    outBatchNo: ").append(toIndentedString(outBatchNo)).append("\n");
    sb.append("    needQueryDetail: ").append(toIndentedString(needQueryDetail)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    detailStatus: ").append(toIndentedString(detailStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
