// Copyright 2021 Tencent Inc. All rights reserved.
//
// 판매자 계좌 이체 대외 API
//
// * 시나리오 및 비즈니스 프로세스: 가맹점은 이 제품을 통해 여러 사용자의 위챗페이 잔액으로 동시에 이체하는 작업을 수행할 수 있으며, 보너스 보조금 지급, 수수료 대금 정산, 직원 비용 처리 등의 시나리오에 사용할 수 있음.
// [https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0](https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0) * 접속 단계: * 가맹점은 위챗페이 가맹점 플랫폼에서 "일괄 이체" 제품 권한을 개통하고 "API 방식으로 이체 시작"을 선택함. * 일괄 이체 인터페이스를 호출하여 여러 사용자의 위챗페이 잔액으로 이체를 시작함. * 조회 배치 인터페이스를 호출하여 이체 배치 상세 정보 및 현재 상태를 얻을 수 있음. * 조회 상세 인터페이스를 호출하여 단일 이체 상세 정보 및 현재 상태를 얻을 수 있음.
//
// API version: 1.0.5

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.transferbatch.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.cipher.Encryption;
import java.util.ArrayList;
import java.util.List;
import java.util.function.UnaryOperator;

/** InitiateBatchTransferRequest */
public class InitiateBatchTransferRequest {
  /** 가맹점 appid 설명: 가맹점 번호를 신청한 appid 또는 가맹점 번호에 바인딩된 appid (기업 번호 corpid가 이 appid임) */
  @SerializedName("appid")
  private String appid;

  /** 판매자 배치 단 번호 설명: 가맹점 시스템 내부의 판매자 배치 단 번호, 이 매개변수는 숫자와 대소문자로만 구성되어야 하며, 가맹점 시스템 내부에서 고유해야 함 */
  @SerializedName("out_batch_no")
  private String outBatchNo;

  /** 배치 이름 설명: 이 일괄 이체의 이름 */
  @SerializedName("batch_name")
  private String batchName;

  /** 배치 비고 설명: 이체 설명, UTF8 인코딩, 최대 32자 허용 */
  @SerializedName("batch_remark")
  private String batchRemark;

  /** 이체 총액 설명: 이체 금액 단위는 "분". 이체 총액은 배치 내 모든 상세 이체 금액의 합과 일치해야 하며, 그렇지 않으면 이체 작업을 시작할 수 없음 */
  @SerializedName("total_amount")
  private Long totalAmount;

  /** 이체 총 건수 설명: 하나의 이체 배치 단은 최대 천 건의 이체를 시작할 수 있음. 이체 총 건수는 배치 내 모든 상세의 합과 일치해야 하며, 그렇지 않으면 이체 작업을 시작할 수 없음 */
  @SerializedName("total_num")
  private Integer totalNum;

  /** 이체 상세 목록 설명: 일괄 이체를 시작하는 상세 목록, 최대 천 건 */
  @Encryption
  @SerializedName("transfer_detail_list")
  private List<TransferDetailInput> transferDetailList = new ArrayList<TransferDetailInput>();

  /** 이체 시나리오 ID 설명: 이 배치 이체에 사용되는 이체 시나리오, 작성하지 않으면 판매자의 기본 시나리오를 사용하며, 기본 시나리오가 없으면 비워둘 수 있으며, "판매자 이체-기능으로 이동"에서 신청할 수 있음. 예: 1001-현금 마케팅 */
  @SerializedName("transfer_scene_id")
  private String transferSceneId;

  /** 알림 주소 설명: 위챗페이 결제 결과 알림을 비동기로 수신하는 콜백 주소, 알림 url은 공개 네트워크에서 접근 가능한 url이어야 하며, https여야 하며, 매개변수를 포함할 수 없음. */
  @SerializedName("notify_url")
  private String notifyUrl;

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getOutBatchNo() {
    return outBatchNo;
  }

  public void setOutBatchNo(String outBatchNo) {
    this.outBatchNo = outBatchNo;
  }

  public String getBatchName() {
    return batchName;
  }

  public void setBatchName(String batchName) {
    this.batchName = batchName;
  }

  public String getBatchRemark() {
    return batchRemark;
  }

  public void setBatchRemark(String batchRemark) {
    this.batchRemark = batchRemark;
  }

  public Long getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Long totalAmount) {
    this.totalAmount = totalAmount;
  }

  public Integer getTotalNum() {
    return totalNum;
  }

  public void setTotalNum(Integer totalNum) {
    this.totalNum = totalNum;
  }

  public List<TransferDetailInput> getTransferDetailList() {
    return transferDetailList;
  }

  public void setTransferDetailList(List<TransferDetailInput> transferDetailList) {
    this.transferDetailList = transferDetailList;
  }

  public String getTransferSceneId() {
    return transferSceneId;
  }

  public void setTransferSceneId(String transferSceneId) {
    this.transferSceneId = transferSceneId;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateBatchTransferRequest {\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    outBatchNo: ").append(toIndentedString(outBatchNo)).append("\n");
    sb.append("    batchName: ").append(toIndentedString(batchName)).append("\n");
    sb.append("    batchRemark: ").append(toIndentedString(batchRemark)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    totalNum: ").append(toIndentedString(totalNum)).append("\n");
    sb.append("    transferDetailList: ").append(toIndentedString(transferDetailList)).append("\n");
    sb.append("    transferSceneId: ").append(toIndentedString(transferSceneId)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  public InitiateBatchTransferRequest cloneWithCipher(UnaryOperator<String> s) {
    InitiateBatchTransferRequest copy = new InitiateBatchTransferRequest();
    copy.appid = appid;
    copy.outBatchNo = outBatchNo;
    copy.batchName = batchName;
    copy.batchRemark = batchRemark;
    copy.totalAmount = totalAmount;
    copy.totalNum = totalNum;
    if (transferDetailList != null && transferDetailList.size() != 0) {
      // arr
      copy.transferDetailList = new ArrayList<>();
      for (TransferDetailInput val : transferDetailList) {
        if (val != null) {
          copy.transferDetailList.add(val.cloneWithCipher(s));
        }
      }
    }
    copy.transferSceneId = transferSceneId;
    copy.notifyUrl = notifyUrl;
    return copy;
  }
}
