// Copyright 2021 Tencent Inc. All rights reserved.
//
// 판매자 계좌 이체 대외 API
//
// * 시나리오 및 비즈니스 프로세스: 가맹점은 이 제품을 통해 여러 사용자의 위챗페이 잔액으로 동시에 이체하는 작업을 수행할 수 있으며, 보너스 보조금 지급, 수수료 대금 정산, 직원 비용 처리 등의 시나리오에 사용할 수 있음.
// [https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0](https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0) * 접속 단계: * 가맹점은 위챗페이 가맹점 플랫폼에서 "일괄 이체" 제품 권한을 개통하고 "API 방식으로 이체 시작"을 선택함. * 일괄 이체 인터페이스를 호출하여 여러 사용자의 위챗페이 잔액으로 이체를 시작함. * 조회 배치 인터페이스를 호출하여 이체 배치 상세 정보 및 현재 상태를 얻을 수 있음. * 조회 상세 인터페이스를 호출하여 단일 이체 상세 정보 및 현재 상태를 얻을 수 있음.
//
// API version: 1.0.5

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.transferbatch.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** TransferBatchGet */
public class TransferBatchGet {
  /** 가맹점 번호 설명: 위챗페이가 할당한 가맹점 번호 */
  @SerializedName("mchid")
  private String mchid;

  /** 판매자 배치 단 번호 설명: 가맹점 시스템 내부의 판매자 배치 단 번호, 가맹점 시스템 내부에서 고유 */
  @SerializedName("out_batch_no")
  private String outBatchNo;

  /** 위챗페이 배치 단 번호 설명: 위챗페이 배치 단 번호, 위챗페이 판매자 이체 시스템이 반환한 고유 식별자 */
  @SerializedName("batch_id")
  private String batchId;

  /** 가맹점 appid 설명: 가맹점 번호를 신청한 appid 또는 가맹점 번호에 바인딩된 appid (기업 번호 corpid가 이 appid임) */
  @SerializedName("appid")
  private String appid;

  /**
   * 배치 상태 설명: WAIT_PAY: 결제 확인 대기. 결제 출자 가맹점이 판매자 어시스턴트 미니 프로그램 또는 서비스 제공자 어시스턴트 미니 프로그램에서 결제 확인을 수행해야 함
   * ACCEPTED: 접수됨. 배치가 성공적으로 접수되었으며, 일괄 이체를 시작한 지 30분 후에도 이체 배치 단이 여전히 이 상태에 있으면, 가맹점 계좌 잔액 부족 등의 원인일 수 있음. 가맹점은 계좌 자금 거래 내역을 조회할 수 있으며, 이 이체 배치 단의 차감이 이미 발생했다면 배치가 이미 이체 중으로 진입한 것이므로 다시 조회하여 확인해야 함
   * PROCESSING: 이체 중. 배치 내 이체 상세 단 처리를 시작함 FINISHED: 완료됨. 배치 내 모든 이체 상세 단이 처리 완료됨 CLOSED: 닫힘. 구체적인 배치 닫힘 사유를 조회하여 확인할 수 있음
   */
  @SerializedName("batch_status")
  private String batchStatus;

  /** 배치 유형 설명: API: API 방식으로 시작 WEB: 페이지 방식으로 시작 */
  @SerializedName("batch_type")
  private String batchType;

  /** 배치 이름 설명: 이 일괄 이체의 이름 */
  @SerializedName("batch_name")
  private String batchName;

  /** 배치 비고 설명: 이체 설명, UTF8 인코딩, 최대 32자 허용 */
  @SerializedName("batch_remark")
  private String batchRemark;

  /** 배치 닫힘 사유 설명: 배치 단 상태가 "CLOSED" (닫힘)인 경우, 닫힘 사유가 있음 */
  @SerializedName("close_reason")
  private CloseReasonType closeReason;

  /** 이체 총액 설명: 이체 금액 단위는 "분" */
  @SerializedName("total_amount")
  private Long totalAmount;

  /** 이체 총 건수 설명: 하나의 이체 배치 단은 최대 삼천 건의 이체를 시작할 수 있음 */
  @SerializedName("total_num")
  private Integer totalNum;

  /** 배치 생성 시간 설명: 배치 접수 성공 시 반환, rfc3339에서 정의한 형식 사용, 형식은 YYYY-MM-DDThh:mm:ss+TIMEZONE */
  @SerializedName("create_time")
  private String createTime;

  /** 배치 업데이트 시간 설명: 배치의 가장 최근 상태 변경 시간, rfc3339에서 정의한 형식 사용, 형식은 YYYY-MM-DDThh:mm:ss+TIMEZONE */
  @SerializedName("update_time")
  private String updateTime;

  /** 이체 성공 금액 설명: 이체 성공 금액, 단위는 "분". 배치 상태가 "PROCESSING" (이체 중)일 때, 이체 성공 금액은 언제든지 변경될 수 있음 */
  @SerializedName("success_amount")
  private Long successAmount;

  /** 이체 성공 건수 설명: 이체 성공 건수. 배치 상태가 "PROCESSING" (이체 중)일 때, 이체 성공 건수는 언제든지 변경될 수 있음 */
  @SerializedName("success_num")
  private Integer successNum;

  /** 이체 실패 금액 설명: 이체 실패 금액, 단위는 "분" */
  @SerializedName("fail_amount")
  private Long failAmount;

  /** 이체 실패 건수 설명: 이체 실패 건수 */
  @SerializedName("fail_num")
  private Integer failNum;

  /** 이체 시나리오 ID 설명: 지정된 이체 시나리오 ID */
  @SerializedName("transfer_scene_id")
  private String transferSceneId;

  public String getMchid() {
    return mchid;
  }

  public void setMchid(String mchid) {
    this.mchid = mchid;
  }

  public String getOutBatchNo() {
    return outBatchNo;
  }

  public void setOutBatchNo(String outBatchNo) {
    this.outBatchNo = outBatchNo;
  }

  public String getBatchId() {
    return batchId;
  }

  public void setBatchId(String batchId) {
    this.batchId = batchId;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getBatchStatus() {
    return batchStatus;
  }

  public void setBatchStatus(String batchStatus) {
    this.batchStatus = batchStatus;
  }

  public String getBatchType() {
    return batchType;
  }

  public void setBatchType(String batchType) {
    this.batchType = batchType;
  }

  public String getBatchName() {
    return batchName;
  }

  public void setBatchName(String batchName) {
    this.batchName = batchName;
  }

  public String getBatchRemark() {
    return batchRemark;
  }

  public void setBatchRemark(String batchRemark) {
    this.batchRemark = batchRemark;
  }

  public CloseReasonType getCloseReason() {
    return closeReason;
  }

  public void setCloseReason(CloseReasonType closeReason) {
    this.closeReason = closeReason;
  }

  public Long getTotalAmount() {
    return totalAmount;
  }

  public void setTotalAmount(Long totalAmount) {
    this.totalAmount = totalAmount;
  }

  public Integer getTotalNum() {
    return totalNum;
  }

  public void setTotalNum(Integer totalNum) {
    this.totalNum = totalNum;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }

  public Long getSuccessAmount() {
    return successAmount;
  }

  public void setSuccessAmount(Long successAmount) {
    this.successAmount = successAmount;
  }

  public Integer getSuccessNum() {
    return successNum;
  }

  public void setSuccessNum(Integer successNum) {
    this.successNum = successNum;
  }

  public Long getFailAmount() {
    return failAmount;
  }

  public void setFailAmount(Long failAmount) {
    this.failAmount = failAmount;
  }

  public Integer getFailNum() {
    return failNum;
  }

  public void setFailNum(Integer failNum) {
    this.failNum = failNum;
  }

  public String getTransferSceneId() {
    return transferSceneId;
  }

  public void setTransferSceneId(String transferSceneId) {
    this.transferSceneId = transferSceneId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferBatchGet {\n");
    sb.append("    mchid: ").append(toIndentedString(mchid)).append("\n");
    sb.append("    outBatchNo: ").append(toIndentedString(outBatchNo)).append("\n");
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    batchStatus: ").append(toIndentedString(batchStatus)).append("\n");
    sb.append("    batchType: ").append(toIndentedString(batchType)).append("\n");
    sb.append("    batchName: ").append(toIndentedString(batchName)).append("\n");
    sb.append("    batchRemark: ").append(toIndentedString(batchRemark)).append("\n");
    sb.append("    closeReason: ").append(toIndentedString(closeReason)).append("\n");
    sb.append("    totalAmount: ").append(toIndentedString(totalAmount)).append("\n");
    sb.append("    totalNum: ").append(toIndentedString(totalNum)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    successAmount: ").append(toIndentedString(successAmount)).append("\n");
    sb.append("    successNum: ").append(toIndentedString(successNum)).append("\n");
    sb.append("    failAmount: ").append(toIndentedString(failAmount)).append("\n");
    sb.append("    failNum: ").append(toIndentedString(failNum)).append("\n");
    sb.append("    transferSceneId: ").append(toIndentedString(transferSceneId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
