// Copyright 2021 Tencent Inc. All rights reserved.
//
// 판매자 계좌 이체 대외 API
//
// * 시나리오 및 비즈니스 프로세스: 가맹점은 이 제품을 통해 여러 사용자의 위챗페이 잔액으로 동시에 이체하는 작업을 수행할 수 있으며, 보너스 보조금 지급, 수수료 대금 정산, 직원 비용 처리 등의 시나리오에 사용할 수 있음.
// [https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0](https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0) * 접속 단계: * 가맹점은 위챗페이 가맹점 플랫폼에서 "일괄 이체" 제품 권한을 개통하고 "API 방식으로 이체 시작"을 선택함. * 일괄 이체 인터페이스를 호출하여 여러 사용자의 위챗페이 잔액으로 이체를 시작함. * 조회 배치 인터페이스를 호출하여 이체 배치 상세 정보 및 현재 상태를 얻을 수 있음. * 조회 상세 인터페이스를 호출하여 단일 이체 상세 정보 및 현재 상태를 얻을 수 있음.
//
// API version: 1.0.5

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.transferbatch.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.cipher.Encryption;
import java.util.function.UnaryOperator;

/** TransferDetailEntity */
public class TransferDetailEntity {
  /** 가맹점 번호 설명: 위챗페이가 할당한 가맹점 번호 */
  @SerializedName("mchid")
  private String mchid;

  /** 판매자 배치 단 번호 설명: 가맹점 시스템 내부의 판매자 배치 단 번호, 가맹점 시스템 내부에서 고유 */
  @SerializedName("out_batch_no")
  private String outBatchNo;

  /** 위챗페이 배치 단 번호 설명: 위챗페이 배치 단 번호, 위챗페이 판매자 이체 시스템이 반환한 고유 식별자 */
  @SerializedName("batch_id")
  private String batchId;

  /** 가맹점 appid 설명: 가맹점 번호를 신청한 appid 또는 가맹점 번호에 바인딩된 appid (기업 번호 corpid가 이 appid임) */
  @SerializedName("appid")
  private String appid;

  /** 판매자 상세 단 번호 설명: 가맹점 시스템 내부에서 이체 배치 단 하위의 서로 다른 이체 상세 단을 구분하는 고유 식별자 */
  @SerializedName("out_detail_no")
  private String outDetailNo;

  /** 위챗페이 상세 단 번호 설명: 위챗페이 시스템 내부에서 이체 배치 단 하위의 서로 다른 이체 상세 단을 구분하는 고유 식별자 */
  @SerializedName("detail_id")
  private String detailId;

  /**
   * 상세 상태 설명: INIT: 초기 상태. 시스템 이체 검증 중 WAIT_PAY: 확인 대기. 가맹점 확인 대기, 무비밀번호 조건에 부합할 때, 시스템이 자동으로 이체 중으로 전환함
   * PROCESSING: 이체 중. 처리 중이며, 이체 결과가 아직 명확하지 않음 SUCCESS: 이체 성공 FAIL: 이체 실패. 실패 사유를 확인한 후, 이 상세 단의 이체를 다시 시작할지 결정해야 함 (전체 이체 배치 단이 아님)
   */
  @SerializedName("detail_status")
  private String detailStatus;

  /** 이체 금액 설명: 이체 금액 단위는 "분" */
  @SerializedName("transfer_amount")
  private Long transferAmount;

  /** 이체 비고 설명: 단일 이체 비고 (위챗페이 사용자가 이 비고를 받음), UTF8 인코딩, 최대 32자 허용 */
  @SerializedName("transfer_remark")
  private String transferRemark;

  /** 상세 실패 사유 설명: 이체가 실패한 경우 실패 사유가 있음 */
  @SerializedName("fail_reason")
  private FailReasonType failReason;

  /** 수취 사용자 openid 설명: 가맹점 appid 하위의 특정 사용자의 openid */
  @SerializedName("openid")
  private String openid;

  /** 수취 사용자 이름 설명: 수취 방 이름. 표준 RSA 알고리즘을 사용하며, 공개 키는 위챗페이 측에서 제공 가맹점이 이체할 때 수취 사용자 이름을 전달했으면, 조회 시 수취 사용자 이름을 반환함 */
  @Encryption
  @SerializedName("user_name")
  private String userName;

  /** 이체 시작 시간 설명: 이체를 시작한 시간, rfc3339에서 정의한 형식 사용, 형식은 YYYY-MM-DDThh:mm:ss+TIMEZONE */
  @SerializedName("initiate_time")
  private String initiateTime;

  /** 상세 업데이트 시간 설명: 상세의 마지막 상태 변경 시간, rfc3339에서 정의한 형식 사용, 형식은 YYYY-MM-DDThh:mm:ss+TIMEZONE */
  @SerializedName("update_time")
  private String updateTime;

  public String getMchid() {
    return mchid;
  }

  public void setMchid(String mchid) {
    this.mchid = mchid;
  }

  public String getOutBatchNo() {
    return outBatchNo;
  }

  public void setOutBatchNo(String outBatchNo) {
    this.outBatchNo = outBatchNo;
  }

  public String getBatchId() {
    return batchId;
  }

  public void setBatchId(String batchId) {
    this.batchId = batchId;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getOutDetailNo() {
    return outDetailNo;
  }

  public void setOutDetailNo(String outDetailNo) {
    this.outDetailNo = outDetailNo;
  }

  public String getDetailId() {
    return detailId;
  }

  public void setDetailId(String detailId) {
    this.detailId = detailId;
  }

  public String getDetailStatus() {
    return detailStatus;
  }

  public void setDetailStatus(String detailStatus) {
    this.detailStatus = detailStatus;
  }

  public Long getTransferAmount() {
    return transferAmount;
  }

  public void setTransferAmount(Long transferAmount) {
    this.transferAmount = transferAmount;
  }

  public String getTransferRemark() {
    return transferRemark;
  }

  public void setTransferRemark(String transferRemark) {
    this.transferRemark = transferRemark;
  }

  public FailReasonType getFailReason() {
    return failReason;
  }

  public void setFailReason(FailReasonType failReason) {
    this.failReason = failReason;
  }

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public String getInitiateTime() {
    return initiateTime;
  }

  public void setInitiateTime(String initiateTime) {
    this.initiateTime = initiateTime;
  }

  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferDetailEntity {\n");
    sb.append("    mchid: ").append(toIndentedString(mchid)).append("\n");
    sb.append("    outBatchNo: ").append(toIndentedString(outBatchNo)).append("\n");
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    outDetailNo: ").append(toIndentedString(outDetailNo)).append("\n");
    sb.append("    detailId: ").append(toIndentedString(detailId)).append("\n");
    sb.append("    detailStatus: ").append(toIndentedString(detailStatus)).append("\n");
    sb.append("    transferAmount: ").append(toIndentedString(transferAmount)).append("\n");
    sb.append("    transferRemark: ").append(toIndentedString(transferRemark)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    initiateTime: ").append(toIndentedString(initiateTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  public TransferDetailEntity cloneWithCipher(UnaryOperator<String> s) {
    TransferDetailEntity copy = new TransferDetailEntity();
    copy.mchid = mchid;
    copy.outBatchNo = outBatchNo;
    copy.batchId = batchId;
    copy.appid = appid;
    copy.outDetailNo = outDetailNo;
    copy.detailId = detailId;
    copy.detailStatus = detailStatus;
    copy.transferAmount = transferAmount;
    copy.transferRemark = transferRemark;
    copy.failReason = failReason;
    copy.openid = openid;
    if (userName != null && !userName.isEmpty()) {
      copy.userName = s.apply(userName);
    }
    copy.initiateTime = initiateTime;
    copy.updateTime = updateTime;
    return copy;
  }
}
