// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** ActApplyInfo */
public class ActApplyInfo {
  /** 매장 정보 설명: 매장 정보 */
  @SerializedName("store_info")
  private StoreInfo storeInfo;

  /** 상품 원가 설명: 브랜드 추가 구매 활동 상품의 원가, 이 가격은 추가 구매 미니 프로그램 플러그인에 표시됨 (단위: 분) */
  @SerializedName("goods_original_price")
  private Long goodsOriginalPrice;

  public StoreInfo getStoreInfo() {
    return storeInfo;
  }

  public void setStoreInfo(StoreInfo storeInfo) {
    this.storeInfo = storeInfo;
  }

  public Long getGoodsOriginalPrice() {
    return goodsOriginalPrice;
  }

  public void setGoodsOriginalPrice(Long goodsOriginalPrice) {
    this.goodsOriginalPrice = goodsOriginalPrice;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActApplyInfo {\n");
    sb.append("    storeInfo: ").append(toIndentedString(storeInfo)).append("\n");
    sb.append("    goodsOriginalPrice: ").append(toIndentedString(goodsOriginalPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
