// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** ActRule */
public class ActRule {
  /** 단일 상품 구매 시 매장에 지급하는 보조금 금액 설명: 단일 상품 구매 시 매장에 지급하는 보조금 금액 (단위: 분) */
  @SerializedName("store_subsidy")
  private Long storeSubsidy;

  /** 단일 상품 구매 시 서비스 제공자에 지급하는 수수료 설명: 단일 상품 구매 시 서비스 제공자에 지급하는 수수료 (단위: 분) */
  @SerializedName("service_provider_subsidy")
  private Long serviceProviderSubsidy;

  /** 활동 매장 보조금 상품 수 상한 설명: 활동 매장 보조금 상품 수 상한 */
  @SerializedName("store_subsidy_quota")
  private Integer storeSubsidyQuota;

  /** 단일 사용자 추가 구매 할인 횟수 상한 설명: 단일 사용자 추가 구매 할인 횟수 상한 */
  @SerializedName("user_subsidy_quota")
  private Integer userSubsidyQuota;

  /** 활동 지역 목록 설명: 활동 지역 목록 */
  @SerializedName("areas")
  private List<ActArea> areas;

  public Long getStoreSubsidy() {
    return storeSubsidy;
  }

  public void setStoreSubsidy(Long storeSubsidy) {
    this.storeSubsidy = storeSubsidy;
  }

  public Long getServiceProviderSubsidy() {
    return serviceProviderSubsidy;
  }

  public void setServiceProviderSubsidy(Long serviceProviderSubsidy) {
    this.serviceProviderSubsidy = serviceProviderSubsidy;
  }

  public Integer getStoreSubsidyQuota() {
    return storeSubsidyQuota;
  }

  public void setStoreSubsidyQuota(Integer storeSubsidyQuota) {
    this.storeSubsidyQuota = storeSubsidyQuota;
  }

  public Integer getUserSubsidyQuota() {
    return userSubsidyQuota;
  }

  public void setUserSubsidyQuota(Integer userSubsidyQuota) {
    this.userSubsidyQuota = userSubsidyQuota;
  }

  public List<ActArea> getAreas() {
    return areas;
  }

  public void setAreas(List<ActArea> areas) {
    this.areas = areas;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActRule {\n");
    sb.append("    storeSubsidy: ").append(toIndentedString(storeSubsidy)).append("\n");
    sb.append("    serviceProviderSubsidy: ")
        .append(toIndentedString(serviceProviderSubsidy))
        .append("\n");
    sb.append("    storeSubsidyQuota: ").append(toIndentedString(storeSubsidyQuota)).append("\n");
    sb.append("    userSubsidyQuota: ").append(toIndentedString(userSubsidyQuota)).append("\n");
    sb.append("    areas: ").append(toIndentedString(areas)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
