// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CreateMaterialsBody */
public class CreateMaterialsBody {
  /** 요청 비즈니스 증빙 설명: 가맹점이 비즈니스 대리인 정보 추가 증빙 번호, 가맹점 측은 고유성을 유지해야 함. 영문자, 숫자, \\\\|, \\\\_, \\\\*, \\\\- 등을 포함할 수 있으며, 기타 불법 기호는 허용되지 않음. */
  @SerializedName("out_request_no")
  private String outRequestNo;

  /** 재료 코드 생성 수량 설명: 재료 코드 생성 수량 */
  @SerializedName("material_num")
  private Long materialNum;

  public String getOutRequestNo() {
    return outRequestNo;
  }

  public void setOutRequestNo(String outRequestNo) {
    this.outRequestNo = outRequestNo;
  }

  public Long getMaterialNum() {
    return materialNum;
  }

  public void setMaterialNum(Long materialNum) {
    this.materialNum = materialNum;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMaterialsBody {\n");
    sb.append("    outRequestNo: ").append(toIndentedString(outRequestNo)).append("\n");
    sb.append("    materialNum: ").append(toIndentedString(materialNum)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
