// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/** DeleteRepresentativeRequest */
public class DeleteRepresentativeRequest {
  /** 소매점 활동 ID 설명: 소매점 활동 ID */
  @SerializedName("activity_id")
  @Expose(serialize = false)
  private String activityId;

  /** 비즈니스 대리인 정보 목록 설명: 비즈니스 대리인 정보 목록 */
  @SerializedName("representative_info_list")
  private List<RepresentativeInfo> representativeInfoList = new ArrayList<RepresentativeInfo>();

  /** 요청 비즈니스 증빙 번호 설명: 가맹점이 비즈니스 대리인 삭제 요청의 고유 식별자, 가맹점은 고유성을 보장해야 함. 영문자, 숫자, \\|, \\_, \\*, \\- 등을 포함할 수 있으며, 기타 불법 기호는 허용되지 않음. */
  @SerializedName("out_request_no")
  private String outRequestNo;

  /** 삭제 시간 설명: 삭제 시간 */
  @SerializedName("delete_time")
  private String deleteTime;

  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public List<RepresentativeInfo> getRepresentativeInfoList() {
    return representativeInfoList;
  }

  public void setRepresentativeInfoList(List<RepresentativeInfo> representativeInfoList) {
    this.representativeInfoList = representativeInfoList;
  }

  public String getOutRequestNo() {
    return outRequestNo;
  }

  public void setOutRequestNo(String outRequestNo) {
    this.outRequestNo = outRequestNo;
  }

  public String getDeleteTime() {
    return deleteTime;
  }

  public void setDeleteTime(String deleteTime) {
    this.deleteTime = deleteTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteRepresentativeRequest {\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    representativeInfoList: ")
        .append(toIndentedString(representativeInfoList))
        .append("\n");
    sb.append("    outRequestNo: ").append(toIndentedString(outRequestNo)).append("\n");
    sb.append("    deleteTime: ").append(toIndentedString(deleteTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
