// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** GoodsInfo */
public class GoodsInfo {
  /** 상품 ID 설명: 상품 ID */
  @SerializedName("goods_id")
  private String goodsId;

  /** 상품 이름 설명: 상품 이름 */
  @SerializedName("goods_name")
  private String goodsName;

  /** 상품 이미지 URL 설명: 상품 이미지 URL */
  @SerializedName("goods_picture_url")
  private String goodsPictureUrl;

  public String getGoodsId() {
    return goodsId;
  }

  public void setGoodsId(String goodsId) {
    this.goodsId = goodsId;
  }

  public String getGoodsName() {
    return goodsName;
  }

  public void setGoodsName(String goodsName) {
    this.goodsName = goodsName;
  }

  public String getGoodsPictureUrl() {
    return goodsPictureUrl;
  }

  public void setGoodsPictureUrl(String goodsPictureUrl) {
    this.goodsPictureUrl = goodsPictureUrl;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoodsInfo {\n");
    sb.append("    goodsId: ").append(toIndentedString(goodsId)).append("\n");
    sb.append("    goodsName: ").append(toIndentedString(goodsName)).append("\n");
    sb.append("    goodsPictureUrl: ").append(toIndentedString(goodsPictureUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
