// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** LockQualificationResponse */
public class LockQualificationResponse {
  /** 반환 결과 텍스트 설명: 반환 결과 텍스트 */
  @SerializedName("return_message")
  private String returnMessage;

  /** 잠금 성공한 자격 ID 목록 설명: 잠금 성공한 자격 ID 목록 */
  @SerializedName("succeed_qualification_ids")
  private List<String> succeedQualificationIds;

  /** 잠금 실패한 자격 ID 목록 설명: 잠금 실패한 자격 ID 목록 */
  @SerializedName("failed_qualification_ids")
  private List<String> failedQualificationIds;

  public String getReturnMessage() {
    return returnMessage;
  }

  public void setReturnMessage(String returnMessage) {
    this.returnMessage = returnMessage;
  }

  public List<String> getSucceedQualificationIds() {
    return succeedQualificationIds;
  }

  public void setSucceedQualificationIds(List<String> succeedQualificationIds) {
    this.succeedQualificationIds = succeedQualificationIds;
  }

  public List<String> getFailedQualificationIds() {
    return failedQualificationIds;
  }

  public void setFailedQualificationIds(List<String> failedQualificationIds) {
    this.failedQualificationIds = failedQualificationIds;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LockQualificationResponse {\n");
    sb.append("    returnMessage: ").append(toIndentedString(returnMessage)).append("\n");
    sb.append("    succeedQualificationIds: ")
        .append(toIndentedString(succeedQualificationIds))
        .append("\n");
    sb.append("    failedQualificationIds: ")
        .append(toIndentedString(failedQualificationIds))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }
}
