// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** Materials */
public class Materials {
  /** 성공한 재료 코드 목록 설명: 성공한 재료 코드 목록 */
  @SerializedName("material_list")
  private List<MaterialInfo> materialList;

  public List<MaterialInfo> getMaterialList() {
    return materialList;
  }

  public void setMaterialList(List<MaterialInfo> materialList) {
    this.materialList = materialList;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Materials {\n");
    sb.append("    materialList: ").append(toIndentedString(materialList)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
