// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 추가 구매 대외 API
//
// 지정된 서비스 제공자는 이 인터페이스를 통해 추가 구매 활동에 등록하고, 특정 지역 내의 추가 구매 활동 목록을 조회하며, 추가 구매 활동 자격을 잠그고 추가 구매 활동 자격을 잠금 해제할 수 있음.
//
// API version: 1.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.retailstore.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** StoreInfo */
public class StoreInfo {
  /** 매장 ID 설명: 매장 ID */
  @SerializedName("store_id")
  private String storeId;

  /** 매장 보조금 입금 가맹점 번호 설명: 매장이 지정한 브랜드 보조금 수취 가맹점 번호 */
  @SerializedName("accounting_merchant_id")
  private String accountingMerchantId;

  /** 매장 가맹점 번호 설명: 등록 매장의 가맹점 번호, 즉 매장 수취 가맹점 번호 */
  @SerializedName("merchant_id")
  private String merchantId;

  public String getStoreId() {
    return storeId;
  }

  public void setStoreId(String storeId) {
    this.storeId = storeId;
  }

  public String getAccountingMerchantId() {
    return accountingMerchantId;
  }

  public void setAccountingMerchantId(String accountingMerchantId) {
    this.accountingMerchantId = accountingMerchantId;
  }

  public String getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoreInfo {\n");
    sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
    sb.append("    accountingMerchantId: ")
        .append(toIndentedString(accountingMerchantId))
        .append("\n");
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
