// Copyright 2021 Tencent Inc. All rights reserved.
//
// 은행 마케팅 대외 API
//
// # 서문
// 은행 마케팅 API는 은행 가맹점을 위해 설정된 API 세트입니다. 현재는 "빠른 거래 계약 번호 업로드 작업 생성" 인터페이스만 포함되어 있으며, 은행이 빠른 거래 계약 번호 파일을 업로드하는 데 사용됩니다. 위챗 측에서 파일을 받으면, 빠른 거래 계약 번호를 위챗 사용자 ID로 변환하여 지정된 번호 패키지 파일에 저장합니다.
//
// API version: 0.1.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.marketingbankpackages.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CreateTaskRequest */
public class CreateTaskRequest {
  /**
   * 빠른 거래 계약 번호 파일
   * 설명: 빠른 거래 계약 번호 파일을 바이너리로 변환하여 얻은 바이너리 내용을 요청 body에 업로드. TXT 또는 CSV 형식의 순수 텍스트 파일만 지원하며, 각 행에 하나의 암호화된 계약 번호를 포함하고, 줄바꿈 문자는 \\n을 사용하며, 인코딩 형식은 utf-8을 사용. 위챗페이 플랫폼 인증서의 공개 키를 사용하여 계약 번호를 하나씩 암호화하고, 인증서 일련 번호를 요청 HTTP 헤더의 Wechatpay-Serial에 포함. 파일 크기는 2MB를 초과할 수 없으며, 단일 파일의 행 수는 5500행을 초과하지 않는 것을 권장. 동일 번호 패키지의 여러 업로드 작업 파일 이름은 중복될 수 없음.
   */
  @SerializedName("file")
  private FormFile file;

  /** 파일 메타 정보 설명: 빠른 계약 번호 패키지의 파일 메타 정보 */
  @SerializedName("meta")
  private FileMeta meta;

  public FormFile getFile() {
    return file;
  }

  public void setFile(FormFile file) {
    this.file = file;
  }

  public FileMeta getMeta() {
    return meta;
  }

  public void setMeta(FileMeta meta) {
    this.meta = meta;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTaskRequest {\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
