// Copyright 2021 Tencent Inc. All rights reserved.
//
// 은행 마케팅 대외 API
//
// # 서문
// 은행 마케팅 API는 은행 가맹점을 위해 설정된 API 세트입니다. 현재는 "빠른 거래 계약 번호 업로드 작업 생성" 인터페이스만 포함되어 있으며, 은행이 빠른 거래 계약 번호 파일을 업로드하는 데 사용됩니다. 위챗 측에서 파일을 받으면, 빠른 거래 계약 번호를 위챗 사용자 ID로 변환하여 지정된 번호 패키지 파일에 저장합니다.
//
// API version: 0.1.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.marketingbankpackages.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** ListTaskRequest */
public class ListTaskRequest {
  /** 번호 패키지 ID 설명: 번호 패키지 고유 식별자. 위챗페이 가맹점 플랫폼에서 번호 패키지를 생성한 후 획득할 수 있습니다. */
  @SerializedName("package_id")
  @Expose(serialize = false)
  private String packageId;

  /** 파일 이름 설명: 작업에서 업로드한 파일 이름 */
  @SerializedName("filename")
  @Expose(serialize = false)
  private String filename;

  /** 페이지 번호 설명: 페이지 번호, 페이지 번호는 0부터 시작 */
  @SerializedName("offset")
  @Expose(serialize = false)
  private Long offset;

  /** 페이지 크기 설명: 페이지 크기, 단일 조회당 최대 20개 레코드 */
  @SerializedName("limit")
  @Expose(serialize = false)
  private Long limit;

  /** 작업 상태 설명: 업로드 작업의 상태: PROCESSING - 처리 중, FINISHED - 완료됨 */
  @SerializedName("status")
  @Expose(serialize = false)
  private TaskStatus status;

  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }

  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public Long getOffset() {
    return offset;
  }

  public void setOffset(Long offset) {
    this.offset = offset;
  }

  public Long getLimit() {
    return limit;
  }

  public void setLimit(Long limit) {
    this.limit = limit;
  }

  public TaskStatus getStatus() {
    return status;
  }

  public void setStatus(TaskStatus status) {
    this.status = status;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListTaskRequest {\n");
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
