// Copyright 2021 Tencent Inc. All rights reserved.
//
// 은행 마케팅 대외 API
//
// # 서문
// 은행 마케팅 API는 은행 가맹점을 위해 설정된 API 세트입니다. 현재는 "빠른 거래 계약 번호 업로드 작업 생성" 인터페이스만 포함되어 있으며, 은행이 빠른 거래 계약 번호 파일을 업로드하는 데 사용됩니다. 위챗 측에서 파일을 받으면, 빠른 거래 계약 번호를 위챗 사용자 ID로 변환하여 지정된 번호 패키지 파일에 저장합니다.
//
// API version: 0.1.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.marketingbankpackages.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** Task */
public class Task {
  /** 업로드 작업 설명: 업로드 작업의 기본 키, 이 리소스를 고유하게 정의하는 식별자 */
  @SerializedName("task_id")
  private String taskId;

  /** 번호 패키지 ID 설명: 번호 패키지 고유 식별자. 위챗페이 가맹점 플랫폼에서 번호 패키지를 생성한 후 획득할 수 있습니다. */
  @SerializedName("package_id")
  private String packageId;

  /** 파일 이름 설명: 작업에서 업로드한 파일 이름 */
  @SerializedName("filename")
  private String filename;

  /**
   * 업로드 작업 생성 시간
   * 설명: 시간 형식은 rfc3339 표준 형식을 따르며, 형식은 YYYY-MM-DDTHH:mm:ss+TIMEZONE이며, YYYY-MM-DD는 년월일을 나타내고, T는 문자열에 나타나며 time 요소의 시작을 나타내고, HH:mm:ss는 시분초를 나타내며, TIMEZONE은 시간대를 나타냅니다(+08:00는 동부 8구 시간, UTC보다 8시간 앞서며, 즉 베이징 시간). 예: 2015-05-20T13:29:35.+08:00는 베이징 시간 2015년 5월 20일 13시 29분 35초를 나타냅니다.
   */
  @SerializedName("create_time")
  private String createTime;

  /**
   * 업로드 작업의 최근 업데이트 시간
   * 설명: 시간 형식은 rfc3339 표준 형식을 따르며, 형식은 YYYY-MM-DDTHH:mm:ss+TIMEZONE이며, YYYY-MM-DD는 년월일을 나타내고, T는 문자열에 나타나며 time 요소의 시작을 나타내고, HH:mm:ss는 시분초를 나타내며, TIMEZONE은 시간대를 나타냅니다(+08:00는 동부 8구 시간, UTC보다 8시간 앞서며, 즉 베이징 시간). 예: 2015-05-20T13:29:35.+08:00는 베이징 시간 2015년 5월 20일 13시 29분 35초를 나타냅니다.
   */
  @SerializedName("update_time")
  private String updateTime;

  /** 성공 수 설명: 매칭 성공한 계약 번호 수. 작업 상태가 FINISHED일 때만 이 데이터가 유효함 */
  @SerializedName("success_count")
  private Long successCount;

  /** 실패 수 설명: 매칭 실패한 계약 번호 수. 작업 상태가 FINISHED일 때만 이 데이터가 유효함 */
  @SerializedName("fail_count")
  private Long failCount;

  /**
   * 매칭 성공한 위챗 사용자 수
   * 설명: 매칭 성공한 위챗 사용자 수, 매칭 성공한 계약 번호 수보다 작지 않음. 한 장의 은행 카드가 사용자에 의해 다른 위챗 계정에 바인딩될 때, 하나의 계약 번호가 여러 위챗 계정에 해당하는 상황이 발생할 수 있습니다. 작업 상태가 FINISHED일 때만 이 데이터가 유효함
   */
  @SerializedName("success_user_count")
  private Long successUserCount;

  /**
   * 은행 유형
   * 설명: 은행 유형, 계약 번호가 속한 은행 및 카드 유형(신용 카드 또는 직불 카드)을 식별하는 데 사용. 문자열 유형의 은행 식별자를 사용하며, 값 목록은 [은행 유형](https://pay.weixin.qq.com/wiki/doc/apiv3_partner/terms_definition/chapter1_1_3.shtml#part-7) 참조
   */
  @SerializedName("bank_type")
  private String bankType;

  /** 작업 상태 설명: 업로드 작업의 상태: PROCESSING - 처리 중, FINISHED - 완료됨 */
  @SerializedName("status")
  private TaskStatus status;

  public String getTaskId() {
    return taskId;
  }

  public void setTaskId(String taskId) {
    this.taskId = taskId;
  }

  public String getPackageId() {
    return packageId;
  }

  public void setPackageId(String packageId) {
    this.packageId = packageId;
  }

  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public String getUpdateTime() {
    return updateTime;
  }

  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }

  public Long getSuccessCount() {
    return successCount;
  }

  public void setSuccessCount(Long successCount) {
    this.successCount = successCount;
  }

  public Long getFailCount() {
    return failCount;
  }

  public void setFailCount(Long failCount) {
    this.failCount = failCount;
  }

  public Long getSuccessUserCount() {
    return successUserCount;
  }

  public void setSuccessUserCount(Long successUserCount) {
    this.successUserCount = successUserCount;
  }

  public String getBankType() {
    return bankType;
  }

  public void setBankType(String bankType) {
    this.bankType = bankType;
  }

  public TaskStatus getStatus() {
    return status;
  }

  public void setStatus(TaskStatus status) {
    this.status = status;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Task {\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
    sb.append("    failCount: ").append(toIndentedString(failCount)).append("\n");
    sb.append("    successUserCount: ").append(toIndentedString(successUserCount)).append("\n");
    sb.append("    bankType: ").append(toIndentedString(bankType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
