// Copyright 2021 Tencent Inc. All rights reserved.
//
// 공공 교통 플랫폼 자동 차감 서비스 대외 API
//
// 공공 교통 플랫폼 자동 차감 서비스 대외 API
//
// API version: 1.0.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.weixinpayscanandride.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** BusSceneInfo */
public class BusSceneInfo {
  /** 승차 시간 설명: 사용자 승차 시간 (탑승), rfc3339에서 정의한 형식 사용, 형식은 yyyy-MM-DDThh:mm:ss+TIMEZONE */
  @SerializedName("start_time")
  private String startTime;

  /** 승차 노선 설명: 승차 노선 노선 이름 표시 규칙: \\^[A-Za-z0-9]{1,10}로$ line_name이 위 규칙에 부합하면, 차감 영수증에 승차 노선 필드가 추가로 표시됨 */
  @SerializedName("line_name")
  private String lineName;

  /** 차량 번호판 설명: 차량 번호판. 지방+번호판만 포함하며, 특수 문자는 포함하지 않음. */
  @SerializedName("plate_number")
  private String plateNumber;

  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public String getLineName() {
    return lineName;
  }

  public void setLineName(String lineName) {
    this.lineName = lineName;
  }

  public String getPlateNumber() {
    return plateNumber;
  }

  public void setPlateNumber(String plateNumber) {
    this.plateNumber = plateNumber;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusSceneInfo {\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    lineName: ").append(toIndentedString(lineName)).append("\n");
    sb.append("    plateNumber: ").append(toIndentedString(plateNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
