// Copyright 2021 Tencent Inc. All rights reserved.
//
// 공공 교통 플랫폼 자동 차감 서비스 대외 API
//
// 공공 교통 플랫폼 자동 차감 서비스 대외 API
//
// API version: 1.0.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.weixinpayscanandride.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** PromotionDetail */
public class PromotionDetail {
  /** 쿠폰 ID 설명: 쿠폰 또는 즉시 할인 ID */
  @SerializedName("coupon_id")
  private String couponId;

  /** 할인 이름 설명: 할인 이름 */
  @SerializedName("name")
  private String name;

  /** 할인 범위 설명: GLOBAL-전체 상품권, SINGLE-단일 상품 할인 */
  @SerializedName("scope")
  private String scope;

  /** 할인 유형 설명: 할인 유형, 열거형 값: */
  @SerializedName("type")
  private PromotionType type;

  /** 활동 ID 설명: 위챗페이 가맹점 백엔드에서 구성한 배치 ID */
  @SerializedName("stock_id")
  private String stockId;

  /** 쿠폰 액면가 설명: 사용자가 받는 할인 금액 */
  @SerializedName("amount")
  private Long amount;

  /** 위챗페이 출자 설명: 위챗페이 가맹점 플랫폼에서 생성한 할인을 특정하며, 출자 금액은 이 항목 할인 총액과 같으며, 단위는 분 */
  @SerializedName("wechatpay_contribute")
  private Long wechatpayContribute;

  /** 가맹점 출자 설명: 가맹점이 직접 생성한 할인을 특정하며, 출자 금액은 이 항목 할인 총액과 같으며, 단위는 분 */
  @SerializedName("merchant_contribute")
  private Long merchantContribute;

  /** 기타 출자 설명: 기타 출자 방 출자 금액, 단위는 분 */
  @SerializedName("other_contribute")
  private Long otherContribute;

  /** 할인 통화 설명: CNY: 중국 위안화, 국내 가맹점 번호는 중국 위안화만 지원. */
  @SerializedName("currency")
  private String currency;

  public String getCouponId() {
    return couponId;
  }

  public void setCouponId(String couponId) {
    this.couponId = couponId;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getScope() {
    return scope;
  }

  public void setScope(String scope) {
    this.scope = scope;
  }

  public PromotionType getType() {
    return type;
  }

  public void setType(PromotionType type) {
    this.type = type;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public Long getWechatpayContribute() {
    return wechatpayContribute;
  }

  public void setWechatpayContribute(Long wechatpayContribute) {
    this.wechatpayContribute = wechatpayContribute;
  }

  public Long getMerchantContribute() {
    return merchantContribute;
  }

  public void setMerchantContribute(Long merchantContribute) {
    this.merchantContribute = merchantContribute;
  }

  public Long getOtherContribute() {
    return otherContribute;
  }

  public void setOtherContribute(Long otherContribute) {
    this.otherContribute = otherContribute;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromotionDetail {\n");
    sb.append("    couponId: ").append(toIndentedString(couponId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    wechatpayContribute: ")
        .append(toIndentedString(wechatpayContribute))
        .append("\n");
    sb.append("    merchantContribute: ").append(toIndentedString(merchantContribute)).append("\n");
    sb.append("    otherContribute: ").append(toIndentedString(otherContribute)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
