// Copyright 2021 Tencent Inc. All rights reserved.
//
// 공공 교통 플랫폼 자동 결제 서비스 대외 API
//
// 공공 교통 플랫폼 자동 결제 서비스 대외 API
//
// API version: 1.0.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.weixinpayscanandride.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** UserServiceEntity */
public class UserServiceEntity {
  /** 자동 결제 계약 ID 설명: 계약 성공 후 위챗이 반환한 자동 결제 계약 ID */
  @SerializedName("contract_id")
  private String contractId;

  /** 사용자 서비스 사용 가능 상태 설명: 사용자 서비스 사용 가능 상태, 열거형 값: */
  @SerializedName("user_service_state")
  private UserServiceStateEnum userServiceState;

  /** 사용 불가 상태 설명 설명: blocked 서비스 상태 설명, 사용자 상태가 BLOCKED로 반환되면 이 필드가 반환되며, 구체적인 설명의 열거형 값은 다음과 같음: */
  @SerializedName("block_reason")
  private BlockReasonEnum blockReason;

  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public UserServiceStateEnum getUserServiceState() {
    return userServiceState;
  }

  public void setUserServiceState(UserServiceStateEnum userServiceState) {
    this.userServiceState = userServiceState;
  }

  public BlockReasonEnum getBlockReason() {
    return blockReason;
  }

  public void setBlockReason(BlockReasonEnum blockReason) {
    this.blockReason = blockReason;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserServiceEntity {\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    userServiceState: ").append(toIndentedString(userServiceState)).append("\n");
    sb.append("    blockReason: ").append(toIndentedString(blockReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
