// Copyright 2021 Tencent Inc. All rights reserved.
//
// 급여 카드 인터페이스 문서
//
// 서비스 제공업체는 본 API 문서에서 제공하는 인터페이스를 통해 가맹점과 급여 카드의 인증 관계 조회, 사전 인증 token 비밀번호 생성, 신원 확인 사전 주문, 신원 확인 결과 조회 등을 수행합니다。
//
// API version: 1.5.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.payrollcard.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** TransferBatchEntity */
public class TransferBatchEntity {
  /** 가맹점 배치서 번호 설명: 가맹점 시스템 내부의 가맹점 배치서 번호, 가맹점 시스템 내부에서 고유합니다 */
  @SerializedName("out_batch_no")
  private String outBatchNo;

  /** 위챗페이 배치서 번호 설명: 위챗페이 배치서 번호, 위챗 가맹점 이체 시스템이 반환하는 고유 식별자 */
  @SerializedName("batch_id")
  private String batchId;

  /** 배치 생성 시간 설명: 배치 접수 성공 시 반환되며, rfc3339에서 정의한 형식을 따릅니다. 형식은 yyyy-MM-DDThh:mm:ss+TIMEZONE입니다 */
  @SerializedName("create_time")
  private String createTime;

  public String getOutBatchNo() {
    return outBatchNo;
  }

  public void setOutBatchNo(String outBatchNo) {
    this.outBatchNo = outBatchNo;
  }

  public String getBatchId() {
    return batchId;
  }

  public void setBatchId(String batchId) {
    this.batchId = batchId;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferBatchEntity {\n");
    sb.append("    outBatchNo: ").append(toIndentedString(outBatchNo)).append("\n");
    sb.append("    batchId: ").append(toIndentedString(batchId)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
