// Copyright 2021 Tencent Inc. All rights reserved.
//
// 결제 선물 활동 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** AddActivityMerchantResponse */
public class AddActivityMerchantResponse {
  /** 활동 ID 설명: 활동 ID */
  @SerializedName("activity_id")
  private String activityId;

  /** 검증 실패한 발권 가맹점 번호 설명: 규칙 검증을 통과하지 못한 발권 가맹점 번호 목록 */
  @SerializedName("invalid_merchant_id_list")
  private List<InvalidParticipateMerchant> invalidMerchantIdList;

  /** 추가 시간 설명: 발권 가맹점 번호를 성공적으로 추가한 시간 */
  @SerializedName("add_time")
  private String addTime;

  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public List<InvalidParticipateMerchant> getInvalidMerchantIdList() {
    return invalidMerchantIdList;
  }

  public void setInvalidMerchantIdList(List<InvalidParticipateMerchant> invalidMerchantIdList) {
    this.invalidMerchantIdList = invalidMerchantIdList;
  }

  public String getAddTime() {
    return addTime;
  }

  public void setAddTime(String addTime) {
    this.addTime = addTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddActivityMerchantResponse {\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    invalidMerchantIdList: ")
        .append(toIndentedString(invalidMerchantIdList))
        .append("\n");
    sb.append("    addTime: ").append(toIndentedString(addTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
