// Copyright 2021 Tencent Inc. All rights reserved.
//
// 결제 선물 활동 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/** AddActivityMerchantRequest */
public class AddActivityMerchantRequest {
  /** 활동 ID 설명: 활동 ID */
  @SerializedName("activity_id")
  @Expose(serialize = false)
  private String activityId;

  /** 추가할 발권 가맹점 번호 설명: 활동에 새로 추가할 발권 가맹점 번호 목록 */
  @SerializedName("merchant_id_list")
  private List<String> merchantIdList = new ArrayList<String>();

  /** 요청 업무 전표 번호 설명: 가맹점이 발권 가맹점 번호를 추가하는 증빙 번호, 가맹점 측에서 고유성을 유지해야 함 */
  @SerializedName("add_request_no")
  private String addRequestNo;

  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public List<String> getMerchantIdList() {
    return merchantIdList;
  }

  public void setMerchantIdList(List<String> merchantIdList) {
    this.merchantIdList = merchantIdList;
  }

  public String getAddRequestNo() {
    return addRequestNo;
  }

  public void setAddRequestNo(String addRequestNo) {
    this.addRequestNo = addRequestNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddActivityMerchantRequest {\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    merchantIdList: ").append(toIndentedString(merchantIdList)).append("\n");
    sb.append("    addRequestNo: ").append(toIndentedString(addRequestNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
