// Copyright 2021 Tencent Inc. All rights reserved.
//
// 결제 선물 활동 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** ListActivitiesResponse */
public class ListActivitiesResponse {
  /** 결과 집합 설명: 결제 선물 활동 목록 */
  @SerializedName("data")
  private List<ActivityInformation> data;

  /** 총수 설명: 총수 */
  @SerializedName("total_count")
  private Long totalCount;

  /** 페이지 번호 설명: 페이지 번호 */
  @SerializedName("offset")
  private Long offset;

  /** 페이지 크기 설명: 페이지 크기 */
  @SerializedName("limit")
  private Long limit;

  public List<ActivityInformation> getData() {
    return data;
  }

  public void setData(List<ActivityInformation> data) {
    this.data = data;
  }

  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }

  public Long getOffset() {
    return offset;
  }

  public void setOffset(Long offset) {
    this.offset = offset;
  }

  public Long getLimit() {
    return limit;
  }

  public void setLimit(Long limit) {
    this.limit = limit;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListActivitiesResponse {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
