// Copyright 2021 Tencent Inc. All rights reserved.
//
// 결제 선물 활동 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.1.2

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.giftactivity.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** TerminateActResponse */
public class TerminateActResponse {
  /** 유효 시간 설명: 유효 시간 */
  @SerializedName("terminate_time")
  private String terminateTime;

  /** 활동 ID 설명: 활동 ID */
  @SerializedName("activity_id")
  private String activityId;

  public String getTerminateTime() {
    return terminateTime;
  }

  public void setTerminateTime(String terminateTime) {
    this.terminateTime = terminateTime;
  }

  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerminateActResponse {\n");
    sb.append("    terminateTime: ").append(toIndentedString(terminateTime)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
