// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 플랫폼 보조금 API
//
// 위챗페이 플랫폼 보조금 API
//
// API version: 0.1.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommercesubsidy.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** ReturnFrom */
public class ReturnFrom {
  /** 출자 계정 유형 설명: 다음 열거형 값 중 하나 선택. 열거형 값: AVAILABLE: 사용 가능 잔액 UNAVAILABLE: 사용 불가 잔액 */
  @SerializedName("account")
  private ReturnAccount account;

  /** 출자 금액 설명: 해당 계정 출자 금액 */
  @SerializedName("amount")
  private Long amount;

  public ReturnAccount getAccount() {
    return account;
  }

  public void setAccount(ReturnAccount account) {
    this.account = account;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnFrom {\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
