// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 플랫폼 보조금 API
//
// 위챗페이 플랫폼 보조금 API
//
// API version: 0.1.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommercesubsidy.model;

import com.google.gson.annotations.SerializedName;

/** ReturnStatus */
public enum ReturnStatus {
  @SerializedName("SUCCESS")
  SUCCESS,

  @SerializedName("FAIL")
  FAIL
}
