// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 플랫폼 보조금 API
//
// 위챗페이 플랫폼 보조금 API
//
// API version: 0.1.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommercesubsidy.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** SubsidiesCancelEntity */
public class SubsidiesCancelEntity {
  /** 전자상거래 플랫폼 하위 가맹점 번호 설명: 보조금을 받는 전자상거래 플랫폼 하위 가맹점, 위챗페이가 할당한 가맹점 번호를 기입 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 위챗 주문 번호 설명: 위챗페이 주문 번호 */
  @SerializedName("transaction_id")
  private String transactionId;

  /** 보조금 취소 결과 설명: 보조금 취소 결과 */
  @SerializedName("result")
  private CancelStatus result;

  /** 보조금 취소 설명 설명: 보조금 취소 설명 */
  @SerializedName("description")
  private String description;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public CancelStatus getResult() {
    return result;
  }

  public void setResult(CancelStatus result) {
    this.result = result;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubsidiesCancelEntity {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
