// Copyright 2021 Tencent Inc. All rights reserved.
//
// Native 결제
//
// Native 결제API
//
// API version: 1.2.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.partnerpayments.nativepay.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CloseRequest */
public class CloseRequest {
  /** 서비스 제공업체 가맹점 번호 설명: 서비스 제공업체 가맹점 번호,위챗페이가 생성하여 발급합니다 */
  @SerializedName("sp_mchid")
  private String spMchid;

  /** 하위 가맹점 번호 설명: 하위 가맹점의 가맹점 번호,위챗페이가 생성하여 발급합니다 */
  @SerializedName("sub_mchid")
  private String subMchid;

  public String getSpMchid() {
    return spMchid;
  }

  public void setSpMchid(String spMchid) {
    this.spMchid = spMchid;
  }

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloseRequest {\n");
    sb.append("    spMchid: ").append(toIndentedString(spMchid)).append("\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
