// Copyright 2021 Tencent Inc. All rights reserved.
//
// 골드 플랜 대외 API
//
// 특약 가맹점 골드 플랜 관리 API
//
// API version: 0.3.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.goldplan.model;

import com.google.gson.annotations.SerializedName;

/** 동종업계 필터 태그 열거형 값 */
public enum IndustryType {
  @SerializedName("E_COMMERCE")
  E_COMMERCE,

  @SerializedName("LOVE_MARRIAGE")
  LOVE_MARRIAGE,

  @SerializedName("POTOGRAPHY")
  POTOGRAPHY,

  @SerializedName("EDUCATION")
  EDUCATION,

  @SerializedName("FINANCE")
  FINANCE,

  @SerializedName("TOURISM")
  TOURISM,

  @SerializedName("SKINCARE")
  SKINCARE,

  @SerializedName("FOOD")
  FOOD,

  @SerializedName("SPORT")
  SPORT,

  @SerializedName("JEWELRY_WATCH")
  JEWELRY_WATCH,

  @SerializedName("HEALTHCARE")
  HEALTHCARE,

  @SerializedName("BUSSINESS")
  BUSSINESS,

  @SerializedName("PARENTING")
  PARENTING,

  @SerializedName("CATERING")
  CATERING,

  @SerializedName("RETAIL")
  RETAIL,

  @SerializedName("SERVICES")
  SERVICES,

  @SerializedName("LAW")
  LAW,

  @SerializedName("ESTATE")
  ESTATE,

  @SerializedName("TRANSPORTATION")
  TRANSPORTATION,

  @SerializedName("ENERGY_SAVING")
  ENERGY_SAVING,

  @SerializedName("SECURITY")
  SECURITY,

  @SerializedName("BUILDING_MATERIAL")
  BUILDING_MATERIAL,

  @SerializedName("COMMUNICATION")
  COMMUNICATION,

  @SerializedName("MERCHANDISE")
  MERCHANDISE,

  @SerializedName("ASSOCIATION")
  ASSOCIATION,

  @SerializedName("COMMUNITY")
  COMMUNITY,

  @SerializedName("ONLINE_AVR")
  ONLINE_AVR,

  @SerializedName("WE_MEDIA")
  WE_MEDIA,

  @SerializedName("CAR")
  CAR,

  @SerializedName("SOFTWARE")
  SOFTWARE,

  @SerializedName("GAME")
  GAME,

  @SerializedName("CLOTHING")
  CLOTHING,

  @SerializedName("INDUSTY")
  INDUSTY,

  @SerializedName("AGRICULTURE")
  AGRICULTURE,

  @SerializedName("PUBLISHING_MEDIA")
  PUBLISHING_MEDIA,

  @SerializedName("HOME_DIGITAL")
  HOME_DIGITAL
}
