// Copyright 2021 Tencent Inc. All rights reserved.
//
// 국내 일반 가맹점 환불 API
//
// 국내 일반 가맹점 환불 기능 관련 API 문서
//
// API version: 1.2.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.refund.model;

import com.google.gson.annotations.SerializedName;

/** AVAILABLE - 사용 가능한 잔액, 다중 계좌 자금 준비 환불 사용 가능한 잔액 출자 계좌 유형 UNAVAILABLE - 사용 불가능한 잔액, 다중 계좌 자금 준비 환불 사용 불가능한 잔액 출자 계좌 유형 */
public enum Account {
  @SerializedName("AVAILABLE")
  AVAILABLE,

  @SerializedName("UNAVAILABLE")
  UNAVAILABLE
}
