// Copyright 2021 Tencent Inc. All rights reserved.
//
// 국내 일반 가맹점 환불 API
//
// 국내 일반 가맹점 환불 기능 관련 API 문서
//
// API version: 1.2.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.refund.model;

import com.google.gson.annotations.SerializedName;

/**
 * UNSETTLED - 미정산 자금, 환불에 사용된 자금에 해당하는 자금 계좌 유형 AVAILABLE - 사용 가능한 잔액, 환불에 사용된 자금에 해당하는 자금 계좌 유형 UNAVAILABLE -
 * 사용 불가능한 잔액, 환불에 사용된 자금에 해당하는 자금 계좌 유형 OPERATION - 운영 계좌, 환불에 사용된 자금에 해당하는 자금 계좌 유형 BASIC -
 * 기본 계좌 (사용 가능한 잔액과 사용 불가능한 잔액 포함), 환불에 사용된 자금에 해당하는 자금 계좌 유형 ECNY_BASIC - 디지털 위안화 기본 계좌, 환불에 사용된 자금에 해당하는 자금 계좌 유형
 */
public enum FundsAccount {
  @SerializedName("UNSETTLED")
  UNSETTLED,

  @SerializedName("AVAILABLE")
  AVAILABLE,

  @SerializedName("UNAVAILABLE")
  UNAVAILABLE,

  @SerializedName("OPERATION")
  OPERATION,

  @SerializedName("BASIC")
  BASIC,

  @SerializedName("ECNY_BASIC")
  ECNY_BASIC
}
