// Copyright 2021 Tencent Inc. All rights reserved.
//
// 국내 일반 가맹점 환불 API
//
// 국내 일반 가맹점 환불 기능 관련 API 문서
//
// API version: 1.2.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.refund.model;

import com.google.gson.annotations.SerializedName;

/** AVAILABLE - 사용 가능한 잔액, 기존 자금 흐름 가맹점에만 적용, 사용 가능한 잔액 계좌에서 출자 지정 */
public enum ReqFundsAccount {
  @SerializedName("AVAILABLE")
  AVAILABLE
}
