// Copyright 2021 Tencent Inc. All rights reserved.
//
// 국내 일반 가맹점 환불 API
//
// 국내 일반 가맹점 환불 기능 관련 API 문서
//
// API version: 1.2.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.refund.model;

import com.google.gson.annotations.SerializedName;

/** GLOBAL - 전역 상품권, 전역 혜택 유형 SINGLE - 단품 혜택, 단품 혜택 유형 */
public enum Scope {
  @SerializedName("GLOBAL")
  GLOBAL,

  @SerializedName("SINGLE")
  SINGLE
}
