// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import com.google.gson.annotations.SerializedName;

/** AcceptorTypeEnum */
public enum AcceptorTypeEnum {
  @SerializedName("MERCHANT_ID")
  MERCHANT_ID,

  @SerializedName("PERSONAL_OPENID")
  PERSONAL_OPENID
}
