// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** AddReceiverRequest */
public class AddReceiverRequest {
  /** 공개 계정 ID 설명: 위챗이 할당한 공개 계정 ID */
  @SerializedName("appid")
  private String appid;

  /** 수신자 유형 설명: 수신자 유형 열거형 값: MERCHANT_ID: 가맹점 PERSONAL_OPENID: 개인 */
  @SerializedName("type")
  private String type;

  /** 수신자 계정 설명: 유형이 MERCHANT_ID인 경우, 가맹점 번호 유형이 PERSONAL_OPENID인 경우, 개인 openid */
  @SerializedName("account")
  private String account;

  /** 수신자 이름 설명: 가맹점 전체 이름. 수신자 유형이 MERCHANT_ID일 때만 이 필드를 기입해야 함. */
  @SerializedName("name")
  private String name;

  /**
   * 분할 당사자와의 관계 유형 설명: 하위 가맹점과 수신자의 관계. 본 필드 값은 열거형: SUPPLIER: 공급업체 DISTRIBUTOR: 유통업체 SERVICE_PROVIDER: 서비스 제공업체 PLATFORM: 플랫폼
   * OTHERS: 기타
   */
  @SerializedName("relation_type")
  private String relationType;

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getRelationType() {
    return relationType;
  }

  public void setRelationType(String relationType) {
    this.relationType = relationType;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddReceiverRequest {\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relationType: ").append(toIndentedString(relationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
