// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CreateReturnOrderRequest */
public class CreateReturnOrderRequest {
  /** 전자상거래 플랫폼 하위 가맹점 번호 설명: 분할 환불 수신 가맹점, 원래 분할 출자 전자상거래 플랫폼 하위 가맹점에 대응, 위챗페이가 할당한 가맹점 번호를 기입 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 위챗 분할 내역 번호 설명: 위챗 분할 내역 번호, 위챗 시스템이 반환한 고유 식별자. 위챗 분할 내역 번호와 가맹점 분할 내역 번호 중 하나 선택하여 기입 */
  @SerializedName("order_id")
  private String orderId;

  /**
   * 가맹점 분할 내역 번호 설명: 가맹점 시스템 내부의 분할 내역 번호, 가맹점 시스템 내부에서 고유함(단일 분할, 다중 분할, 완료 분할은 서로 다른 가맹점 분할 내역 번호를 사용해야 함), 동일 분할 내역 번호로 여러 번 요청하면 한 번과 동일함. 숫자, 대소문자 영문, _, -, |, *, @만 가능
   * . 위챗 분할 내역 번호와 가맹점 분할 내역 번호 중 하나 선택하여 기입
   */
  @SerializedName("out_order_no")
  private String outOrderNo;

  /** 가맹점 환불 내역 번호 설명: 이 환불 내역 번호는 가맹점이 자체 백엔드에서 생성한 새로운 환불 내역 번호로, 가맹점 백엔드에서 고유함 숫자, 대소문자 영문, _, -, |, *, @만 가능, 동일 환불 내역 번호로 여러 번 요청하면 한 번과 동일함. */
  @SerializedName("out_return_no")
  private String outReturnNo;

  /** 환불 가맹점 번호 설명: 원래 분할 요청에서 성공적으로 분할된 가맹점 수신자에 대해서만 환불 가능 */
  @SerializedName("return_mchid")
  private String returnMchid;

  /** 환불 금액 설명: 분할 수신자로부터 환불해야 하는 금액, 단위는 전, 정수만 가능, 원래 분할 내역서에서 해당 수신자에게 분할된 금액을 초과할 수 없음 */
  @SerializedName("amount")
  private Long amount;

  /** 환불 설명 설명: 분할 환불 사유 설명 */
  @SerializedName("description")
  private String description;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  public String getOutReturnNo() {
    return outReturnNo;
  }

  public void setOutReturnNo(String outReturnNo) {
    this.outReturnNo = outReturnNo;
  }

  public String getReturnMchid() {
    return returnMchid;
  }

  public void setReturnMchid(String returnMchid) {
    this.returnMchid = returnMchid;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateReturnOrderRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    outOrderNo: ").append(toIndentedString(outOrderNo)).append("\n");
    sb.append("    outReturnNo: ").append(toIndentedString(outReturnNo)).append("\n");
    sb.append("    returnMchid: ").append(toIndentedString(returnMchid)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
