// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CreateAfterSalesOrderRequest */
public class CreateAfterSalesOrderRequest {
  /** 하위 가맹점 번호 설명: 분할 출자 가맹점, 위챗페이가 할당한 가맹점 번호를 기입 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 위챗 주문 번호 설명: 위챗페이 주문 번호 */
  @SerializedName("transaction_id")
  private String transactionId;

  /** 분할 금액 설명: 분할 금액, 단위는 전, 정수만 가능, 원 주문 결제 금액 및 최대 분할 비율 금액을 초과할 수 없음 */
  @SerializedName("amount")
  private Long amount;

  /** 유형 설명: 열거형 값: 1, SERVICE_FEE_INCOME: 서비스 수수료 수입 분할 */
  @SerializedName("type")
  private String type;

  /** 시나리오 설명: 열거형 값: 1, REFUND_TICKET: 티켓 환불 2, CHANGE_TICKET: 티켓 변경 3, RETURN_GOODS: 상품 반품 */
  @SerializedName("scene")
  private String scene;

  /** 위챗 환불 내역 번호 설명: 해당 위챗 주문에 대응하는 위챗 환불 내역 번호. 티켓 환불 수입 분할, 티켓 변경 환불 수입 분할, 상품 반품 수입 분할 시 필수. */
  @SerializedName("refund_id")
  private String refundId;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getScene() {
    return scene;
  }

  public void setScene(String scene) {
    this.scene = scene;
  }

  public String getRefundId() {
    return refundId;
  }

  public void setRefundId(String refundId) {
    this.refundId = refundId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAfterSalesOrderRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    scene: ").append(toIndentedString(scene)).append("\n");
    sb.append("    refundId: ").append(toIndentedString(refundId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
