// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** QueryAfterSalesOrderResponse */
public class QueryAfterSalesOrderResponse {
  /** 하위 가맹점 번호 설명: 분할 출자 가맹점 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 위챗 주문 번호 설명: 위챗페이 주문 번호 */
  @SerializedName("transaction_id")
  private String transactionId;

  /** 분할 금액 설명: 분할 금액, 단위는 전, 정수만 가능, 원 주문 결제 금액 및 최대 분할 비율 금액을 초과할 수 없음 */
  @SerializedName("amount")
  private Long amount;

  /**
   * 분할 결과 설명: 열거형 값: 1, PROCESSING: 분할 중(나중에 조회하여 결과 확인) 2, SUCCESS: 분할 성공(최종 상태) 3, FAILED:
   * 분할 실패(최종 상태, 자금 미변동 또는 자금이 분할 출자 당사자로 전환됨, 가맹점이 자체 처리, 구체적 실패 사유는 "분할 실패 사유" 필드 참조)
   */
  @SerializedName("result")
  private String result;

  /** 분할 완료 시간 설명: 분할 완료 시간, RFC3339 표준 형식 준수 */
  @SerializedName("finish_time")
  private String finishTime;

  /**
   * 분할 실패 사유 설명: 분할 실패 사유. 다음 열거형 값 포함: 1. ACCOUNT_ABNORMAL: 분할 수신 계정 이상 2. NO_RELATION: 분할 관계 해제됨 3.
   * RECEIVER_HIGH_RISK: 고위험 수신자
   */
  @SerializedName("fail_reason")
  private String failReason;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public String getFinishTime() {
    return finishTime;
  }

  public void setFinishTime(String finishTime) {
    this.finishTime = finishTime;
  }

  public String getFailReason() {
    return failReason;
  }

  public void setFailReason(String failReason) {
    this.failReason = failReason;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryAfterSalesOrderResponse {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    finishTime: ").append(toIndentedString(finishTime)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
