// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** QueryReturnOrderRequest */
public class QueryReturnOrderRequest {
  /** 전자상거래 플랫폼 하위 가맹점 번호 설명: 분할 환불 수신 가맹점, 원래 분할 출자 전자상거래 플랫폼 하위 가맹점에 대응, 위챗페이가 할당한 가맹점 번호를 기입 */
  @SerializedName("sub_mchid")
  @Expose(serialize = false)
  private String subMchid;

  /** 가맹점 환불 내역 번호 설명: 환불 인터페이스 호출 시 제공한 가맹점 시스템 내부의 환불 내역 번호 */
  @SerializedName("out_return_no")
  @Expose(serialize = false)
  private String outReturnNo;

  /** 위챗 분할 내역 번호 설명: 원래 분할 요청을 시작할 때, 위챗이 반환한 위챗 분할 내역 번호, 가맹점 분할 내역 번호와 일대일 대응. 위챗 분할 내역 번호와 가맹점 분할 내역 번호 중 하나 선택하여 기입 */
  @SerializedName("order_id")
  @Expose(serialize = false)
  private String orderId;

  /** 가맹점 분할 내역 번호 설명: 원래 분할 요청을 시작할 때 사용한 가맹점 시스템 내부의 분할 내역 번호. 위챗 분할 내역 번호와 가맹점 분할 내역 번호 중 하나 선택하여 기입 */
  @SerializedName("out_order_no")
  @Expose(serialize = false)
  private String outOrderNo;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getOutReturnNo() {
    return outReturnNo;
  }

  public void setOutReturnNo(String outReturnNo) {
    this.outReturnNo = outReturnNo;
  }

  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryReturnOrderRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    outReturnNo: ").append(toIndentedString(outReturnNo)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    outOrderNo: ").append(toIndentedString(outOrderNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
