// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** QueryAfterSalesOrderRequest */
public class QueryAfterSalesOrderRequest {
  /** 하위 가맹점 번호 설명: 분할 출자 가맹점, 위챗페이가 할당한 가맹점 번호를 기입 */
  @SerializedName("sub_mchid")
  @Expose(serialize = false)
  private String subMchid;

  /** 위챗 주문 번호 설명: 위챗페이 주문 번호 */
  @SerializedName("transaction_id")
  @Expose(serialize = false)
  private String transactionId;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryAfterSalesOrderRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
