// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// 위챗페이 전자상거래 플랫폼 분할 API
//
// API version: 1.0.21

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommerceprofitsharing.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** QueryReturnOrderResponse */
public class QueryReturnOrderResponse {
  /** 전자상거래 플랫폼 하위 가맹점 번호 설명: 분할 환불 수신 가맹점, 원래 분할 출자 전자상거래 플랫폼 하위 가맹점에 대응, 위챗페이가 할당한 가맹점 번호를 기입 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 위챗 분할 내역 번호 설명: 위챗 분할 내역 번호, 위챗 시스템이 반환한 고유 식별자 */
  @SerializedName("order_id")
  private String orderId;

  /** 가맹점 분할 내역 번호 설명: 가맹점 시스템 내부의 분할 내역 번호, 가맹점 시스템 내부에서 고유함(단일 분할, 다중 분할, 완료 분할은 서로 다른 가맹점 분할 내역 번호를 사용해야 함), 동일 분할 내역 번호로 여러 번 요청하면 한 번과 동일함. 숫자, 대소문자 영문, _, -, |, *, @만 가능 */
  @SerializedName("out_order_no")
  private String outOrderNo;

  /** 가맹점 환불 내역 번호 설명: 이 환불 내역 번호는 가맹점이 자체 백엔드에서 생성한 새로운 환불 내역 번호로, 가맹점 백엔드에서 고유함 숫자, 대소문자 영문, _, -, |, *, @만 가능, 동일 환불 내역 번호로 여러 번 요청하면 한 번과 동일함. */
  @SerializedName("out_return_no")
  private String outReturnNo;

  /** 위챗 환불 내역 번호 설명: 위챗 분할 환불 내역 번호, 위챗 시스템이 반환한 고유 식별자 */
  @SerializedName("return_no")
  private String returnNo;

  /** 환불 가맹점 번호 설명: 원래 분할 요청에서 성공적으로 분할된 가맹점 수신자에 대해서만 환불 가능 */
  @SerializedName("return_mchid")
  private String returnMchid;

  /** 환불 금액 설명: 분할 수신자로부터 환불해야 하는 금액, 단위는 전, 정수만 가능, 원래 분할 내역서에서 해당 수신자에게 분할된 금액을 초과할 수 없음 */
  @SerializedName("amount")
  private Long amount;

  /**
   * 환불 결과 설명: 요청 반환값이 처리 중인 경우, 가맹점은 환불 결과 조회 인터페이스를 호출하여 요청의 최종 처리 결과를 획득할 수 있음 열거형 값: PROCESSING: 처리 중 SUCCESS: 성공함 FAILED: 실패함
   * 참고: 반환값이 처리 중인 경우, 가맹점 환불 내역 번호를 변경하지 말고 동일한 매개변수로 다시 분할 환불을 시작해야 하며, 그렇지 않으면 자금 위험이 발생함 처리 중 상태의 환불 내역이 5일 동안 성공하지 않으면, 시간 초과로 인해 실패로 설정됨
   */
  @SerializedName("result")
  private String result;

  /**
   * 실패 사유 설명: 실패 사유. 다음 열거형 값 포함: 1. ACCOUNT_ABNORMAL: 원래 분할 수신자 계정 이상 2. TIME_OUT_CLOSED: 시간 초과로 주문 닫음 3.
   * PAYER_ACCOUNT_ABNORMAL: 원래 분할 분출 당사자 계정 이상 4. INVALID_REQUEST: 설명 매개변수 설정 실패
   */
  @SerializedName("fail_reason")
  private String failReason;

  /** 완료 시간 설명: 분할 환불 완료 시간, RFC3339 표준 형식 준수 */
  @SerializedName("finish_time")
  private String finishTime;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public String getOutOrderNo() {
    return outOrderNo;
  }

  public void setOutOrderNo(String outOrderNo) {
    this.outOrderNo = outOrderNo;
  }

  public String getOutReturnNo() {
    return outReturnNo;
  }

  public void setOutReturnNo(String outReturnNo) {
    this.outReturnNo = outReturnNo;
  }

  public String getReturnNo() {
    return returnNo;
  }

  public void setReturnNo(String returnNo) {
    this.returnNo = returnNo;
  }

  public String getReturnMchid() {
    return returnMchid;
  }

  public void setReturnMchid(String returnMchid) {
    this.returnMchid = returnMchid;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public String getFailReason() {
    return failReason;
  }

  public void setFailReason(String failReason) {
    this.failReason = failReason;
  }

  public String getFinishTime() {
    return finishTime;
  }

  public void setFinishTime(String finishTime) {
    this.finishTime = finishTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryReturnOrderResponse {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    outOrderNo: ").append(toIndentedString(outOrderNo)).append("\n");
    sb.append("    outReturnNo: ").append(toIndentedString(outReturnNo)).append("\n");
    sb.append("    returnNo: ").append(toIndentedString(returnNo)).append("\n");
    sb.append("    returnMchid: ").append(toIndentedString(returnMchid)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("    finishTime: ").append(toIndentedString(finishTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
