// Copyright 2021 Tencent Inc. All rights reserved.
//
// JSAPI 결제
//
// JSAPI 결제API
//
// API version: 1.2.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.partnerpayments.jsapi.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** PrepayRequest */
public class PrepayRequest {
  /** 서비스 제공업체 애플리케이션 ID 설명: 서비스 제공업체가 신청한 공개 계정 appid */
  @SerializedName("sp_appid")
  private String spAppid;

  /** 서비스 제공업체 가맹점 번호 설명: 서비스 제공업체 가맹점 번호,위챗페이가 생성하여 발급합니다 */
  @SerializedName("sp_mchid")
  private String spMchid;

  /** 하위 가맹점 애플리케이션 ID 설명: 하위 가맹점이 신청한 공개 계정 appid */
  @SerializedName("sub_appid")
  private String subAppid;

  /** 하위 가맹점 번호 설명: 하위 가맹점의 가맹점 번호,위챗페이가 생성하여 발급합니다 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 상품 설명 설명: 상품 설명 */
  @SerializedName("description")
  private String description;

  /** 가맹점 주문 번호 설명: 가맹점 주문 번호 */
  @SerializedName("out_trade_no")
  private String outTradeNo;

  /** 거래 종료 시간 설명: 주문 만료 시간,형식은 rfc3339 형식입니다 */
  @SerializedName("time_expire")
  private String timeExpire;

  /** 추가 데이터 설명: 추가 데이터 */
  @SerializedName("attach")
  private String attach;

  /** 알림 주소 설명: 유효성: 1. HTTPS; 2. 쿼리 문자열을 포함할 수 없습니다. */
  @SerializedName("notify_url")
  private String notifyUrl;

  /** 주문 할인 표시 설명: 상품 표시, 상품권 또는 즉시 할인 기능의 매개변수. */
  @SerializedName("goods_tag")
  private String goodsTag;

  /** limitPay */
  public enum LimitPayEnum {
    @SerializedName("no_balance")
    NO_BALANCE,

    @SerializedName("no_credit")
    NO_CREDIT,

    @SerializedName("no_debit")
    NO_DEBIT,

    @SerializedName("balance_only")
    BALANCE_ONLY
  }

  @SerializedName("limit_pay")
  private List<LimitPayEnum> limitPay;

  /** 전자 영수증 입구 개방 식별자 설명: true를 전달하면 결제 성공 메시지와 결제 상세 페이지에 영수증 발행 입구가 나타납니다. 위챗페이 가맹점 플랫폼 또는 위챗 공개 플랫폼에서 전자 영수증 기능을 활성화해야 하며, 이 필드를 전달해야만 적용됩니다. */
  @SerializedName("support_fapiao")
  private Boolean supportFapiao;

  /** amount */
  @SerializedName("amount")
  private Amount amount;

  /** payer */
  @SerializedName("payer")
  private Payer payer;

  /** detail */
  @SerializedName("detail")
  private Detail detail;

  /** sceneInfo */
  @SerializedName("scene_info")
  private SceneInfo sceneInfo;

  /** settleInfo */
  @SerializedName("settle_info")
  private SettleInfo settleInfo;

  public String getSpAppid() {
    return spAppid;
  }

  public void setSpAppid(String spAppid) {
    this.spAppid = spAppid;
  }

  public String getSpMchid() {
    return spMchid;
  }

  public void setSpMchid(String spMchid) {
    this.spMchid = spMchid;
  }

  public String getSubAppid() {
    return subAppid;
  }

  public void setSubAppid(String subAppid) {
    this.subAppid = subAppid;
  }

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getOutTradeNo() {
    return outTradeNo;
  }

  public void setOutTradeNo(String outTradeNo) {
    this.outTradeNo = outTradeNo;
  }

  public String getTimeExpire() {
    return timeExpire;
  }

  public void setTimeExpire(String timeExpire) {
    this.timeExpire = timeExpire;
  }

  public String getAttach() {
    return attach;
  }

  public void setAttach(String attach) {
    this.attach = attach;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  public String getGoodsTag() {
    return goodsTag;
  }

  public void setGoodsTag(String goodsTag) {
    this.goodsTag = goodsTag;
  }

  public List<LimitPayEnum> getLimitPay() {
    return limitPay;
  }

  public void setLimitPay(List<LimitPayEnum> limitPay) {
    this.limitPay = limitPay;
  }

  public Boolean getSupportFapiao() {
    return supportFapiao;
  }

  public void setSupportFapiao(Boolean supportFapiao) {
    this.supportFapiao = supportFapiao;
  }

  public Amount getAmount() {
    return amount;
  }

  public void setAmount(Amount amount) {
    this.amount = amount;
  }

  public Payer getPayer() {
    return payer;
  }

  public void setPayer(Payer payer) {
    this.payer = payer;
  }

  public Detail getDetail() {
    return detail;
  }

  public void setDetail(Detail detail) {
    this.detail = detail;
  }

  public SceneInfo getSceneInfo() {
    return sceneInfo;
  }

  public void setSceneInfo(SceneInfo sceneInfo) {
    this.sceneInfo = sceneInfo;
  }

  public SettleInfo getSettleInfo() {
    return settleInfo;
  }

  public void setSettleInfo(SettleInfo settleInfo) {
    this.settleInfo = settleInfo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrepayRequest {\n");
    sb.append("    spAppid: ").append(toIndentedString(spAppid)).append("\n");
    sb.append("    spMchid: ").append(toIndentedString(spMchid)).append("\n");
    sb.append("    subAppid: ").append(toIndentedString(subAppid)).append("\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    outTradeNo: ").append(toIndentedString(outTradeNo)).append("\n");
    sb.append("    timeExpire: ").append(toIndentedString(timeExpire)).append("\n");
    sb.append("    attach: ").append(toIndentedString(attach)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("    goodsTag: ").append(toIndentedString(goodsTag)).append("\n");
    sb.append("    limitPay: ").append(toIndentedString(limitPay)).append("\n");
    sb.append("    supportFapiao: ").append(toIndentedString(supportFapiao)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    payer: ").append(toIndentedString(payer)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    sceneInfo: ").append(toIndentedString(sceneInfo)).append("\n");
    sb.append("    settleInfo: ").append(toIndentedString(settleInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
