// Copyright 2021 Tencent Inc. All rights reserved.
//
// H5 결제
//
// H5 결제API
//
// API version: 1.2.3

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.partnerpayments.h5.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** QueryOrderByOutTradeNoRequest */
public class QueryOrderByOutTradeNoRequest {
  /** outTradeNo 설명: 가맹점 주문 번호 */
  @SerializedName("out_trade_no")
  @Expose(serialize = false)
  private String outTradeNo;

  /** spMchid 설명: 서비스 제공업체 가맹점 번호 */
  @SerializedName("sp_mchid")
  @Expose(serialize = false)
  private String spMchid;

  /** subMchid 설명: 하위 가맹점 번호 */
  @SerializedName("sub_mchid")
  @Expose(serialize = false)
  private String subMchid;

  public String getOutTradeNo() {
    return outTradeNo;
  }

  public void setOutTradeNo(String outTradeNo) {
    this.outTradeNo = outTradeNo;
  }

  public String getSpMchid() {
    return spMchid;
  }

  public void setSpMchid(String spMchid) {
    this.spMchid = spMchid;
  }

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryOrderByOutTradeNoRequest {\n");
    sb.append("    outTradeNo: ").append(toIndentedString(outTradeNo)).append("\n");
    sb.append("    spMchid: ").append(toIndentedString(spMchid)).append("\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
