// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** AssociateTradeInfoRequest */
public class AssociateTradeInfoRequest {
  /** 배치 번호 설명:위챗페이가 각 가맹점 쿠폰 배치에 할당한 고유 ID，对于商户自定义code的批次，关联请求必须填写배치 번호 */
  @SerializedName("stock_id")
  private String stockId;

  /** 쿠폰 code 설명: 쿠폰의 고유 식별자 */
  @SerializedName("coupon_code")
  private String couponCode;

  /** 연결된 가맹점 주문 번호 설명:微信支付下单时的商户订单号，欲与该商家券关联的微信支付 */
  @SerializedName("out_trade_no")
  private String outTradeNo;

  /** 请求业务单据号 설명:가맹점이 배치를 생성한 증빙 번호 (형식: 가맹점 ID+날짜+순번), 가맹점 측에서 고유성 유지 필요，可包含英文字母，数字，｜，\\_，\\*，-等内容，不允许出现其他不合法符号。 */
  @SerializedName("out_request_no")
  private String outRequestNo;

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getOutTradeNo() {
    return outTradeNo;
  }

  public void setOutTradeNo(String outTradeNo) {
    this.outTradeNo = outTradeNo;
  }

  public String getOutRequestNo() {
    return outRequestNo;
  }

  public void setOutRequestNo(String outRequestNo) {
    this.outRequestNo = outRequestNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssociateTradeInfoRequest {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    outTradeNo: ").append(toIndentedString(outTradeNo)).append("\n");
    sb.append("    outRequestNo: ").append(toIndentedString(outRequestNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
