// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** AvailableCurrentDayTime */
public class AvailableCurrentDayTime {
  /** 당일 사용 가능 시작 시간 설명: 당일 사용 가능 시작 시간 단위 초 1은 당일 0시 0분 1초를 나타냄 */
  @SerializedName("begin_time")
  private Long beginTime;

  /** 당일 사용 가능 종료 시간 설명: 당일 사용 가능 종료 시간 단위 초 86399는 당일 23시 59분 59초를 나타냄 */
  @SerializedName("end_time")
  private Long endTime;

  public Long getBeginTime() {
    return beginTime;
  }

  public void setBeginTime(Long beginTime) {
    this.beginTime = beginTime;
  }

  public Long getEndTime() {
    return endTime;
  }

  public void setEndTime(Long endTime) {
    this.endTime = endTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableCurrentDayTime {\n");
    sb.append("    beginTime: ").append(toIndentedString(beginTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
