// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** CouponCodeInfoRequest */
public class CouponCodeInfoRequest {
  /** 배치 번호 설명:商家券배치 번호 */
  @SerializedName("stock_id")
  @Expose(serialize = false)
  private String stockId;

  /** 商户上传code 설명:商户上传code */
  @SerializedName("coupon_code")
  @Expose(serialize = false)
  private String couponCode;

  /** 公众账号ID 설명:公众账号ID */
  @SerializedName("appid")
  @Expose(serialize = false)
  private String appid;

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponCodeInfoRequest {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
