// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** DeactivateCouponRequest */
public class DeactivateCouponRequest {
  /** 쿠폰 code 설명: 쿠폰의 고유 식별자 */
  @SerializedName("coupon_code")
  private String couponCode;

  /** 배치 번호 설명:쿠폰이 속한 배치 번호 */
  @SerializedName("stock_id")
  private String stockId;

  /** 무효화 요청 증빙 번호 설명:매번 무효화 요청의 고유 식별자, 가맹점은 고유성 보장 필요 */
  @SerializedName("deactivate_request_no")
  private String deactivateRequestNo;

  /** 무효화 사유 설명:가맹점이 쿠폰을 무효화한 사유 */
  @SerializedName("deactivate_reason")
  private String deactivateReason;

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getDeactivateRequestNo() {
    return deactivateRequestNo;
  }

  public void setDeactivateRequestNo(String deactivateRequestNo) {
    this.deactivateRequestNo = deactivateRequestNo;
  }

  public String getDeactivateReason() {
    return deactivateReason;
  }

  public void setDeactivateReason(String deactivateReason) {
    this.deactivateReason = deactivateReason;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeactivateCouponRequest {\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    deactivateRequestNo: ")
        .append(toIndentedString(deactivateRequestNo))
        .append("\n");
    sb.append("    deactivateReason: ").append(toIndentedString(deactivateReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
