// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** DeleteCouponCodeRequest */
public class DeleteCouponCodeRequest {
  /** 배치 번호 설명:가맹점 쿠폰 배치 번호 */
  @SerializedName("stock_id")
  @Expose(serialize = false)
  private String stockId;

  /** 쿠폰 code 설명:업로드한 사용자 정의 code */
  @SerializedName("coupon_code")
  @Expose(serialize = false)
  private String couponCode;

  /** 요청 업무 증빙 번호 설명:가맹점이 code를 삭제한 증빙 번호，가맹점 측에서 고유성 유지 필요 */
  @SerializedName("delete_request_no")
  @Expose(serialize = false)
  private String deleteRequestNo;

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getDeleteRequestNo() {
    return deleteRequestNo;
  }

  public void setDeleteRequestNo(String deleteRequestNo) {
    this.deleteRequestNo = deleteRequestNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteCouponCodeRequest {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    deleteRequestNo: ").append(toIndentedString(deleteRequestNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
