// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** ListCouponsByFilterRequest */
public class ListCouponsByFilterRequest {
  /**
   * 사용자 식별자 설명:Openid 정보，AppID 하의 사용자 고유 식별자。
   * 검증 규칙:전달한 OpenID는 호출 측 가맹점 번호(즉, 요청 헤더 내 가맹점 번호)와 바인딩 관계가 있는 AppID에서 획득한 OpenID이거나, 전달한 OpenID는 소속 가맹점 번호와 바인딩 관계가 있는 AppID에서 획득한 OpenID여야 합니다. [OpenID 획득 문서](https://pay.weixin.qq.com/wiki/doc/apiv3/terms_definition/chapter1_1_3.shtml#part-3)
   */
  @SerializedName("openid")
  @Expose(serialize = false)
  private String openid;

  /**
   * 공개 계정 ID 설명: 현재 호출 인터페이스 가맹점 번호와 바인딩 관계가 있는 AppID 전달 지원. 미니프로그램 AppID와 공개 계정 AppID 지원.
   * 검증 규칙: 전달한 AppID는 호출 측 가맹점 번호(즉, 요청 헤더 내 가맹점 번호)와 바인딩 관계가 있는 AppID이거나, 전달한 AppID는 소속 가맹점 번호와 바인딩 관계가 있는 AppID여야 함
   */
  @SerializedName("appid")
  @Expose(serialize = false)
  private String appid;

  /** 배치 번호 설명: 배치 번호, 배치 번호 지정 조회 여부 */
  @SerializedName("stock_id")
  @Expose(serialize = false)
  private String stockId;

  /** 배치 생성 가맹점 번호 설명: 배치 생성 측 가맹점 번호 검증 규칙: 호출 측 가맹점 번호(즉, 요청 헤더 내 가맹점 번호)가 배치 생성 측 가맹점 번호인 경우, 이 매개변수는 필수 전달 */
  @SerializedName("creator_merchant")
  @Expose(serialize = false)
  private String creatorMerchant;

  /** 배치 소속 가맹점 번호 설명: 배치 소속 가맹점 번호 검증 규칙: 호출 측 가맹점 번호(즉, 요청 헤더 내 가맹점 번호)가 배치 소속 가맹점 번호인 경우, 이 매개변수는 필수 전달 */
  @SerializedName("belong_merchant")
  @Expose(serialize = false)
  private String belongMerchant;

  /** 배치 발송 가맹점 번호 설명: 배치 발송 가맹점 번호 검증 규칙: 호출 측 가맹점 번호(즉, 요청 헤더 내 가맹점 번호)가 배치 발송 가맹점 번호인 경우, 이 매개변수는 필수 전달. 위탁 마케팅 관계 하에서는 위탁 쿠폰 발송 가맹점 번호를 입력하세요 */
  @SerializedName("sender_merchant")
  @Expose(serialize = false)
  private String senderMerchant;

  /** 페이지 번호 설명: 페이지 번호 */
  @SerializedName("offset")
  @Expose(serialize = false)
  private Integer offset;

  /** 페이지 크기 설명: 페이지 크기 */
  @SerializedName("limit")
  @Expose(serialize = false)
  private Integer limit;

  /** 쿠폰 상태 설명:가맹점 쿠폰 상태 */
  @SerializedName("coupon_state")
  @Expose(serialize = false)
  private CouponStatus couponState;

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCreatorMerchant() {
    return creatorMerchant;
  }

  public void setCreatorMerchant(String creatorMerchant) {
    this.creatorMerchant = creatorMerchant;
  }

  public String getBelongMerchant() {
    return belongMerchant;
  }

  public void setBelongMerchant(String belongMerchant) {
    this.belongMerchant = belongMerchant;
  }

  public String getSenderMerchant() {
    return senderMerchant;
  }

  public void setSenderMerchant(String senderMerchant) {
    this.senderMerchant = senderMerchant;
  }

  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public CouponStatus getCouponState() {
    return couponState;
  }

  public void setCouponState(CouponStatus couponState) {
    this.couponState = couponState;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCouponsByFilterRequest {\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    creatorMerchant: ").append(toIndentedString(creatorMerchant)).append("\n");
    sb.append("    belongMerchant: ").append(toIndentedString(belongMerchant)).append("\n");
    sb.append("    senderMerchant: ").append(toIndentedString(senderMerchant)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    couponState: ").append(toIndentedString(couponState)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
