// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** ModifyBudgetResponse */
public class ModifyBudgetResponse {
  /** 배치 현재 최대 발송 개수 설명: 배치 최대 발송 개수 */
  @SerializedName("max_coupons")
  private Long maxCoupons;

  /** 현재 단일 일자 발송 상한선 개수 설명: 현재 단일 일자 발송 상한선 개수 */
  @SerializedName("max_coupons_by_day")
  private Long maxCouponsByDay;

  public Long getMaxCoupons() {
    return maxCoupons;
  }

  public void setMaxCoupons(Long maxCoupons) {
    this.maxCoupons = maxCoupons;
  }

  public Long getMaxCouponsByDay() {
    return maxCouponsByDay;
  }

  public void setMaxCouponsByDay(Long maxCouponsByDay) {
    this.maxCouponsByDay = maxCouponsByDay;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyBudgetResponse {\n");
    sb.append("    maxCoupons: ").append(toIndentedString(maxCoupons)).append("\n");
    sb.append("    maxCouponsByDay: ").append(toIndentedString(maxCouponsByDay)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
