// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** ModifyMiniAppInfo */
public class ModifyMiniAppInfo {
  /** 가맹점 미니프로그램 AppID 설명:미니프로그램 AppID가 소속 가맹점 번호와 바인딩 관계 필요 */
  @SerializedName("mini_programs_appid")
  private String miniProgramsAppid;

  /** 가맹점 미니프로그램 path 설명:가맹점 미니프로그램 path */
  @SerializedName("mini_programs_path")
  private String miniProgramsPath;

  /** 입구 문구 설명:입구 문구，글자 수 상한선 5자, 한자/영문/숫자 각각 1자로 계산。 */
  @SerializedName("entrance_words")
  private String entranceWords;

  /** 안내 문구 설명: 미니프로그램 입구 안내 문구, 글자 수 상한선 6자, 한자/영문/숫자 각각 1자로 계산. */
  @SerializedName("guiding_words")
  private String guidingWords;

  public String getMiniProgramsAppid() {
    return miniProgramsAppid;
  }

  public void setMiniProgramsAppid(String miniProgramsAppid) {
    this.miniProgramsAppid = miniProgramsAppid;
  }

  public String getMiniProgramsPath() {
    return miniProgramsPath;
  }

  public void setMiniProgramsPath(String miniProgramsPath) {
    this.miniProgramsPath = miniProgramsPath;
  }

  public String getEntranceWords() {
    return entranceWords;
  }

  public void setEntranceWords(String entranceWords) {
    this.entranceWords = entranceWords;
  }

  public String getGuidingWords() {
    return guidingWords;
  }

  public void setGuidingWords(String guidingWords) {
    this.guidingWords = guidingWords;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifyMiniAppInfo {\n");
    sb.append("    miniProgramsAppid: ").append(toIndentedString(miniProgramsAppid)).append("\n");
    sb.append("    miniProgramsPath: ").append(toIndentedString(miniProgramsPath)).append("\n");
    sb.append("    entranceWords: ").append(toIndentedString(entranceWords)).append("\n");
    sb.append("    guidingWords: ").append(toIndentedString(guidingWords)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
