// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** NotifyConfig */
public class NotifyConfig {
  /**
   * 이벤트 알림 AppID
   * 설명: 콜백 알림 시, 작업 사용자의 OpenID(예: 쿠폰 수령 사용자)를 계산하여 반환, 미니프로그램 또는 공개 계정의 AppID 지원; 이 필드를 기입하지 않으면, 콜백 알림에서 사용자 신원 정보와 관련된 OpenID와 UnionID가 모두 비어있음.
   */
  @SerializedName("notify_appid")
  private String notifyAppid;

  public String getNotifyAppid() {
    return notifyAppid;
  }

  public void setNotifyAppid(String notifyAppid) {
    this.notifyAppid = notifyAppid;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotifyConfig {\n");
    sb.append("    notifyAppid: ").append(toIndentedString(notifyAppid)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
