// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** PayReceiptListRequest */
public class PayReceiptListRequest {
  /** 가맹점 쿠폰 배치 번호 설명: 위챗페이가 생성, 가맹점 쿠폰 생성 API 호출 성공 시 반환되는 고유 배치 ID */
  @SerializedName("stock_id")
  @Expose(serialize = false)
  private String stockId;

  /**
   * 가맹점 쿠폰 code 설명: 쿠폰의 고유 식별자. WECHATPAY\\_MODE 쿠폰 code 모드에서, 가맹점 쿠폰 code는 위챗페이가 생성한 고유 ID;
   * MERCHANT\\_UPLOAD, MERCHANT\\_API 쿠폰 code 모드에서, 가맹점 쿠폰 code는 가맹점이 업로드하거나 지정하며, 배치 하에서 고유성 보장;
   */
  @SerializedName("coupon_code")
  @Expose(serialize = false)
  private String couponCode;

  /** 보조금 결제 요청 내역 번호 설명: 가맹점이 보조금 결제 API 호출 시 기입한 "업무 요청 고유 내역 번호" */
  @SerializedName("out_subsidy_no")
  @Expose(serialize = false)
  private String outSubsidyNo;

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getOutSubsidyNo() {
    return outSubsidyNo;
  }

  public void setOutSubsidyNo(String outSubsidyNo) {
    this.outSubsidyNo = outSubsidyNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayReceiptListRequest {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    outSubsidyNo: ").append(toIndentedString(outSubsidyNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
