// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** QueryCouponRequest */
public class QueryCouponRequest {
  /** 쿠폰 code 설명: 쿠폰의 고유 식별자 */
  @SerializedName("coupon_code")
  @Expose(serialize = false)
  private String couponCode;

  /**
   * 공개 계정 ID 설명: 현재 호출 인터페이스 가맹점 번호와 바인딩 관계가 있는 AppID 전달 지원. 미니프로그램 AppID와 공개 계정 AppID 지원.
   * 검증 규칙: 전달한 AppID는 호출 측 가맹점 번호(즉, 요청 헤더 내 가맹점 번호)와 바인딩 관계가 있는 AppID이거나, 전달한 AppID는 소속 가맹점 번호와 바인딩 관계가 있는 AppID여야 함
   */
  @SerializedName("appid")
  @Expose(serialize = false)
  private String appid;

  /**
   * 사용자 OpenID 설명: OpenID 정보, 사용자가 AppID 하의 고유 식별자.
   * 검증 규칙: 전달한 OpenID는 호출 측 가맹점 번호(즉, 요청 헤더 내 가맹점 번호)와 바인딩 관계가 있는 AppID에서 획득한 OpenID이거나, 전달한 OpenID는 소속 가맹점 번호와 바인딩 관계가 있는 AppID에서 획득한 OpenID여야 합니다. [OpenID 획득 문서](https://pay.weixin.qq.com/wiki/doc/apiv3/terms_definition/chapter1_1_3.shtml#part-3)
   */
  @SerializedName("openid")
  @Expose(serialize = false)
  private String openid;

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryCouponRequest {\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
