// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** ReturnReceiptInfoRequest */
public class ReturnReceiptInfoRequest {
  /** 보조금 환불 내역 번호 설명:보조금 환불 고유 내역 번호，위챗페이가 생성，보조금 환불 성공 후에만 반환 */
  @SerializedName("subsidy_return_receipt_id")
  @Expose(serialize = false)
  private String subsidyReturnReceiptId;

  public String getSubsidyReturnReceiptId() {
    return subsidyReturnReceiptId;
  }

  public void setSubsidyReturnReceiptId(String subsidyReturnReceiptId) {
    this.subsidyReturnReceiptId = subsidyReturnReceiptId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnReceiptInfoRequest {\n");
    sb.append("    subsidyReturnReceiptId: ")
        .append(toIndentedString(subsidyReturnReceiptId))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }
}
