// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** SendCouponResult */
public class SendCouponResult {
  /** 배치 번호 설명:위챗페이 쿠폰 배치 ID */
  @SerializedName("stock_id")
  private String stockId;

  /** 쿠폰 발송 증빙 설명:쿠폰 발송 증빙，영문, 숫자, ｜, _, *, - 등을 포함할 수 있으며, 기타 불법 기호는 허용되지 않음，단일 배치 단일 사용자 하에서 고유성 보장 필요 */
  @SerializedName("out_request_no")
  private String outRequestNo;

  /** 쿠폰 code 설명: 쿠폰의 고유 식별자 */
  @SerializedName("coupon_code")
  private String couponCode;

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getOutRequestNo() {
    return outRequestNo;
  }

  public void setOutRequestNo(String outRequestNo) {
    this.outRequestNo = outRequestNo;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendCouponResult {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    outRequestNo: ").append(toIndentedString(outRequestNo)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
