// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** StockGetResponse */
public class StockGetResponse {
  /** 商家券批次名称 설명:배치 이름, 글자 수 상한선 21자, 한자/영문/숫자 각각 1자로 계산. */
  @SerializedName("stock_name")
  private String stockName;

  /** 배치 소속 가맹점 번호 설명: 배치가 어느 가맹점에 속하는지 참고: 일반 직접 연결 모드, 이 매개변수는 직접 연결 가맹점 번호. 서비스 제공업체 모드, 이 매개변수는 하위 가맹점 번호. 간접 연결 모드, 이 매개변수는 하위 가맹점 번호. */
  @SerializedName("belong_merchant")
  private String belongMerchant;

  /** 批次备注 설명:가맹점에만 표시되며, 사용자 정의 정보에 사용. 글자 수 상한선 20자, 한자/영문/숫자 각각 1자로 계산. */
  @SerializedName("comment")
  private String comment;

  /** 적용 상품 범위 설명: 배치가 어떤 상품에서 사용 가능한지 설명하며, 위챗 카드 지갑에 표시됩니다. 글자 수 상한선 15자, 한자/영문/숫자 각각 1자로 계산. */
  @SerializedName("goods_name")
  private String goodsName;

  /** 배치 유형 설명: 배치 유형 */
  @SerializedName("stock_type")
  private BusiFavorStockType stockType;

  /** 사용 규칙 설명: 사용 규칙 */
  @SerializedName("coupon_use_rule")
  private CouponUseRule couponUseRule;

  /** 발송 규칙 설명: 발송 규칙 */
  @SerializedName("stock_send_rule")
  private StockSendRule stockSendRule;

  /** 自定义入口 설명:카드 상세 페이지, 여러 입구를 선택하여 사용자 유도 가능 */
  @SerializedName("custom_entrance")
  private CustomEntrance customEntrance;

  /** 스타일 정보 설명: 배치 생성 시의 스타일 정보 */
  @SerializedName("display_pattern_info")
  private DisplayPatternInfo displayPatternInfo;

  /** 배치 상태 설명: 배치 상태 */
  @SerializedName("stock_state")
  private StockStatus stockState;

  /** 쿠폰 code 모드 설명: 쿠폰 code 모드 */
  @SerializedName("coupon_code_mode")
  private CouponCodeMode couponCodeMode;

  /** 배치 번호 설명: 배치 고유 식별자 */
  @SerializedName("stock_id")
  private String stockId;

  /**
   * 쿠폰 code 수량
   * 설명: coupon_code_mode(쿠폰 code 모드)가 MERCHANT_UPLOAD(가맹점 업로드 사용자 정의 code) 모드일 때만 이 필드를 반환. 반환 내용은 가맹점이 업로드한 code의 수량 정보
   */
  @SerializedName("coupon_code_count")
  private CouponCodeCount couponCodeCount;

  /** 事件通知配置 설명:이벤트 콜백 알림 가맹점 설정 */
  @SerializedName("notify_config")
  private NotifyConfig notifyConfig;

  /** 배치 발송 상황 설명: 배치 발송 상황 */
  @SerializedName("send_count_information")
  private SendCount sendCountInformation;

  /** 是否允许营销补差 설명:该批次发放的券是否允许进行补差 참고: 해당 필드는 아직 미개방 */
  @SerializedName("subsidy")
  private Boolean subsidy;

  public String getStockName() {
    return stockName;
  }

  public void setStockName(String stockName) {
    this.stockName = stockName;
  }

  public String getBelongMerchant() {
    return belongMerchant;
  }

  public void setBelongMerchant(String belongMerchant) {
    this.belongMerchant = belongMerchant;
  }

  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public String getGoodsName() {
    return goodsName;
  }

  public void setGoodsName(String goodsName) {
    this.goodsName = goodsName;
  }

  public BusiFavorStockType getStockType() {
    return stockType;
  }

  public void setStockType(BusiFavorStockType stockType) {
    this.stockType = stockType;
  }

  public CouponUseRule getCouponUseRule() {
    return couponUseRule;
  }

  public void setCouponUseRule(CouponUseRule couponUseRule) {
    this.couponUseRule = couponUseRule;
  }

  public StockSendRule getStockSendRule() {
    return stockSendRule;
  }

  public void setStockSendRule(StockSendRule stockSendRule) {
    this.stockSendRule = stockSendRule;
  }

  public CustomEntrance getCustomEntrance() {
    return customEntrance;
  }

  public void setCustomEntrance(CustomEntrance customEntrance) {
    this.customEntrance = customEntrance;
  }

  public DisplayPatternInfo getDisplayPatternInfo() {
    return displayPatternInfo;
  }

  public void setDisplayPatternInfo(DisplayPatternInfo displayPatternInfo) {
    this.displayPatternInfo = displayPatternInfo;
  }

  public StockStatus getStockState() {
    return stockState;
  }

  public void setStockState(StockStatus stockState) {
    this.stockState = stockState;
  }

  public CouponCodeMode getCouponCodeMode() {
    return couponCodeMode;
  }

  public void setCouponCodeMode(CouponCodeMode couponCodeMode) {
    this.couponCodeMode = couponCodeMode;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public CouponCodeCount getCouponCodeCount() {
    return couponCodeCount;
  }

  public void setCouponCodeCount(CouponCodeCount couponCodeCount) {
    this.couponCodeCount = couponCodeCount;
  }

  public NotifyConfig getNotifyConfig() {
    return notifyConfig;
  }

  public void setNotifyConfig(NotifyConfig notifyConfig) {
    this.notifyConfig = notifyConfig;
  }

  public SendCount getSendCountInformation() {
    return sendCountInformation;
  }

  public void setSendCountInformation(SendCount sendCountInformation) {
    this.sendCountInformation = sendCountInformation;
  }

  public Boolean getSubsidy() {
    return subsidy;
  }

  public void setSubsidy(Boolean subsidy) {
    this.subsidy = subsidy;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockGetResponse {\n");
    sb.append("    stockName: ").append(toIndentedString(stockName)).append("\n");
    sb.append("    belongMerchant: ").append(toIndentedString(belongMerchant)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    goodsName: ").append(toIndentedString(goodsName)).append("\n");
    sb.append("    stockType: ").append(toIndentedString(stockType)).append("\n");
    sb.append("    couponUseRule: ").append(toIndentedString(couponUseRule)).append("\n");
    sb.append("    stockSendRule: ").append(toIndentedString(stockSendRule)).append("\n");
    sb.append("    customEntrance: ").append(toIndentedString(customEntrance)).append("\n");
    sb.append("    displayPatternInfo: ").append(toIndentedString(displayPatternInfo)).append("\n");
    sb.append("    stockState: ").append(toIndentedString(stockState)).append("\n");
    sb.append("    couponCodeMode: ").append(toIndentedString(couponCodeMode)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCodeCount: ").append(toIndentedString(couponCodeCount)).append("\n");
    sb.append("    notifyConfig: ").append(toIndentedString(notifyConfig)).append("\n");
    sb.append("    sendCountInformation: ")
        .append(toIndentedString(sendCountInformation))
        .append("\n");
    sb.append("    subsidy: ").append(toIndentedString(subsidy)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
