// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** SubsidyReturnRequest */
public class SubsidyReturnRequest {
  /** 가맹점 쿠폰 배치 번호 설명: 위챗페이가 생성, 가맹점 쿠폰 생성 API 호출 성공 시 반환되는 고유 배치 ID. "만원 이상 할인 쿠폰"과 "할인 쿠폰" 배치만 지원, "교환 구매 쿠폰" 배치는 미지원 */
  @SerializedName("stock_id")
  private String stockId;

  /**
   * 가맹점 쿠폰 code 설명: 쿠폰의 고유 식별자. WECHATPAY\\_MODE 쿠폰 code 모드에서, 가맹점 쿠폰 code는 위챗페이가 생성한 고유 ID;
   * MERCHANT\\_UPLOAD, MERCHANT\\_API 쿠폰 code 모드에서, 가맹점 쿠폰 code는 가맹점이 업로드하거나 지정하며, 배치 하에서 고유성 보장;
   */
  @SerializedName("coupon_code")
  private String couponCode;

  /** 위챗페이 주문 번호 설명: 위챗페이 주문 결제 성공 시 반환되는 주문 번호 */
  @SerializedName("transaction_id")
  private String transactionId;

  /** 위챗페이 환불 내역 번호 설명: 위챗페이 환불 내역 번호 */
  @SerializedName("refund_id")
  private String refundId;

  /** 원래 마케팅 보조금 차감 가맹점 번호 설명: 원래 마케팅 보조금 차감 가맹점 번호, 즉 환불 자금 수취 가맹점 번호 */
  @SerializedName("payer_merchant")
  private String payerMerchant;

  /** 원래 마케팅 보조금 입금 가맹점 번호 설명: 원래 마케팅 보조금 입금 가맹점 번호, 즉 환불 자금 차감 가맹점 번호 */
  @SerializedName("payee_merchant")
  private String payeeMerchant;

  /** 보조금 환불 금액 설명: 이번 보조금 환불 금액, 단위는 전. 단일 쿠폰 Code 환불 총 금액은 보조금 금액을 초과할 수 없음 */
  @SerializedName("amount")
  private Long amount;

  /** 보조금 환불 설명 설명: 환불 비고 설명, 조회 시 그대로 반환됨 */
  @SerializedName("description")
  private String description;

  /** 업무 요청 고유 내역 번호 설명: 가맹점 측에서 고유성 보장 필요, 영문, 숫자, ｜, _, *, - 등을 포함할 수 있으며, 기타 불법 기호는 허용되지 않음 */
  @SerializedName("out_subsidy_return_no")
  private String outSubsidyReturnNo;

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public String getRefundId() {
    return refundId;
  }

  public void setRefundId(String refundId) {
    this.refundId = refundId;
  }

  public String getPayerMerchant() {
    return payerMerchant;
  }

  public void setPayerMerchant(String payerMerchant) {
    this.payerMerchant = payerMerchant;
  }

  public String getPayeeMerchant() {
    return payeeMerchant;
  }

  public void setPayeeMerchant(String payeeMerchant) {
    this.payeeMerchant = payeeMerchant;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getOutSubsidyReturnNo() {
    return outSubsidyReturnNo;
  }

  public void setOutSubsidyReturnNo(String outSubsidyReturnNo) {
    this.outSubsidyReturnNo = outSubsidyReturnNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubsidyReturnRequest {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    refundId: ").append(toIndentedString(refundId)).append("\n");
    sb.append("    payerMerchant: ").append(toIndentedString(payerMerchant)).append("\n");
    sb.append("    payeeMerchant: ").append(toIndentedString(payeeMerchant)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    outSubsidyReturnNo: ").append(toIndentedString(outSubsidyReturnNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
