// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** SubsidyReturnReceipt */
public class SubsidyReturnReceipt {
  /** 보조금 반환 내역 번호 설명: 보조금 반환 고유 내역 번호, 위챗페이가 생성하며, 보조금 반환 성공 후에만 반환 */
  @SerializedName("subsidy_return_receipt_id")
  private String subsidyReturnReceiptId;

  /** 가맹점 쿠폰 배치 번호 설명: 위챗페이가 생성하며, 가맹점 쿠폰 생성 API 호출 성공 시 반환되는 고유 배치 ID */
  @SerializedName("stock_id")
  private String stockId;

  /** 가맹점 쿠폰 code 설명: 쿠폰의 고유 식별자 */
  @SerializedName("coupon_code")
  private String couponCode;

  /** 위챗페이 주문 번호 설명: 위챗페이 주문 결제 성공 시 반환되는 주문 번호 */
  @SerializedName("transaction_id")
  private String transactionId;

  /** 위챗페이 환불 내역 번호 설명: 위챗페이 환불 내역 번호 */
  @SerializedName("refund_id")
  private String refundId;

  /** 원 마케팅 보조금 출금 가맹점 번호 설명: 원 마케팅 보조금 출금 가맹점 번호, 즉 반환 자금 수취 가맹점 번호 */
  @SerializedName("payer_merchant")
  private String payerMerchant;

  /** 원 마케팅 보조금 입금 가맹점 번호 설명: 원 마케팅 보조금 입금 가맹점 번호, 즉 반환 자금 출금 가맹점 번호 */
  @SerializedName("payee_merchant")
  private String payeeMerchant;

  /** 보조금 반환 금액 설명: 이번 보조금 반환 금액, 단위는 분. 단일 쿠폰 code 반환 총액은 보조금 금액을 초과할 수 없음 */
  @SerializedName("amount")
  private Long amount;

  /** 보조금 반환 설명 설명: 반환 비고 설명, 조회 시 그대로 반환 */
  @SerializedName("description")
  private String description;

  /** 보조금 반환 내역 상태 설명: 보조금 지급 내역 상태 */
  @SerializedName("status")
  private SubsidyReturnReceiptStatus status;

  /** 보조금 반환 실패 사유 설명: 보조금 반환 실패 시에만 반환되며, 해당 실패 사유를 알려줌 */
  @SerializedName("fail_reason")
  private SubsidyReturnReceiptFailReason failReason;

  /** 보조금 반환 완료 시간 설명: 보조금 반환 성공 시에만 반환되며, 완료 시간을 반환합니다 */
  @SerializedName("return_done_time")
  private String returnDoneTime;

  /** 보조금 지급 내역 번호 설명: 이번 보조금 반환 작업에 해당하는 보조금 지급 내역 번호 */
  @SerializedName("subsidy_receipt_id")
  private String subsidyReceiptId;

  /** 업무 요청 고유 내역 번호 설명: 가맹점 측에서 고유성 보장 필요. 영문, 숫자, |, _, *, - 등을 포함할 수 있으며, 기타 불법 기호는 허용되지 않음 */
  @SerializedName("out_subsidy_return_no")
  private String outSubsidyReturnNo;

  /** 보조금 반환 시작 시간 설명: 보조금 반환 내역 생성 시간 */
  @SerializedName("return_create_time")
  private String returnCreateTime;

  public String getSubsidyReturnReceiptId() {
    return subsidyReturnReceiptId;
  }

  public void setSubsidyReturnReceiptId(String subsidyReturnReceiptId) {
    this.subsidyReturnReceiptId = subsidyReturnReceiptId;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getCouponCode() {
    return couponCode;
  }

  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public String getRefundId() {
    return refundId;
  }

  public void setRefundId(String refundId) {
    this.refundId = refundId;
  }

  public String getPayerMerchant() {
    return payerMerchant;
  }

  public void setPayerMerchant(String payerMerchant) {
    this.payerMerchant = payerMerchant;
  }

  public String getPayeeMerchant() {
    return payeeMerchant;
  }

  public void setPayeeMerchant(String payeeMerchant) {
    this.payeeMerchant = payeeMerchant;
  }

  public Long getAmount() {
    return amount;
  }

  public void setAmount(Long amount) {
    this.amount = amount;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SubsidyReturnReceiptStatus getStatus() {
    return status;
  }

  public void setStatus(SubsidyReturnReceiptStatus status) {
    this.status = status;
  }

  public SubsidyReturnReceiptFailReason getFailReason() {
    return failReason;
  }

  public void setFailReason(SubsidyReturnReceiptFailReason failReason) {
    this.failReason = failReason;
  }

  public String getReturnDoneTime() {
    return returnDoneTime;
  }

  public void setReturnDoneTime(String returnDoneTime) {
    this.returnDoneTime = returnDoneTime;
  }

  public String getSubsidyReceiptId() {
    return subsidyReceiptId;
  }

  public void setSubsidyReceiptId(String subsidyReceiptId) {
    this.subsidyReceiptId = subsidyReceiptId;
  }

  public String getOutSubsidyReturnNo() {
    return outSubsidyReturnNo;
  }

  public void setOutSubsidyReturnNo(String outSubsidyReturnNo) {
    this.outSubsidyReturnNo = outSubsidyReturnNo;
  }

  public String getReturnCreateTime() {
    return returnCreateTime;
  }

  public void setReturnCreateTime(String returnCreateTime) {
    this.returnCreateTime = returnCreateTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubsidyReturnReceipt {\n");
    sb.append("    subsidyReturnReceiptId: ")
        .append(toIndentedString(subsidyReturnReceiptId))
        .append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    refundId: ").append(toIndentedString(refundId)).append("\n");
    sb.append("    payerMerchant: ").append(toIndentedString(payerMerchant)).append("\n");
    sb.append("    payeeMerchant: ").append(toIndentedString(payeeMerchant)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    failReason: ").append(toIndentedString(failReason)).append("\n");
    sb.append("    returnDoneTime: ").append(toIndentedString(returnDoneTime)).append("\n");
    sb.append("    subsidyReceiptId: ").append(toIndentedString(subsidyReceiptId)).append("\n");
    sb.append("    outSubsidyReturnNo: ").append(toIndentedString(outSubsidyReturnNo)).append("\n");
    sb.append("    returnCreateTime: ").append(toIndentedString(returnCreateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
