// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/** UploadCouponCodeBody */
public class UploadCouponCodeBody {
  /**
   * 쿠폰 code 목록 설명: 가맹점이 업로드한 쿠폰 code 목록; code에 포함 가능한 문자 0-9 a-z A-Z 공백(공백만 포함, 탭, 줄바꿈, 페이지 나눔 등은 포함하지 않음) 중간선- 밑줄_ 백슬래시\\ 슬래시/
   * 등호= 세로선|
   */
  @SerializedName("coupon_code_list")
  private List<String> couponCodeList = new ArrayList<String>();

  /** 요청 업무 증빙 번호 설명: 가맹점이 code를 업로드한 증빙 번호, 가맹점 측에서 고유성 유지 필요 */
  @SerializedName("upload_request_no")
  private String uploadRequestNo;

  public List<String> getCouponCodeList() {
    return couponCodeList;
  }

  public void setCouponCodeList(List<String> couponCodeList) {
    this.couponCodeList = couponCodeList;
  }

  public String getUploadRequestNo() {
    return uploadRequestNo;
  }

  public void setUploadRequestNo(String uploadRequestNo) {
    this.uploadRequestNo = uploadRequestNo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UploadCouponCodeBody {\n");
    sb.append("    couponCodeList: ").append(toIndentedString(couponCodeList)).append("\n");
    sb.append("    uploadRequestNo: ").append(toIndentedString(uploadRequestNo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
