// Copyright 2021 Tencent Inc. All rights reserved.
//
// 마케팅 가맹점 쿠폰 대외 API
//
// No description provided (generated by Openapi Generator
// https://github.com/openapitools/openapi-generator)
//
// API version: 0.0.11

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.merchantexclusivecoupon.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** UseCouponResponse */
public class UseCouponResponse {
  /** 배치 번호 설명:배치 ID */
  @SerializedName("stock_id")
  private String stockId;

  /** 사용자 식별자 설명:해당 공개 계정 내 사용자 고유 신원 식별자。 */
  @SerializedName("openid")
  private String openid;

  /**
   * 시스템 쿠폰 사용 성공 시간
   * 설명:시스템이 쿠폰 사용에 성공한 시간，[rfc3339](https://datatracker.ietf.org/doc/html/rfc3339) 표준 형식 준수, 형식은 yyyy-MM-DDTHH:mm:ss+TIMEZONE이며, yyyy-MM-DD는 년월일을 나타내고, T는 문자열에 나타나며 time 요소의 시작을 나타내고, HH:mm:ss는 시분초를 나타내며, TIMEZONE은 시간대를 나타냅니다(+08:00는 동부 8구 시간, UTC보다
   * 8시간 앞서며, 즉 베이징 시간). 예: 2015-05-20T13:29:35+08:00는 베이징 시간 2015년 5월 20일 13시 29분 35초를 나타냅니다.
   */
  @SerializedName("wechatpay_use_time")
  private String wechatpayUseTime;

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getWechatpayUseTime() {
    return wechatpayUseTime;
  }

  public void setWechatpayUseTime(String wechatpayUseTime) {
    this.wechatpayUseTime = wechatpayUseTime;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UseCouponResponse {\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    wechatpayUseTime: ").append(toIndentedString(wechatpayUseTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
