// Copyright 2021 Tencent Inc. All rights reserved.
//
// 전자상거래 환불 API
//
// 국내 전자상거래 환불 기능 관련 API 문서
//
// API version: 1.1.8

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommercerefund.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** CreateRefundRequest */
public class CreateRefundRequest {
  /** 하위 가맹점 번호 설명: 위챗페이가 할당한 하위 가맹점의 가맹점 번호 */
  @SerializedName("sub_mchid")
  private String subMchid;

  /** 전자상거래 플랫폼 APPID 설명: 전자상거래 플랫폼이 위챗 공개 플랫폼에서 신청한 서비스 계정에 대응하는 APPID, 가맹점 기능 신청 시 위챗페이가 바인딩 관계를 구성함 */
  @SerializedName("sp_appid")
  private String spAppid;

  /** 하위 가맹점 APPID 설명: 하위 가맹점이 위챗에서 공개 계정 신청 성공 후 할당받은 계정 ID, 전자상거래 플랫폼 측에 바인딩 관계 구성이 있어야 전달 가능 */
  @SerializedName("sub_appid")
  private String subAppid;

  /** 위챗 주문 번호 설명: 원래 결제 거래에 대응하는 위챗 주문 번호 */
  @SerializedName("transaction_id")
  private String transactionId;

  /** 가맹점 주문 번호 설명: 원래 결제 거래에 대응하는 가맹점 주문 번호 */
  @SerializedName("out_trade_no")
  private String outTradeNo;

  /** 가맹점 환불 내역 번호 설명: 가맹점 시스템 내부의 환불 내역 번호, 가맹점 시스템 내부에서 고유함, 숫자, 대소문자 영문, _, -, |, *, @만 가능, 동일 환불 내역 번호로 여러 번 요청해도 한 건만 환불됨. */
  @SerializedName("out_refund_no")
  private String outRefundNo;

  /** 환불 사유 설명: 가맹점이 전달하면, 사용자에게 전달되는 환불 메시지에 환불 사유가 표시됨 */
  @SerializedName("reason")
  private String reason;

  /** 주문 금액 설명: 주문 금액 정보 */
  @SerializedName("amount")
  private RefundReqAmount amount;

  /**
   * 환불 결과 콜백 url 설명: 비동기로 위챗페이 환불 결과 알림을 수신하는 콜백 주소, 알림 url은 외부 네트워크에서 접근 가능한 url이어야 하며, 매개변수를 포함할 수 없음.
   * 매개변수에 notify_url을 전달한 경우, 가맹점 플랫폼에 구성된 콜백 주소는 적용되지 않으며, 현재 전달한 주소를 우선적으로 콜백함.
   */
  @SerializedName("notify_url")
  private String notifyUrl;

  /**
   * 환불 출자 가맹점 설명: REFUND_SOURCE_PARTNER_ADVANCE: 전자상거래 플랫폼 선불, 위챗페이에 신청하여 개설 필요 REFUND_SOURCE_SUB_MERCHANT:
   * 하위 가맹점, 기본값 참고: REFUND_SOURCE_PARTNER_ADVANCE를 전달한 경우, 선불 환불 사용 가능을 의미할 뿐이며, 실제 출금 계정은 환불 신청 접수 결과 또는 주문 조회 결과를 기준으로 함.
   */
  @SerializedName("refund_account")
  private String refundAccount;

  /**
   * 자금 계정
   * 설명: 주문이 분할 대기 상태인 경우, 이 매개변수를 전달하여 환불 자금 출처 계정을 지정할 수 있음. 이 필드가 없는 경우, 기본적으로 주문 거래 자금이 있는 계정에서 출금하며, 즉 분할 대기 시 사용 불가 잔액의 자금으로 환불하고, 분할 완료 또는 분할 없음 시 사용 가능 잔액의 자금으로 환불함.
   * AVAILABLE: 사용 가능 잔액
   */
  @SerializedName("funds_account")
  private String fundsAccount;

  public String getSubMchid() {
    return subMchid;
  }

  public void setSubMchid(String subMchid) {
    this.subMchid = subMchid;
  }

  public String getSpAppid() {
    return spAppid;
  }

  public void setSpAppid(String spAppid) {
    this.spAppid = spAppid;
  }

  public String getSubAppid() {
    return subAppid;
  }

  public void setSubAppid(String subAppid) {
    this.subAppid = subAppid;
  }

  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public String getOutTradeNo() {
    return outTradeNo;
  }

  public void setOutTradeNo(String outTradeNo) {
    this.outTradeNo = outTradeNo;
  }

  public String getOutRefundNo() {
    return outRefundNo;
  }

  public void setOutRefundNo(String outRefundNo) {
    this.outRefundNo = outRefundNo;
  }

  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public RefundReqAmount getAmount() {
    return amount;
  }

  public void setAmount(RefundReqAmount amount) {
    this.amount = amount;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }

  public String getRefundAccount() {
    return refundAccount;
  }

  public void setRefundAccount(String refundAccount) {
    this.refundAccount = refundAccount;
  }

  public String getFundsAccount() {
    return fundsAccount;
  }

  public void setFundsAccount(String fundsAccount) {
    this.fundsAccount = fundsAccount;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRefundRequest {\n");
    sb.append("    subMchid: ").append(toIndentedString(subMchid)).append("\n");
    sb.append("    spAppid: ").append(toIndentedString(spAppid)).append("\n");
    sb.append("    subAppid: ").append(toIndentedString(subAppid)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    outTradeNo: ").append(toIndentedString(outTradeNo)).append("\n");
    sb.append("    outRefundNo: ").append(toIndentedString(outRefundNo)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("    refundAccount: ").append(toIndentedString(refundAccount)).append("\n");
    sb.append("    fundsAccount: ").append(toIndentedString(fundsAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
