// Copyright 2021 Tencent Inc. All rights reserved.
//
// 전자상거래 환불 API
//
// 국내 전자상거래 환불 기능 관련 API 문서
//
// API version: 1.1.8

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommercerefund.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** RefundReqAmount */
public class RefundReqAmount {
  /** 환불 금액 설명: 환불 금액, 통화의 최소 단위, 정수만 가능, 원 주문 결제 금액을 초과할 수 없음. */
  @SerializedName("refund")
  private Long refund;

  /**
   * 환불 출자 계정 및 금액 설명: 환불이 지정 계정에서 출자해야 할 때, 이 매개변수를 전달하여 출자 금액을 지정함(통화의 최소 단위, 정수만 가능).
   * 이 기능은 자금 계정(funds_account) 매개변수를 통해 사용 가능 잔액 출자 환불 기능을 지정하는 것보다 우선순위가 높으며, 둘은 동시에 사용할 수 없음.
   * 여러 계정 출자 환불을 동시에 지정하는 사용 시나리오는 다음 조건을 만족해야 함: 1, 환불 지출 분리 제품 기능 미개설; 2, 전자상거래 플랫폼 선불 환불 아님; 3, 주문이 분할 주문에 속하며, 분할이 분할 대기 또는 분할 중 상태.
   * 매개변수 전달은 다음 조건을 만족해야 함: 1, 기본 계정 사용 가능 잔액 출자 금액과 기본 계정 사용 불가 잔액 출자 금액의 합이 환불 금액과 같음; 2, 계정 유형은 중복될 수 없음. 위 조건 중 하나라도 만족하지 않으면 오류 반환
   */
  @SerializedName("from")
  private List<FundsFromItem> from;

  /** 원 주문 금액 설명: 원래 결제 거래의 주문 총 금액, 통화의 최소 단위, 정수만 가능 */
  @SerializedName("total")
  private Long total;

  /** 환불 통화 설명: ISO 4217 표준에 부합하는 3자리 영문 코드, 현재는 인민폐만 지원: CNY */
  @SerializedName("currency")
  private String currency;

  public Long getRefund() {
    return refund;
  }

  public void setRefund(Long refund) {
    this.refund = refund;
  }

  public List<FundsFromItem> getFrom() {
    return from;
  }

  public void setFrom(List<FundsFromItem> from) {
    this.from = from;
  }

  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }

  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundReqAmount {\n");
    sb.append("    refund: ").append(toIndentedString(refund)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
