// Copyright 2021 Tencent Inc. All rights reserved.
//
// 전자상거래 환불 API
//
// 국내 전자상거래 환불 기능 관련 API 문서
//
// API version: 1.1.8

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.ecommercerefund.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** Refund4Create */
public class Refund4Create {
  /** 위챗페이 환불 주문 번호 설명: 위챗페이 환불 주문 번호 */
  @SerializedName("refund_id")
  private String refundId;

  /** 가맹점 환불 내역 번호 설명: 가맹점 시스템 내부의 환불 내역 번호, 가맹점 시스템 내부에서 고유함, 숫자, 대소문자 영문, _, -, |, *, @만 가능, 동일 환불 내역 번호로 여러 번 요청해도 한 건만 환불됨. */
  @SerializedName("out_refund_no")
  private String outRefundNo;

  /**
   * 환불 생성 시간
   * 설명: 환불 접수 시간, rfc3339 표준 형식을 따름, 형식은 YYYY-MM-DDTHH:mm:ss+TIMEZONE, YYYY-MM-DD는 년월일을 나타내고, T는 문자열에 나타나며 time 요소의 시작을 나타내고, HH:mm:ss는 시분초를 나타내며, TIMEZONE은 시간대를 나타냄(+08:00은 동부 8구 시간을 나타내며 UTC보다
   * 8시간 앞서며, 즉 베이징 시간). 예: 2015-05-20T13:29:35+08:00은 베이징 시간 2015년 5월 20일 13시 29분 35초를 나타냄.
   */
  @SerializedName("create_time")
  private String createTime;

  /** 환불 금액 설명: 주문 환불 금액 정보 */
  @SerializedName("amount")
  private RefundAmount amount;

  /** 할인 환불 상세 설명: 할인 환불 기능 정보 */
  @SerializedName("promotion_detail")
  private List<PromotionDetail> promotionDetail;

  /**
   * 환불 출자 가맹점 설명: REFUND_SOURCE_PARTNER_ADVANCE: 전자상거래 플랫폼 선불 REFUND_SOURCE_SUB_MERCHANT: 하위 가맹점, 기본값
   * 참고: 환불 신청 시 아직 환불 자금이 차감되지 않은 경우가 있을 수 있으며, 이 경우 본 필드를 반환하지 않으며, 주문 조회로 확인해야 함.
   */
  @SerializedName("refund_account")
  private String refundAccount;

  public String getRefundId() {
    return refundId;
  }

  public void setRefundId(String refundId) {
    this.refundId = refundId;
  }

  public String getOutRefundNo() {
    return outRefundNo;
  }

  public void setOutRefundNo(String outRefundNo) {
    this.outRefundNo = outRefundNo;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public RefundAmount getAmount() {
    return amount;
  }

  public void setAmount(RefundAmount amount) {
    this.amount = amount;
  }

  public List<PromotionDetail> getPromotionDetail() {
    return promotionDetail;
  }

  public void setPromotionDetail(List<PromotionDetail> promotionDetail) {
    this.promotionDetail = promotionDetail;
  }

  public String getRefundAccount() {
    return refundAccount;
  }

  public void setRefundAccount(String refundAccount) {
    this.refundAccount = refundAccount;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Refund4Create {\n");
    sb.append("    refundId: ").append(toIndentedString(refundId)).append("\n");
    sb.append("    outRefundNo: ").append(toIndentedString(outRefundNo)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    promotionDetail: ").append(toIndentedString(promotionDetail)).append("\n");
    sb.append("    refundAccount: ").append(toIndentedString(refundAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
