// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;

/** CardLimitation */
public class CardLimitation {
  /** 지정 은행 카드 이름 설명: 배치에서 결제 방식을 은행 카드로 지정하고 지정 은행 카드 정보를 설정한 경우, 이 필드는 필수이며 최대 4자의 한자 문자. 위챗페이 결제 창에 사용자에게 표시됨. */
  @SerializedName("name")
  private String name;

  /** 지정 은행 카드 BIN 설명: 배치에서 결제 방식을 은행 카드로 지정하고 지정 은행 카드 정보를 설정한 경우, 이 필드는 필수이며 json 형식. 특수 규칙: 단일 카드 BIN의 문자 길이는 [6, 9], 항목 개수 제한은 [1, 10] */
  @SerializedName("bin")
  private List<String> bin = new ArrayList<String>();

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public List<String> getBin() {
    return bin;
  }

  public void setBin(List<String> bin) {
    this.bin = bin;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardLimitation {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bin: ").append(toIndentedString(bin)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
