// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** Coupon */
public class Coupon {
  /** 배치 생성 방 가맹점 번호 설명: 위챗페이가 생성 방 가맹점에 할당한 가맹점 번호 */
  @SerializedName("stock_creator_mchid")
  private String stockCreatorMchid;

  /** 배치 번호 설명: 배치 ID */
  @SerializedName("stock_id")
  private String stockId;

  /** 단일 상품 할인 특정 정보 설명: 단일 상품 할인 특정 정보 */
  @SerializedName("cut_to_message")
  private CutTypeMsg cutToMessage;

  /** 대금권 이름 설명: 대금권 이름 */
  @SerializedName("coupon_name")
  private String couponName;

  /** 대금권 상태 설명: 대금권 상태: SENDED-사용 가능, USED-실제 차감됨, EXPIRED-만료됨 */
  @SerializedName("status")
  private String status;

  /** 사용 설명 설명: 대금권 설명 필드 */
  @SerializedName("description")
  private String description;

  /** 쿠폰 수령 시간 설명: 쿠폰 수령 시간 */
  @SerializedName("create_time")
  private String createTime;

  /** 쿠폰 유형 설명: NORMAL-만원 이상 할인 쿠폰; CUT_TO-할인액까지 쿠폰 */
  @SerializedName("coupon_type")
  private String couponType;

  /** 자금 흐름 없음 여부 설명: true-예; false-아니오 */
  @SerializedName("no_cash")
  private Boolean noCash;

  /** 사용 가능 시작 시간 설명: 사용 가능 시작 시간 */
  @SerializedName("available_begin_time")
  private String availableBeginTime;

  /** 사용 가능 종료 시간 설명: 사용 가능 종료 시간 */
  @SerializedName("available_end_time")
  private String availableEndTime;

  /** 단일 상품 할인 여부 설명: TRUE-예; FALSE-아니오 */
  @SerializedName("singleitem")
  private Boolean singleitem;

  /** 만원 이상 할인 쿠폰 정보 설명: 일반 만원 이상 할인 쿠폰 액면가, 최소 금액 정보 */
  @SerializedName("normal_coupon_information")
  private FixedValueStockMsg normalCouponInformation;

  public String getStockCreatorMchid() {
    return stockCreatorMchid;
  }

  public void setStockCreatorMchid(String stockCreatorMchid) {
    this.stockCreatorMchid = stockCreatorMchid;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public CutTypeMsg getCutToMessage() {
    return cutToMessage;
  }

  public void setCutToMessage(CutTypeMsg cutToMessage) {
    this.cutToMessage = cutToMessage;
  }

  public String getCouponName() {
    return couponName;
  }

  public void setCouponName(String couponName) {
    this.couponName = couponName;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public String getCouponType() {
    return couponType;
  }

  public void setCouponType(String couponType) {
    this.couponType = couponType;
  }

  public Boolean getNoCash() {
    return noCash;
  }

  public void setNoCash(Boolean noCash) {
    this.noCash = noCash;
  }

  public String getAvailableBeginTime() {
    return availableBeginTime;
  }

  public void setAvailableBeginTime(String availableBeginTime) {
    this.availableBeginTime = availableBeginTime;
  }

  public String getAvailableEndTime() {
    return availableEndTime;
  }

  public void setAvailableEndTime(String availableEndTime) {
    this.availableEndTime = availableEndTime;
  }

  public Boolean getSingleitem() {
    return singleitem;
  }

  public void setSingleitem(Boolean singleitem) {
    this.singleitem = singleitem;
  }

  public FixedValueStockMsg getNormalCouponInformation() {
    return normalCouponInformation;
  }

  public void setNormalCouponInformation(FixedValueStockMsg normalCouponInformation) {
    this.normalCouponInformation = normalCouponInformation;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coupon {\n");
    sb.append("    stockCreatorMchid: ").append(toIndentedString(stockCreatorMchid)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    cutToMessage: ").append(toIndentedString(cutToMessage)).append("\n");
    sb.append("    couponName: ").append(toIndentedString(couponName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    couponType: ").append(toIndentedString(couponType)).append("\n");
    sb.append("    noCash: ").append(toIndentedString(noCash)).append("\n");
    sb.append("    availableBeginTime: ").append(toIndentedString(availableBeginTime)).append("\n");
    sb.append("    availableEndTime: ").append(toIndentedString(availableEndTime)).append("\n");
    sb.append("    singleitem: ").append(toIndentedString(singleitem)).append("\n");
    sb.append("    normalCouponInformation: ")
        .append(toIndentedString(normalCouponInformation))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }
}
