// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** FavorAvailableTime */
public class FavorAvailableTime {
  /** 고정 시간대 사용 가능 설명: 고정 시간대 사용 가능 */
  @SerializedName("fix_available_time")
  private FixedAvailableTime fixAvailableTime;

  /** 수령 후 다음 날 유효 설명: true-예; false-아니오 */
  @SerializedName("second_day_available")
  private Boolean secondDayAvailable;

  /** 수령 후 유효 시간 설명: 수령 후 유효 시간, 단위 분 */
  @SerializedName("available_time_after_receive")
  private Integer availableTimeAfterReceive;

  public FixedAvailableTime getFixAvailableTime() {
    return fixAvailableTime;
  }

  public void setFixAvailableTime(FixedAvailableTime fixAvailableTime) {
    this.fixAvailableTime = fixAvailableTime;
  }

  public Boolean getSecondDayAvailable() {
    return secondDayAvailable;
  }

  public void setSecondDayAvailable(Boolean secondDayAvailable) {
    this.secondDayAvailable = secondDayAvailable;
  }

  public Integer getAvailableTimeAfterReceive() {
    return availableTimeAfterReceive;
  }

  public void setAvailableTimeAfterReceive(Integer availableTimeAfterReceive) {
    this.availableTimeAfterReceive = availableTimeAfterReceive;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FavorAvailableTime {\n");
    sb.append("    fixAvailableTime: ").append(toIndentedString(fixAvailableTime)).append("\n");
    sb.append("    secondDayAvailable: ").append(toIndentedString(secondDayAvailable)).append("\n");
    sb.append("    availableTimeAfterReceive: ")
        .append(toIndentedString(availableTimeAfterReceive))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }
}
