// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** FixedValueStockMsg */
public class FixedValueStockMsg {
  /** 액면가 설명: 액면가, 단위 분 */
  @SerializedName("coupon_amount")
  private Long couponAmount;

  /** 최소 금액 설명: 쿠폰 사용 금액 최소 금액, 단위 분 */
  @SerializedName("transaction_minimum")
  private Long transactionMinimum;

  public Long getCouponAmount() {
    return couponAmount;
  }

  public void setCouponAmount(Long couponAmount) {
    this.couponAmount = couponAmount;
  }

  public Long getTransactionMinimum() {
    return transactionMinimum;
  }

  public void setTransactionMinimum(Long transactionMinimum) {
    this.transactionMinimum = transactionMinimum;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FixedValueStockMsg {\n");
    sb.append("    couponAmount: ").append(toIndentedString(couponAmount)).append("\n");
    sb.append("    transactionMinimum: ").append(toIndentedString(transactionMinimum)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
