// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** ListCouponsByFilterRequest */
public class ListCouponsByFilterRequest {
  /** 사용자 식별자 설명: 사용자가 가맹점 appid 하에서의 고유 식별자 */
  @SerializedName("openid")
  @Expose(serialize = false)
  private String openid;

  /**
   * 공개 계정 ID
   * 설명: 위챗페이가 쿠폰 발급 방 가맹점에 할당한 공개 계정 ID, 인터페이스에 전달하는 모든 appid는 공개 계정의 appid여야 함(mp.weixin.qq.com에서 신청한 것), APP의 appid는 안 됨(open.weixin.qq.com에서 신청한 것).
   */
  @SerializedName("appid")
  @Expose(serialize = false)
  private String appid;

  /** 배치 번호 설명: 배치 번호, 배치 번호 지정 조회 여부, available_mchid를 입력하면 이 필드는 적용되지 않음 */
  @SerializedName("stock_id")
  @Expose(serialize = false)
  private String stockId;

  /** 쿠폰 상태 설명: 대금권 상태: SENDED-사용 가능, USED-실제 차감됨, available_mchid를 입력하면 이 필드는 적용되지 않음 */
  @SerializedName("status")
  @Expose(serialize = false)
  private String status;

  /** 배치 생성 방 가맹점 번호 설명: 배치 생성 방 가맹점 번호. 배치 생성 방 가맹점 번호, 배치 발급 가맹점 번호, 사용 가능 가맹점 번호 세 매개변수 중 하나를 선택 입력. */
  @SerializedName("creator_mchid")
  @Expose(serialize = false)
  private String creatorMchid;

  /** 배치 발급 가맹점 번호 설명: 배치 발급 가맹점 번호. 배치 생성 방 가맹점 번호, 배치 발급 가맹점 번호, 사용 가능 가맹점 번호 세 매개변수 중 하나를 선택 입력. */
  @SerializedName("sender_mchid")
  @Expose(serialize = false)
  private String senderMchid;

  /** 사용 가능 가맹점 번호 설명: 사용 가능 가맹점 번호. 배치 생성 방 가맹점 번호, 배치 발급 가맹점 번호, 사용 가능 가맹점 번호 세 매개변수 중 하나를 선택 입력. */
  @SerializedName("available_mchid")
  @Expose(serialize = false)
  private String availableMchid;

  /** 페이지 번호 설명: 페이지 번호, 기본값 0, available_mchid를 입력하면 이 필드는 적용되지 않음 */
  @SerializedName("offset")
  @Expose(serialize = false)
  private Integer offset;

  /** 페이지 크기 설명: 페이지 크기, 기본값 20, available_mchid를 입력하면 이 필드는 적용되지 않음 */
  @SerializedName("limit")
  @Expose(serialize = false)
  private Integer limit;

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getCreatorMchid() {
    return creatorMchid;
  }

  public void setCreatorMchid(String creatorMchid) {
    this.creatorMchid = creatorMchid;
  }

  public String getSenderMchid() {
    return senderMchid;
  }

  public void setSenderMchid(String senderMchid) {
    this.senderMchid = senderMchid;
  }

  public String getAvailableMchid() {
    return availableMchid;
  }

  public void setAvailableMchid(String availableMchid) {
    this.availableMchid = availableMchid;
  }

  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCouponsByFilterRequest {\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creatorMchid: ").append(toIndentedString(creatorMchid)).append("\n");
    sb.append("    senderMchid: ").append(toIndentedString(senderMchid)).append("\n");
    sb.append("    availableMchid: ").append(toIndentedString(availableMchid)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
