// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** ListStocksRequest */
public class ListStocksRequest {
  /** 페이지 번호 설명: 페이지 번호는 0부터 시작, 기본값은 0페이지 */
  @SerializedName("offset")
  @Expose(serialize = false)
  private Integer offset;

  /** 페이지 크기 설명: 페이지 크기, 최대 10 */
  @SerializedName("limit")
  @Expose(serialize = false)
  private Integer limit;

  /** 배치 생성 방 가맹점 번호 설명: 배치 생성 방 가맹점 번호 */
  @SerializedName("stock_creator_mchid")
  @Expose(serialize = false)
  private String stockCreatorMchid;

  /** 시작 시간 설명: 시작 생성 시간 */
  @SerializedName("create_start_time")
  @Expose(serialize = false)
  private String createStartTime;

  /** 종료 시간 설명: 종료 생성 시간 */
  @SerializedName("create_end_time")
  @Expose(serialize = false)
  private String createEndTime;

  /** 배치 상태 설명: 배치 상태: unactivated-미활성화; audit-심사 중; running-실행 중; stoped-중지됨; paused-발급 일시 중지 */
  @SerializedName("status")
  @Expose(serialize = false)
  private String status;

  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public String getStockCreatorMchid() {
    return stockCreatorMchid;
  }

  public void setStockCreatorMchid(String stockCreatorMchid) {
    this.stockCreatorMchid = stockCreatorMchid;
  }

  public String getCreateStartTime() {
    return createStartTime;
  }

  public void setCreateStartTime(String createStartTime) {
    this.createStartTime = createStartTime;
  }

  public String getCreateEndTime() {
    return createEndTime;
  }

  public void setCreateEndTime(String createEndTime) {
    this.createEndTime = createEndTime;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListStocksRequest {\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    stockCreatorMchid: ").append(toIndentedString(stockCreatorMchid)).append("\n");
    sb.append("    createStartTime: ").append(toIndentedString(createStartTime)).append("\n");
    sb.append("    createEndTime: ").append(toIndentedString(createEndTime)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
