// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/** ListAvailableSingleitemsRequest */
public class ListAvailableSingleitemsRequest {
  /** 페이지 번호 설명: 페이지 번호, 최대 500 */
  @SerializedName("offset")
  @Expose(serialize = false)
  private Integer offset;

  /** 페이지 크기 설명: 페이지 크기, 최대 100 */
  @SerializedName("limit")
  @Expose(serialize = false)
  private Integer limit;

  /** 배치 생성 방 가맹점 번호 설명: 배치 생성 방 가맹점 번호 */
  @SerializedName("stock_creator_mchid")
  @Expose(serialize = false)
  private String stockCreatorMchid;

  /** 배치 번호 설명: 배치 번호 */
  @SerializedName("stock_id")
  @Expose(serialize = false)
  private String stockId;

  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public String getStockCreatorMchid() {
    return stockCreatorMchid;
  }

  public void setStockCreatorMchid(String stockCreatorMchid) {
    this.stockCreatorMchid = stockCreatorMchid;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAvailableSingleitemsRequest {\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    stockCreatorMchid: ").append(toIndentedString(stockCreatorMchid)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
