// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** MediaImageRequest */
public class MediaImageRequest {
  /** 이미지 파일 설명: 미디어 이미지를 이진 변환하여 얻은 미디어 이미지 이진 내용, 요청 body에서 이 이진 내용을 업로드. 미디어 이미지는 JPG, BMP, PNG 형식만 지원, 파일 크기는 2M를 초과할 수 없음. */
  @SerializedName("file")
  private FormFile file;

  /** 미디어 파일 메타 정보 설명: */
  @SerializedName("meta")
  private ImageMeta meta;

  public FormFile getFile() {
    return file;
  }

  public void setFile(FormFile file) {
    this.file = file;
  }

  public ImageMeta getMeta() {
    return meta;
  }

  public void setMeta(ImageMeta meta) {
    this.meta = meta;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaImageRequest {\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
