// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;

/** StartStockResponse */
public class StartStockResponse {
  /**
   * 유효 시간
   * 설명: 유효 시간, [rfc3339 표준 형식](https://datatracker.ietf.org/doc/html/rfc3339) 준수, 형식은 yyyy-MM-DDTHH:mm:ss.sss+TIMEZONE, yyyy-MM-DD는 년월일, T는 문자열에 나타나며 time 요소의 시작을 의미, HH:mm:ss는 시분초, TIMEZONE은 시간대(+08:00은 동부 8구 시간대, UTC보다 8시간 앞서며 베이징 시간). 예: 2015-05-20T13:29:35+08:00은 베이징 시간 2015년 5월 20일 13시 29분 35초를 의미.
   */
  @SerializedName("start_time")
  private String startTime;

  /** 배치 번호 설명: 배치 번호 */
  @SerializedName("stock_id")
  private String stockId;

  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public String getStockId() {
    return stockId;
  }

  public void setStockId(String stockId) {
    this.stockId = stockId;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StartStockResponse {\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    stockId: ").append(toIndentedString(stockId)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
