// Copyright 2021 Tencent Inc. All rights reserved.
//
// 위챗페이 마케팅 시스템 오픈 API
//
// 신규 즉시 할인 금액 API
//
// API version: 3.4.0

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.cashcoupons.model;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

import com.google.gson.annotations.SerializedName;
import java.util.List;

/** StockCollection */
public class StockCollection {
  /** 배치 총수 설명: 조회 조건에 맞는 총 수량 */
  @SerializedName("total_count")
  private Long totalCount;

  /** 배치 상세 설명: 배치 상세 */
  @SerializedName("data")
  private List<Stock> data;

  /** 페이지 크기 설명: 페이지 크기, 최대 10 */
  @SerializedName("limit")
  private Integer limit;

  /** 페이지 번호 설명: 페이지 번호는 0부터 시작, 기본값은 0페이지 */
  @SerializedName("offset")
  private Integer offset;

  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }

  public List<Stock> getData() {
    return data;
  }

  public void setData(List<Stock> data) {
    this.data = data;
  }

  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockCollection {\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
